<form class="form-horizontal">
	<div class="control-group">
		<label class="control-label" for="filterVetoRaison">Raison sociale</label>
		<div class="controls">
			<input class="search-query" dojoType="dijit.form.TextBox" id="filterVetoRaison" type="text" onkeyup="filterVeto('<?php echo $this->gridName ?>')" />
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="filterVetoCp">Code postal</label>
		<div class="controls">
			<input class="search-query" dojoType="dijit.form.TextBox" id="filterVetoCp" type="text" onkeyup="filterVeto('<?php echo $this->gridName ?>')" />
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="filterVetoVille">Ville</label>
		<div class="controls">
			<input class="search-query" dojoType="dijit.form.TextBox" id="filterVetoVille" type="text" onkeyup="filterVeto('<?php echo $this->gridName ?>')" />
		</div>
	</div>
</form>
