Raison sociale :
<span>
  <input dojoType="dijit.form.TextBox" style="width:120px" id="filterVetoRaison" type="text" onkeyup="filterVeto('<?php echo $this->gridName ?>')" />
</span>
Code postal :
<span>
  <input dojoType="dijit.form.TextBox" style="width:50px" id="filterVetoCp" type="text" onkeyup="filterVeto('<?php echo $this->gridName ?>')" />
</span>
Ville :
<span>
  <input dojoType="dijit.form.TextBox" style="width:100px" id="filterVetoVille" type="text" onkeyup="filterVeto('<?php echo $this->gridName ?>')" />
</span>