<thead>
  <tr>
    <th field="nom" width="18px" get="formatRowNum">#</th>
    <th field="id" hidden="true" width="25px">Id</th>
    <th field="raison" width="150px" formatter="formatUpperCaseBold">Raison sociale</th>
    <th field="adresse" width="150px">Adresse</th>
    <th field="cp" width="50px">Code postal</th>
    <th field="ville" width="80px" formatter="formatUpperCase">Ville</th>
    <th field="portable" width="80px">Portable</th>
    <th field="fixe" width="80px">Fixe</th>
  </tr>
</thead>