<?php if ($this->filterPath) { ?>
<div class="accordion" id="filters">
	<div class="accordion-group">
		<div class="accordion-heading">
			<a class="accordion-toggle btn" data-toggle="collapse" data-parent="#filters" href="#collapseOne">
				<i class="icon-filter"></i> Filtre(s)
			</a>
		</div>
		<div id="collapseOne" class="accordion-body collapse">
			<div class="accordion-inner">
				<?php echo $this->render($this->filterPath) ?>
			</div>
		</div>
	</div>
</div>
<?php }?>