<div class="centre_principal">
  <h2>Administration</h2>
  <h3>Indicateurs</h3>
  <ul>
    <li><i class="icon-ok"></i> <span class="badge badge-info"><?php echo $this->indicNbChatsAdoption?></span> chats à l'adoption (dont <span class="badge badge-success"><?php echo $this->indicNbChatsRes ?></span> réservé(s)) avec fiche validée</li>
    <li><i class="icon-ok"></i> <span class="badge badge-important"><?php echo $this->indicNbFichesAValider?></span> fiche(s) de chat à valider</li>
    <li><i class="icon-ok"></i> <span class="badge badge-success"><?php echo $this->indicNbFaDispo?></span> FA disponible(s)</li>
    <li><i class="icon-ok"></i> <span class="badge badge-info"><?php echo $this->indicNbFaActive?></span> FA active(s)</li>
  </ul>
  <h3>Exports</h3>
  <div>
    <button class="btn" onclick="exportData('<?php echo $this->urlExportChatUrl ?>')"><i class="icon-download-alt"></i> Export chats</button>
    <button class="btn" onclick="exportData('<?php echo $this->urlExportFaUrl ?>')"><i class="icon-download-alt"></i> Export FA</button>
    <button class="btn" onclick="exportData('<?php echo $this->urlExportAdoptantUrl ?>')"><i class="icon-download-alt"></i> Export adoptants</button>
    <button class="btn" onclick="exportData('<?php echo $this->urlExportContactUrl ?>')"><i class="icon-download-alt"></i> Export contacts</button>
  </div>
  <h3>Pages spéciales</h3>
  <div>
    <button class="btn" onclick="exportData('<?php echo $this->urlTableauChatUrl ?>')"><i class="icon-th"></i> Tableau chats pour impression</button>
  </div>
</div>