<div class="align-center">
  <h3><?php echo $this->titre ?></h3>

  <h4><span id="nbElements"><?php echo $this->nbElements?></span> élément(s)</h4>
</div>
<div>
  <div id="commonGridStore" data-dojo-type="dojox/data/QueryReadStore" clientSort="true" jsId="commonGridStore" url="<?php echo $this->urlListeJson ?>" requestMethod="post">
  </div>

  <?php echo $this->render('admin/filter.phtml'); ?>

  <div data-dojo-type="dijit/Menu" jsid="gridMenu" style="display: none;">
    <div data-dojo-type="dojox/widget/PlaceholderMenuItem" label="GridColumns"></div>
  </div>
  <div style="text-align:left">
    <div class="grid">
      <div id="loadGrid" class="ajax" style="display:block"></div>
      <table id="commonGrid" 
      rowsPerPage="13" 
      columnReordering="true"
      sortInfo="<?php echo $this->defaultSort ?>" 
      jsId="commonGrid" 
      data-dojo-type="dojox/grid/DataGrid" 
      store="commonGridStore" 
      selectable="true" 
      noDataMessage="Pas de données."
      headerMenu="gridMenu"
      <?php if ($this->initFilter) {?>
      query="<?php echo $this->initFilter ?>"
      <?php }?>
      >

      <script type="dojo/connect" event="_onFetchBegin" args="event">initGrid(this.id);</script> 
      <script type="dojo/connect" event="_onFetchComplete" args="event">endGrid(this.id);</script>

      <?php echo $this->partial($this->headerPath) ?>
      <?php if ( !$this->redefineButtons) {
       echo $this->render('admin/gridactions.phtml');
     } else {
      echo $this->render($this->redefineButtons);
    }?>
  </table>
</div>
</div>
<div>
  <?php if ($this->urlExportUrl) {?>
  <button class="btn btn-action pull-right" onclick="exportData('<?php echo $this->urlExportUrl ?>', 'commonGrid')"><i class="icon-download-alt"></i> Export excel</button>
  <?php }?>
  <?php if ( !$this->redefineButtons) {?>
  <button class="btn btn-action" onclick="addItem('<?php echo $this->urlAddItem ?>')"><i class="icon-plus"></i> Ajouter</button>
  <button class="btn btn-action" onclick="editItem('<?php echo $this->urlEditItem ?>', 'commonGrid')"><i class="icon-pencil"></i> Editer</button>
  <button class="btn btn-action" onclick="deleteItem('<?php echo $this->urlDeleteItem ?>', 'commonGrid')"><i class="icon-trash"></i> Supprimer</button>
  <?php }?>
</div>
</div>