<div class="centre_principal">
  <h2>Administration</h2>
  <h3>Indicateurs</h3>
  <ul>
    <li><i class="icon-ok"></i> <?php echo $this->indicNbChatsAdoption?> chats à l'adoption (dont réservé(s) : <?php echo $this->indicNbChatsRes ?>)</li>
    <li><i class="icon-ok"></i> <?php echo $this->indicNbFichesAValider?> fiche(s) de chat à valider</li>
    <li><i class="icon-ok"></i> <?php echo $this->indicNbFaDispo?> FA disponible(s)</li>
    <li><i class="icon-ok"></i> <?php echo $this->indicNbFaActive?> FA active(s)</li>
  </ul>
  <h3>Exports</h3>
  <div>
    <button class="btn" onclick="exportData('<?php echo $this->urlExportChatUrl ?>')"><i class="icon-download-alt"></i> Export chats</button>
    <button class="btn" onclick="exportData('<?php echo $this->urlExportFaUrl ?>')"><i class="icon-download-alt"></i> Export FA</button>
    <button class="btn" onclick="exportData('<?php echo $this->urlExportAdoptantUrl ?>')"><i class="icon-download-alt"></i> Export adoptants</button>
    <button class="btn" onclick="exportData('<?php echo $this->urlExportContactUrl ?>')"><i class="icon-download-alt"></i> Export contacts</button>
  </div>
  <h3>Pages spéciales</h3>
  <div>
    <button class="btn" onclick="exportData('<?php echo $this->urlTableauChatUrl ?>')"><i class="icon-th"></i> Tableau chats pour impression</button>
  </div>
</div>