<div class="centre_principal">
  <h3><?php echo $this->titre ?></h3>
  <br>
  <div data-dojo-type="dojox/data/QueryReadStore" clientSort="true" jsId="gridChatStore" url="<?php echo $this->urlChatListeJson ?>"></div>
  <?php echo $this->render('admin/filter.phtml'); ?>
  <div data-dojo-type="dijit/Menu" jsid="gridMenuChat" style="display: none;">
        <div data-dojo-type="dojox/widget/PlaceholderMenuItem" label="GridColumns"></div>
  </div>
  <div style="text-align:left">
  <div class="chatFaAjoutGrid">
    <table id='gridChatSelection'
           headerMenu="gridMenuChat"
           rowsPerPage="15"  
           columnReordering="true"
           sortInfo="3" 
           jsId="gridChatSelection" 
           data-dojo-type="dojox/grid/DataGrid" 
           store="gridChatStore" selectable="true" 
           selectionMode="single" 
           noDataMessage="Pas de chats">
      <?php echo $this->partial($this->headerChatPath) ?>
      <script type="dojo/connect" event="_onFetchBegin" args="event">initGrid(this.id);</script>
      <script type="dojo/connect" event="_onFetchComplete" args="event">endGrid(this.id);</script>
      <script type="dojo/method" event="onDblClick" args="event">hideTooltip(event);editItem('<?php echo $this->urlSelectChat ?>', 'gridChatSelection',  'chats', 'chargementChats', false, 'idChat')</script>
      <script type="dojo/method" event="onCellMouseOver" args="event">showTooltipAjout(event)</script>
      <script type="dojo/method" event="onCellMouseOut" args="event">hideTooltip(event)</script>
    </table>
  </div>
  </div>
  <button class="btn" onclick="editItem('<?php echo $this->urlSelectChat ?>', 'gridChatSelection',  'chats', 'chargementChats', false, 'idChat')"><i class="icon-plus"></i> Ajouter</button>
  <button class="btn" onclick="addItem('<?php echo $this->urlRetourListeChat ?>', 'chats', 'chargementChats', false)"><i class="icon-arrow-left"></i> Retour</button>
</div>