<div class="centre_principal">

  <h3><?php echo $this->titre ?></h3>
  <br>
  <div data-dojo-type="dojox/data/QueryReadStore" clientSort="true" jsId="gridAdStore" url="<?php echo $this->urlAdListeJson ?>"></div>
  <?php echo $this->render('admin/filter.phtml'); ?>
  
  <div style="text-align:left">
    <div class="grid">
    
    <div data-dojo-type="dijit/Menu" jsid="gridMenuAd" style="display: none;">
        <div data-dojo-type="dojox/widget/PlaceholderMenuItem" label="GridColumns"></div>
    </div>
    
    <table id='gridAdSelection' 
           headerMenu="gridMenuAd"
           rowsPerPage="15" 
           columnReordering="true" 
           sortInfo="3" 
           jsId="gridAdSelection" 
           data-dojo-type="dojox/grid/DataGrid" 
           store="gridAdStore" 
           selectable="true" 
           selectionMode="single" 
           noDataMessage="Pas d'adoptant">
      <?php echo $this->partial($this->headerAdPath) ?>
      
      <script type="dojo/connect" event="_onFetchBegin" args="event">initGrid(this.id);</script>
      <script type="dojo/method" event="onDblClick" args="event">hideTooltip(event);editItem('<?php echo $this->urlSelectAd ?>', 'gridAdSelection',  'corps', 'chargementCorps', false, 'idNewAd')</script>
      <script type="dojo/method" event="onCellMouseOver" args="event">showTooltipAjout(event)</script>
      <script type="dojo/method" event="onCellMouseOut" args="event">hideTooltip(event)</script>
    </table>
  </div>
</div>

  <button class="btn btn-action" onclick="editItem('<?php echo $this->urlSelectAd ?>', 'gridAdSelection',  'corps', 'chargementCorps', false, 'idNewAd')"><i class="icon-hand-up"></i> Sélectionner</button>
  <button class="btn btn-action" onclick="addItem('<?php echo $this->urlRetourListeChat ?>', 'corps', 'chargementCorps', false)"><i class="icon-arrow-left"></i> Retour</button>
</div>