<div class="centre_principal">

  <h3><?php echo $this->titre ?></h3>
  <br>
  <div dojoType="dojox.data.QueryReadStore" clientSort="true" jsId="gridAdStore" url="<?php echo $this->urlAdListeJson ?>"></div>
  <?php echo $this->render('admin/filter.phtml'); ?>
  
  <div style="text-align:left">
    <div class="grid">
    
    <div dojoType="dijit.Menu" jsid="gridMenuAd" style="display: none;">
        <div dojoType="dojox.widget.PlaceholderMenuItem" label="GridColumns"></div>
    </div>
    
    <table id='gridAdSelection' 
           headerMenu="gridMenuAd"
           rowsPerPage="15" 
           columnReordering="true" 
           sortInfo="3" 
           jsId="gridAdSelection" 
           dojoType="dojox.grid.DataGrid" 
           store="gridAdStore" 
           selectable="true" 
           selectionMode="single" 
           noDataMessage="Pas d'adoptant">
      <?php echo $this->partial($this->headerAdPath) ?>
      
      <script type="dojo/connect" event="_onFetchBegin" args="event">initGrid(this.id);</script>
      <script type="dojo/method" event="onDblClick" args="event">editItem('<?php echo $this->urlSelectAd ?>', 'gridAdSelection',  'corps', 'chargementCorps', false, 'idNewAd')</script>
      <script type="dojo/method" event="onCellMouseOver" args="event">showTooltipAjout(event)</script>
      <script type="dojo/method" event="onCellMouseOut" args="event">hideTooltip(event)</script>
    </table>
  </div>
</div>

  <button id="selectionButton" dojoType="dijit.form.Button" onclick="editItem('<?php echo $this->urlSelectAd ?>', 'gridAdSelection',  'corps', 'chargementCorps', false, 'idNewAd')"><div class="ficheAjouter"></div><div class="boutonFiche">Sélectionner</div></button>
  <button id="retourButton" dojoType="dijit.form.Button" onclick="addItem('<?php echo $this->urlRetourListeChat ?>', 'corps', 'chargementCorps', false)"><div class="boutonRetour"></div><div class="boutonFiche">Retour</div></button>
</div>