Nom :
<span>
  <input dojoType="dijit.form.TextBox" style="width:120px" id="filterAdNom" type="text" onkeyup="filterAdoptant('<?php echo $this->gridName ?>')" />
</span>
Prénom :
<span>
  <input dojoType="dijit.form.TextBox" style="width:120px" id="filterAdPrenom" type="text" onkeyup="filterAdoptant('<?php echo $this->gridName ?>')" />
</span>
Login :
<span>
  <input dojoType="dijit.form.TextBox" style="width:120px" id="filterAdLogin" type="text" onkeyup="filterAdoptant('<?php echo $this->gridName ?>')" />
</span>