<form class="form-horizontal">
	<div class="control-group">
		<label class="control-label" for="filterAdNom">Nom</label>
		<div class="controls">
			<input data-dojo-type="dijit/form/TextBox" class="search-query" id="filterAdNom" type="text" onkeyup="filterAdoptant('<?php echo $this->gridName ?>')" />
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="filterAdPrenom">Prénom</label>
		<div class="controls">
			<input data-dojo-type="dijit/form/TextBox" class="search-query" id="filterAdPrenom" type="text" onkeyup="filterAdoptant('<?php echo $this->gridName ?>')" />
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="filterAdLogin">Login</label>
		<div class="controls">
			<input data-dojo-type="dijit/form/TextBox" class="search-query" id="filterAdLogin" type="text" onkeyup="filterAdoptant('<?php echo $this->gridName ?>')" />
		</div>
	</div>
</form>