<div class="centre_principal" id="replace">
  <h3><?php echo $this->titreChat ?></h3>
  <h4><span id="nbElements"><?php echo $this->nbChats?></span> chat(s)</h4>
  <br>
  <div dojoType="dojox.data.QueryReadStore" sortInfo="3" clientSort="true" jsId="gridChatStore" url="<?php echo $this->urlChatListeJson ?>"></div>
  
  <div dojoType="dijit.Menu" jsid="gridChatAd" style="display: none;">
        <div dojoType="dojox.widget.PlaceholderMenuItem" label="GridColumns"></div>
  </div>
  <div style="text-align:left">  
  <div class="chatFaGrid">
    <table id="gridChat" 
           rowsPerPage="15"
           headerMenu="gridChatAd"
           columnReordering="true"
           sortInfo="3" 
           jsId="gridChat" 
           dojoType="dojox.grid.DataGrid" 
           store="gridChatStore" 
           selectable="true" 
           selectionMode="single" 
           noDataMessage="Pas de chat adopté.">
      <script type="dojo/connect" event="_onFetchBegin" args="event">initGrid(this.id);</script>
      <script type="dojo/connect" event="_onFetchComplete" args="event">endGrid(this.id);</script>
      <?php echo $this->partial($this->headerChatPath) ?>
    </table>
  </div>
  </div>
  <button class="btn btn-action" onclick="addItem('<?php echo $this->urlChatAddItem ?>', 'chats', 'chargementChats', false)"><i class="icon-plus"></i> Ajouter</button>
  <button class="btn btn-action" onclick="deleteItem('<?php echo $this->urlChatDeleteItem ?>', 'gridChat', 'idChat')"><i class="icon-trash"></i> Supprimer</button>
  <button class="btn btn-action" onclick="editItem('<?php echo $this->urlChatEditItem ?>', 'gridChat', 'corps', 'chargementCorps')"><i class="icon-pencil"></i> Editer</button>
</div>