<thead>
  <tr>
    <th field="Nom" width="18px" get="formatRowNum">#</th>
    <th field="id" hidden="true" width="25px">Id</th>
    <th field="nom" width="80px" formatter="formatUpperCaseBold">Nom</th>
    <th field="libSexe" width="30px" formatter="formatSexe">Sexe</th>
    <th field="date" width="90px" formatter="formatDate">Date de naissance</th>
    <th field="date_adoption" width="85px" formatter="formatDate">Date d'adoption</th>
    <th field="fa" width="110px">FA</th>
    <th field="adoptant" width="110px">Adoptant</th>
  </tr>
</thead>