<thead>
  <tr>
    <th field="nom" width="18px" get="formatRowNum">#</th>
    <th field="id" hidden="true" width="25px">Id</th>
    <th field="dateSubmit" formatter="formatDate" width="90px">Date</th>
    <th field="nom" width="150px" formatter="formatUpperCaseBold">Nom</th>
    <th field="prenom" width="100px" formatter="formatUcfirst">Prénom</th>
    <th field="login" width="70px">Login</th>
    <th field="chatsAdoptes" width="90px">Adopté(s)</th>
    <th field="repere" width="70px">Repéré</th>
    <th field="cp" hidden="true" width="40px">Code postal</th>
    <th field="ville" width="120px" formatter="formatUpperCase">Ville</th>
    <th field="portable" width="80px">Portable</th>
    <th field="fixe" width="80px">Fixe</th>
  </tr>
</thead>