<div class="centre_principal">
  <?php echo $this->render("admin/indexgrid.phtml"); ?>
  <button class="btn btn-action" onclick="addItem('<?php echo $this->urlAddItem ?>')"><i class="icon-plus"></i> Ajouter</button>
  <button class="btn btn-action" onclick="editItem('<?php echo $this->urlEditItem ?>', 'commonGrid')"><i class="icon-pencil"></i> Editer</button>
  <button class="btn btn-action" onclick="editItem('<?php echo $this->urlChatAdItem ?>', 'commonGrid')"><i class="icon-search"></i> Chat(s) adopté(s)</button>
  <button class="btn btn-action" onclick="deleteItem('<?php echo $this->urlDeleteItem ?>', 'commonGrid')"><i class="icon-trash"></i> Supprimer</button>
</div>