<div class="centre_principal">
<h2>Merci pour votre candidature.</h2>
<p>
Nous vous remercions d'avoir pris le temps de répondre à nos questions. 
Ce questionnaire est volontairement très précis afin de définir ensemble le ou les chats qui vous correspondraient le mieux. 
</p>
<p>
En effet, comme vous le savez peut-être déjà, chaque chat est différent, chaque chat a son caractère et sa personnalité, et tous les chats ne peuvent pas être placés dans tous les foyers (par exemple, nous ne mettrons pas un chat qui a tendance à griffer avec de jeunes enfants, ou encore un chat qui ne supporte pas l'enfermement n'ira pas en appartement). 
</p>
<p>
Ce questionnaire n'est donc pas là pour faire la police, mais pour vous satisfaire au mieux dans votre recherche. 
Il est gage du sérieux de notre association
</p>
  <ul>
    <li id="signature">L'équipe FELIN POSSIBLE</li>
  </ul>
</div>