<div class="centre_principal">
	<h2>Merci pour votre candidature.</h2>
	<p>
		Nous vous remercions d'avoir pris le temps de répondre à nos questions. 
		Ce questionnaire est volontairement très précis afin de définir ensemble le ou les chats qui vous correspondraient le mieux. 
	</p>
	<p>
		En effet, comme vous le savez peut-être déjà, chaque chat est différent, chaque chat a son caractère et sa personnalité, et tous les chats ne peuvent pas être placés dans tous les foyers (par exemple, nous ne mettrons pas un chat qui a tendance à griffer avec de jeunes enfants, ou encore un chat qui ne supporte pas l'enfermement n'ira pas en appartement). 
	</p>
	<p>
		Ce questionnaire n'est donc pas là pour faire la police, mais pour vous satisfaire au mieux dans votre recherche. 
		Il est gage du sérieux de notre association
	</p>
	<ul>
		<li id="signature">L'équipe FELIN POSSIBLE</li>
	</ul>
</div>
<div class="centre_principal align-center">
	<p>Pour vous équiper en vue de votre future adoption, visitez notre partenaire:
		<address>
			<strong>Ki-Kazh</strong></br>
			9 rue Victor Hugo</br>
			35000 RENNES</br>
			02 99 51 96 67</br>
			contact@ki-kazh.com</br>
			<i class="icon-globe"></i> <a href="www.ki-kazh.com">www.ki-kazh.com</a></br>
			<i class="icon-globe"></i> <a href="www.facebook.fr/kikazhrennes">www.facebook.fr/kikazhrennes</a></br>
		</address>
	</p>
	<img src="http://img607.imageshack.us/img607/8656/vyt1.jpg"></img>
		
</div>
