<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal">
	<br>
	<h2>Devenir Adhérent</h2>
	<p>
		Si vous souhaitez adhérer à notre association ou tout simplement faire un don,
		vous pouvez télécharger le fichier ci dessous, l'imprimer et nous le renvoyer complété et
		accompagné de votre chèque libellé à l'ordre de FELIN POSSIBLE, à l'adresse suivante:
	</p>
	<p>
	<?php echo $this->render('index/adress.phtml'); ?>
	</p>
	<p>
		Tout don de 25 euros et plus fera de vous un adhérent de l'association.
	</p>
	<p>
		Etre adhérent vous donne le droit d'assister et de voter lors des assemblées générales,
		et des avantages que vous découvrirez une fois adhérents. :)
	</p>
	<p>
		Merci de la part de toute l'équipe pour votre soutien.
	</p>

	<p>
		<b>Fichier à télécharger (version pdf) : </b> <a href="http://www.felinpossible.fr/site/public/documents/FP_ADHESION_2012.pdf">cliquez-ici <i class=" icon-file"></i></a>
	</p>
</div>
