<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal">
<h2>Pourquoi adopter dans une association</h2>

<p>
Pourquoi adopter dans une association alors que les annonces de particuliers pullulent de partout ?
</p>
<p>
Tout d'abord pour faire une <u>bonne action</u>.
Les chatons présents dans les associations ont bien souvent perdu leur mère, ils ont eu un mauvais départ dans la vie.
En les adoptant, vous donnez à ces petits orphelins la chance de vivre dans un foyer et de recevoir de l'amour !
De plus, ce n'est pas parce qu'ils ont perdu leur mère jeunes qu'ils ne sont pas câlins, bien au contraire.
Ces chatons sont pour certains nourris au biberon et développent une relation toute particulière avec l'humain.
La plupart restent très câlins toute leur vie !
</p>
<p>
Adopter en association, c'est aussi avoir la certitude que votre chat est en <u>bonne santé</u>.
Combien de particuliers ne font pas les tests FIV et FELV (leucose féline, première cause de mortalité chez nos amis félins) ?
Presque tous. En adoptant chez un particulier ou dans une animalerie, vous risquez de vous retrouver avec un chat malade, et des frais vétérinaires à la clef.
Les chats des associations sont testés et vaccinés. C'est la meilleure garantie qu'ils soient en bonne santé ! De plus, adopter en association, c'est aussi être en <u>adéquation avec la loi</u>.
Selon la loi, il est interdit de donner ou vendre un chaton de moins de 8 semaines. Il est aussi interdit de céder un chat ou chaton non-identifié.
En adoptant ou en donnant un chaton non-tatoué ou pucé, vous êtes donc hors-la-loi.
</p>
<p>
Adopter en association, c'est pouvoir adopter en toute confiance, pouvoir obtenir des <u>conseils</u>, poser des questions sur l'éducation du chat.
Avoir un service "après-vente" également, avec possibilité d'une période d'essai. Il y a des erreurs à ne pas commettre avec un chat, et particulièrement avec un chaton, et les associations sont là pour vous conseiller et vous aider.
</p>
<p>
De plus, auprès d'une association spécialisée dans la protection féline comme <b>FELIN POSSIBLE</b>, vous êtes sûrs de tomber sur des passionnés de chats, qui s'y connaissent, et par conséquent seront de bon conseil.
</p>
<p>
Alors c'est vrai qu'en adoptant dans une association, il y a des frais. Alors que chez un particulier, c'est gratuit.
Mais les associations ne vendent pas leurs chats, elles ne font aucun bénéfice sur l'argent qu'elles reçoivent.
L'argent que vous donnez lors d'une adoption dans une association sert à <u>rembourser les frais vétérinaires</u> engagés pour le chat: les tests, les vaccins, l'identification, le tatouage etc...
Ces frais, si vous prenez bien soin de votre chat, vous les aurez à payer également chez votre vétérinaire, même en adoptant gratuitement un chat à un particulier. 
Vous aurez même 2 fois plus à débourser, car les associations bénéficient de tarifs très avantageux auprès des vétérinaires. Donc vous avez tout intérêt, financièrement parlant, à passer par une association.
</p>
<p>
Adopter chez un particulier, enfin, c'est participer au problème de la <u>surpopulation féline</u>, dont vous n'êtes peut-être pas conscient, mais qui est bien réel.
Il suffit de regarder les petites annonces de chatons qui fleurissent au printemps et le taux de remplissage des refuges.
Il y a bien plus de naissances chaque année, que d'adoptants. A cause de ça, chaque année, des chatons sont euthanasiés ou finissent leur vie dans un refuge, alors que leur place devrait être au sein d'une famille aimante.
A l'inverse, adopter en association, c'est leur donner un coup de pouce et lutter contre ce fléau
</p>
<p>
A tous les futurs adoptants de nos chats, voici <b>les clauses</b> que vous retrouverez sur le contrat d'adoption, et donc ce à quoi <b>vous vous engagez en adoptant</b> par le biais de notre association.
</p>
<p>
En adoptant ce chat, je m'engage :	
<ul>
<li>à m'en occuper de manière responsable</li>	
<li>à lui prodiguer nourriture, amour et soin au quotidien</li>	
<li>à le garder durant toute sa vie et ne jamais l'abandonner</li>	
<li>à le faire vacciner chaque année</li>	
<li>à le faire stériliser dès ses 6 mois s'il s'agit d'un chaton, et à ne pas faire naître de portée</li>	
<li>à signaler au fichier national félin tout changement de coordonnées (adresse, téléphone, etc)</li>	
<li>à le faire examiner par un vétérinaire en cas de blessure ou de maladie</li>	
<li>à ce qu'il vive avec les autres membres de la famille dans le même lieu de vie</li>	
<li>à donner des nouvelles régulièrement à l'association Félin Possible</li>	
<li>à accepter une ou plusieurs visites de Félin Possible dans le cadre du suivi post-adoption</li>	
<li>à restituer le chat à l'association Félin Possible en cas de séparation inévitable</li>
</ul>
</p>
<br>
<h2>Questions à se poser avant toute adoption</h2>
<br>
<p>
S'il est facile d'avoir un coup de coeur pour un chat, toute adoption doit néanmoins être mûrement réflêchie. Une adoption ne doit JAMAIS se faire sur un coup de tête.
Afin de vous aider dans votre réflexion, voici quelques questions que tout adoptant devrait se poser AVANT de franchir le pas :
</p>
<p>
<b><u>1- Suis-je prêt à m'engager pour 15 ans, voire plus ?</u></b>
En effet, l'espérance de vie moyenne d'un chat est de 15 ans, mais les plus chanceux peuvent vivre jusqu'à plus de 20 ans !
En adoptant un chat, vous vous engagez à vous en occuper durant tout sa vie. Il ne s'agit pas de le redonner au moindre changement de situation personnelle ou professionnelle.
</p>
<p>
<b><u>2- Ai-je suffisamment de temps libre pour m'occuper d'un chat au quotidien ?</u></b>
S'occuper d'un chat ne demande pas, comme pour un chien, de sorties quotidiennes.
Le chat étant indépendant, s'il veut sortir et s'il en a la possibilité, il le fera seul.
Mais un chat nécessite néanmoins une attention et des soins quotidiens, que ce soit pour le nettoyage de la litière, le brossage (particulièrement pour les chats à poils longs), les séances de jeux (1h par jour) etc…
</p>
<p>
<b><u>3- Ai-je les moyens financiers nécessaires pour subvenir aux besoins d'un chat ?</u></b>
Et oui, un chat nécessite un certain budget, qui n'est pas forcément à la portée de toutes les bourses.
Les croquettes de qualité coûtent cher (comptez 15 euros par mois pour un chat). Les sacs de litière (plus ou moins chers selon les marques) sont à renouveler chaque semaine.
Il faut aussi penser aux frais d'anti-puces (à renouveler chaque mois), au vermifuge (tous les 4/6 mois).
Il ne faut pas oublier les frais de vétérinaires, que ce soit pour le rappel des vaccins ou encore les frais imprévus, qui peuvent monter très vite, en cas de maladie ou de blessure.
</p>
<p>
<b><u>4- Que ferai-je de mon chat pendant les vacances ?</u></b>
Les vacances, particulièrement les grandes vacances des mois de juillet et août, sont toujours appréciées des petits comme des grands.
Malheureusement c'est aussi la période de l'année où est enregistré chaque année le plus grand nombre d'abandons de chats, par des maîtres n'ayant pas trouvé de solution de garde pour leur petit compagnon.
Sachez que de nombreuses solutions existent (prêt de sa maison, visite quotidienne au domicile, pension féline etc…). Encore faut-il y réflêchir avant l'adoption pour ne pas se retrouver sans solution le moment venu.
N'hésitez pas à questionner les membres de votre famille, les amis ou encore les voisins, pour savoir lesquels seraient prêts à garder votre chat pendant vos vacances.
</p>
<p>
<b><u>5- Vais-je opter pour un chaton ou un chat adulte ?</u></b>
Si vous tenez à votre mobilier, que vous avez des bibelots précieux et fragiles, que vous ne supporterez pas une griffure sur votre canapé en cuir tout neuf, il vaudrait mieux opter pour un chat adulte, qui sera moins foufou et moins maladroit qu'un chaton.
Ou oublie souvent qu'un chaton n'est pas de tout repos ! Si vous avez des enfants en bas âge, il est judicieux de ne pas adopter un tout jeune chaton, car ceux-ci sont fragiles, et les enfants, sans le faire exprès, peuvent avoir tendance à les manipuler un peu trop brusquement.
</p>
<p>
<b><u>6- Quel caractère aimerai-je chez mon futur chat et quel caractère serait le plus adapté à mon mode de vie ?</u></b>
Bien plus que sur la couleur ou l'aspect physique, il vous faut réflêchir sur le caractère que vous aimeriez chez votre futur chat, afin qu'il s'accorde le mieux possible avec votre personnalité et votre mode de vie.
Préférez-vous plutôt un chat très câlin voire pot-de-colle ? Si oui, êtes-vous sûr de bien vous rendre compte qu'un chat pot-de-colle sera toujours dans vos jambes, s'installera sur vos genoux dès que vous vous asseyez, s'installera sur votre livre, ou sur votre oreiller pendant que vous dormez.
Ou bien peut-être préférez-vous un chat plus indépendant, qui « vit sa vie » ? Ou encore un chat très joueur pour jouer avec vos enfants ?
</p>
<p>
<b><u>7- Que ferai-je du chat en cas de changements importants dans ma vie ?</u></b>
Que ferai-je du chat en cas de déménagement, en cas de grossesse et de non-immunisation contre la toxoplasmose, en cas d'enfant allergique, en cas de divorce, en cas de chômage et de difficultés à assumer les frais, etc… ?
Autant de questions à se poser avant toute adoption. Les situations citées ci-dessus sont malheureusement des cas fréquents d'abandons pour les chats, alors que des solutions existent et que beaucoup de ces abandons pourraient être évités.
</p>
<p>
8- En cas de décès, qui s'occupera de mon chat ?
C'est une question que l'on ne pense pas forcément à se poser, particulièrement lorsqu'on est jeune et en bonne santé. Mais un accident peut arriver à n'importe qui, et le chat se retrouver subitement sans maître. C'est pourquoi il est bon de réflêchir à la question avant toute adoption, et d'en parler à son entourage proche pour trouver des solutions en cas de malheur.
</p>
<p>
Cette liste n'est pas exhaustive. Il est essentiel que chaque adoptant ait mené une réflexion personnelle avant de signer le contrat d'adoption. <b><u>Une adoption est un engagement à long terme, elle n'est pas à prendre à la légère.</u></b>
</p>

<br>
<h2>Et si j'adoptais un adulte ?</h2>
<br>
<p>
Les <b>chatons</b> sont tellement mignons avec leurs petites bouilles à croquer, qu'il est souvent tentant de vouloir adopter un chaton, et c'est compréhensible.
</p>
<p>
Mais il ne faut pas oublier pour autant les <b>adultes</b>, qui ont, eux aussi, un jour été chatons.
Adopter un chat adulte a ses <b>avantages</b>, tout comme adopter un chaton peut avoir des <b>inconvénients</b> dont on n'est pas toujours conscient quand on n'a pas, ou plus, l'habitude.
</p>
<p>
Si vous recherchez un <b>caractère</b> particulier pour votre futur chat, par exemple un chat très câlin, nous vous conseillons d'opter pour un chat adulte, car vous serez sûr à 100% de son caractère.
A l'inverse, le caractère d'un chaton n'est jamais définitif. Un chaton peut très bien être très câlin étant petit, et devenir indépendant en grandissant... ou vice versa.
A <b>FELIN POSSIBLE</b>, les chats sont en famille d'accueil, et nos familles d'accueil sont donc très attentives à leur caractère et leur personnalité.
Nous saurons donc vous <b>conseiller</b> en fonction du caractère que vous recherchez chez votre futur chat.
</p>
<p>
Adopter un adulte a bien d'autres avantages. Un adulte sera plus <b>calme</b> et fera moins de bêtises qu'un chaton.
Effectivement, on a souvent tendance à l'oublier quand on n'en a pas eu depuis un moment, mais un chaton, c'est foufou, et maladroit ! Un chaton, ça grimpe partout, ça court partout, ça fait des bêtises, et ça casse des bibelots.
Si vous êtes attachés à votre intérieur, à vos meubles et à vos objets, optez de préférence pour un adulte.
</p>
<p>
Il faut aussi oublier certaines <b>idées reçues</b>. Notamment celle qui pense qu'un chat adulte ayant été abandonné, ayant connu l'errance et la faim, voire ayant été maltraité, sera forcément perturbé.
Les chats, comme les chiens d'ailleurs, sont fabuleux, car ils n'éprouvent <b>aucune rancune</b> envers les humains, même lorsqu'ils ont été victimes de leur cruauté.
Les chats abandonnés sont même souvent très câlins, car ils en ont manqué, et ils sont reconnaissants envers leurs nouveaux maîtres de prendre soin d'eux.
Les chats ont une <b>capacité d'adaptation</b> impressionnante, et même adultes, ils se font très bien à une nouvelle vie, si on veut bien leur en donner la chance et leur laisser un petit temps d'adaptation.
</p>
<p>
Les raisons qui reviennent le plus souvent pour vouloir à tout prix un chaton sont de le voir <b>grandir</b> et de <b>l'éduquer</b> soi-même.
Mais il ne faut pas oublier que la phase de croissance du chaton est très courte: elle ne dure que <b>quelques mois</b>.
Le chat deviendra très vite adulte, et il serait dommage de priver un chat d'une famille aimante, juste parce qu'il n'est plus tout petit.
Un jeune adulte sera toujours très vif et joueur, certains adultes peuvent même rester "chaton" dans leur tête pendant plusieurs années. ;)
Quant à <b>l'éducation</b>, c'est le rôle de la maman-chat d'éduquer son chaton, ce n'est pas celui de l'humain.
Bien sûr, il est possible de lui apprendre quelques <b>règles</b>, comme de ne pas grimper sur la table, ou encore de ne pas faire ses griffes sur le canapé, mais ceci est aussi possible avec un adulte, et cela, sans forcément prendre plus de temps qu'avec un chaton (qui du fait de son côté "foufou" sera plus difficile à canaliser).
</p>
<p>
<b>Pour conclure, nous vous conseillons de ne pas fermer votre coeur aux adultes pour la seule raison qu'ils ne sont plus chatons.
Eux aussi méritent une famille aimante, et attentionnée, et ils vous le rendront au centuple: adopter un adulte apporte beaucoup de bonheur.</b>
</p>
</div>