<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal">
<h2>L'arrivée de votre chat</h2>
<br>
<ul>
  <li><a href="#ancreEquipement">L'équipement à prévoir pour l'arrivée de votre chat</a></li>
  <li><a href="#ancreNvChat">Comment procéder pour introduire un nouveau chat</a></li>
  <li><a href="#ancreCohabitation">La cohabitation avec vos chats déjà en place</a></li>
</ul>
<br><br>

<!-- Equipement -->
<br>
<h3><a name="ancreEquipement">L'équipement à prévoir pour l'arrivée de votre chat</a></h3>
<p>
Vous vous apprêtez à accueillir votre chat ? Peut-être est-ce le premier, et vous vous demandez si vous n'avez rien oublié...
</p>
<p>
Voici une liste des choses indispensables (ou non !) à prévoir pour accueillir au mieux votre nouvelle boule de poils.
</p>
<h4>L'indispensable</h4>
<ul>
  <li>2 gamelles : 1 pour les croquettes, 1 pour l'eau. Si vous avez plusieurs chats, il peuvent partager les gamelles.</li>
  <li>1 bac à litière : nous vous conseillons la maison de toilette, plus intime et moins odorante en appartement. Le bac à litière est à placer dans un endroit tranquille, loin des regards et des passages.</li>
  <li>1 griffoir : pour éviter que votre chat ruine votre canapé en cuir ou votre fauteuil en osier. Vous en trouverez dans les animaleries. Une bûche en bois peut aussi très bien faire l'affaire.</li>
  <li>des joujous : inutile de vous ruiner, les chats s'amusent généralement de peu de choses… un bout de ficelle, un bouchon, une plume, une noisette ramassée dans les bois… Si vraiment vous tenez à acheter des jouets dans le commerce, les objets type canne à pêche ou plumeau ont souvent beaucoup de succès.</li>
  <li>1 caisse de transport : soyez vigilants au système de fermeture, certains modèles peuvent s'ouvrir facilement en cas de choc.</li>
</ul>

<h4>Le facultatif</h4>
<ul>
  <li> 1 coussin : vous pouvez investir dans une corbeille ou un coussin, mais ce n'est pas indispensable. Les chats s'adaptent généralement très bien et trouvent eux-mêmes leur(s) coin(s) dodo.</li>
  <li> 1 arbre à chat : si vous êtes en appartement, il permettra à votre chat de s'occuper. Il sera idéalement placé près d'une fenêtre, et d'un radiateur. Si vous êtes en maison et que votre chat peut sortir, l'arbre à chat sera un plus mais pas indispensable.</li>
</ul>

<br>
<!-- Nouveau Chat -->
<h3><a name="ancreNvChat">Comment procéder pour introduire un nouveau chat</a></h3>
<p>
Placez la caisse de transport contenant votre chat dans un endroit calme. Eloignez si possible les enfants, et les autres animaux de la famille. Ne le forcez pas à sortir, laissez-le venir à vous, à son rythme. S'il est un peu timide, laissez-le dans sa caisse de transport ouverte, et retirez-vous de la pièce, dans laquelle vous aurez préalablement placé gamelles et litière. Il sortira de lui-même quand il le sentira.
</p>
<p>
Chaque chat a son caractère, son vécu, et la période d'adaptation peut être très rapide (quelques jours), comme très longue (plusieurs mois, voire plus). A vous d'être patient et de respecter son rythme.
</p>
<p>
Si vous avez un autre chat, ou un autre animal, il est conseillé de mettre votre chat en quarantaine pendant quelques jours. Ceci afin d'éviter la propagation de maladies ou de parasites éventuels, mais aussi d'offrir une certaine tranquillité à votre nouveau chat. Cela lui permettra d'explorer tranquillement la première pièce de votre habitation, sans avoir à gérer un « ennemi » un peu trop présent.
</p>

<br>
<!-- Cohabitation -->
<h3><a name="ancreCohabitation">La cohabitation avec vos chats déjà en place</a></h3>
<p>
Si vous avez déjà un ou plusieurs autres chats, il se peut que la cohabitation soit quelque peu houleuse dans un premier temps.
</p>
<p>
La cohabitation se fait plus ou moins vite selon les chats, en fonction de leur âge, mais aussi de leur caractère, de leur passé, etc. Un chat ayant vécu 10 ans en chat unique et chouchouté de la famille aura souvent plus de mal à accepter un nouvel arrivant qu'un chat déjà habitué à vivre en communauté.
</p>
<p>
C'est assez rare qu'un chat n'accepte pas un congénère, mais cela peut parfois prendre plusieurs mois, voire plusieurs années pour que la cohabitation se fasse entre 2 chats.
</p>
<p>
De plus, qui dit cohabitation ne dit pas forcément grand amour. Parfois les chats se prennent d'affection, dorment ensemble, se font la toilette mutuelle. Mais ce n'est pas le cas entre tous les chats. Ce n'est pas parce que l'on a 2 chats que l'on assistera forcément à des marques d'affection mutuelles.
</p>
</div>