<div class="centre_principal">
  <h2>Devenir Bénévole</h2>
  <p>
    Notre association a toujours besoin de <b>bénévoles</b>. En effet, nous sommes peu nombreux et ne pouvons être partout à la fois ! C'est pourquoi les bénévoles sont essentiels et jouent un rôle très important.
  </p>
  <p>
    Toute personne souhaitant nous aider peut devenir bénévole. Il n'y a aucun temps de présence imposé: chacun aide selon sa disponibilité, et sa volonté. L'aide des bénévoles peut très bien être occasionnelle et ponctuelle, comme elle peut être plus régulière.
  </p>
  <p>
    Les tâches effectuées par les bénévoles sont multiples et peuvent faire appel à des talents divers et variés. En voici quelques exemples:
  </p>
  <ul>
    <li><i class="icon-hand-right"></i> collage d'affiches</li>
    <li><i class="icon-hand-right"></i> distribution de tracts</li>
    <li><i class="icon-hand-right"></i> confection d'objets pour la boutique de l'association</li>
    <li><i class="icon-hand-right"></i> tenue de stands lors de manifestations</li>
    <li><i class="icon-hand-right"></i> réalisation d'affiches ou de documents d'information</li>
    <li><i class="icon-hand-right"></i> transport d'un chat chez le vétérinaire</li>
    <li><i class="icon-hand-right"></i> et bien d'autres choses... nous avons quelques projets pour la suite de l'association pour lesquels nous cherchons des graphistes, des illustrateurs, des personnes ayant une bonne plume,
     des connaissances précises sur les chats : nous vous en reparlerons le moment venu, mais si vous avez ces talents, vous pouvez déjà nous contacter.
   </ul> 
   <p>
    Cette liste est loin d'être exhaustive, nous sommes ouverts à toutes les propositions d'aide. :)
  </p>
  <p>
    Si vous souhaitez nous aider, n'hésitez pas à nous en parler, pour nous contacter:
  </p>
  <ul>
    <li><i class="icon-user"></i> par téléphone au <b>06 28 19 73 84</b>, </li>
    <li><i class="icon-envelope"></i> par email à l'adresse <a href="mailto:asso@felinpossible.fr">asso@felinpossible.fr</a></li>
    <li><i class="icon-comment"></i> sur notre <a href="forum/index.php"> forum de discussion </a></li>
  </ul>

  <p>
    Toute l'équipe de <b>FELIN POSSIBLE</b> vous remercie pour l'intérêt que vous manifestez pour notre association et l'aide que vous voudrez bien nous apporter.
  </p>
</div>
