<div class="centre_principal">
	<h2>Prise en charge</h2>
	<p>
		Vous êtes de plus en plus nombreux à nous contacter pour prendre en charge des chats, qu'il s'agisse de chats trouvés, de chatons nés à la rue, d'abandons de particuliers. 
	</p>
	<p>
		Un petit point sur notre fonctionnement à ce niveau, en fonction des 2 principaux cas rencontrés (ce qui nous évitera d'avoir à répéter sans arrêt la même chose   et donc de gagner du temps) :
	</p>
	<ul>
		<li><i class="icon-hand-right"></i> <a href="#ancreRecueil" rel="ancre">Vous avez recueilli un chat perdu/abandonné/errant</a></li>
		<li><i class="icon-hand-right"></i> <a href="#ancreParticulier" rel="ancre">Vous êtes un particulier et souhaitez abandonner votre chat</a></li>
		<li><i class="icon-hand-right"></i> <a href="#ancreQueFaire" rel="ancre">Que faire si je souhaite qu'un chat soit pris en charge par l'association ?</a></li>
	</ul>
	
	<h3><a id="ancreRecueil"></a>Vous avez recueilli un chat perdu/abandonné/errant</h3>
	<p>
		Il vous faut avant toute chose, faire des <b>recherches <u>APPROFONDIES</u></b> au cas où le chat soit seulement perdu et recherché par ses maîtres. 
		J'insiste sur le mot "approfondi". Il ne s'agit pas simplement de demander à 2/3 voisins s'ils connaissent le chat. 
		"Approfondi", cela signifie mettre <b><u>TOUT</u></b> en oeuvre pour rechercher d'éventuels propriétaires. 
		<p>
			Cela commence par la <b>vérification de l'identification</b>. Un chat peut être identifié par <u>tatouage</u> (visible dans l'oreille), ou par <u>puce électronique</u>. 
			Cette dernière est invisible à l'oeil nu, puisqu'il s'agit d'une micro-puce de la taille d'un grain de riz implantée sous la peau. Elle se vérifie chez le vétérinaire au moyen d'un lecteur de puce, c'est un acte gratuit qui prend 30 secondes et ne nécessite pas de prendre rendez-vous : il vous suffit de vous présenter à l'accueil avec le chat. 
			Si vous n'avez pas de caisse de transport, généralement les vétérinaires peuvent en prêter une, ou nous pouvons également le faire. 
			A noter que le tatouage est (malheureusement) voué à disparaître, donc de plus en plus de chats sont identifiés par puce. 
			Si le chat est identifié, le vétérinaire pourra obtenir auprès du fichier national félin les coordonnées de ses maîtres et les contacter. 
		</p>
		<p>
			Ensuite si le chat n'est pas identifié, il vous faut faire une <b>enquête <u>minutieuse</u></b> dans votre quartier, et les quartiers alentours (un chat non-stérilisé et/ou affamé peut parcourir plusieurs kilomètres). 
			Cela implique de : 
			<dl>
				<dt>Questionner les habitants du quartier</dt>
				<dd>Savent-ils à qui appartient le chat ? d'où il vient ? l'ont-il déjà vu dans le quartier ? depuis combien de temps ? etc.
					Il faut les questionner en nombre, pas seulement 2/3 personnes.
				</dd>
				<dt>Mettre des affiches (en nombre)</dt>
				<dd>Dans les commerces, chez les vétérinaires, bref dans tous les lieux de passage, signalant le chat comme étant trouvé.
				</dd>
			</dl>
		</p>
		<p>
			Il vous faut également <b>signaler le chat</b> aux refuges et associations de la région, à la mairie, à la gendarmerie, aux vétérinaires, à la fourrière : tous les endroits où sont susceptibles d'aller des maîtres ayant perdu leur chat. 
		</p>
		<p>
			Il vous faudra également <b>passer des annonces sur Internet</b>, notamment sur le site <a href="http://www.chat-perdu.org/"><i class=" icon-globe"></i> http://www.chat-perdu.org</a> mais aussi sur les sites de petites annonces (le bon coin, vivastreet, etc).
			Ainsi que sur <b>Ouest France</b> pour les personnes qui n'ont pas internet (personnes âgées notamment).
		</p>
		<p>
			<b>Toutes ces démarches vous incombent, vous qui avez pris la responsabilité de recueillir ce chat. Nous ne sommes pas là pour les faire à votre place.</b>
		</p>
		<p>
			Et s'il s'avère après ces recherches, mais <b class="text-error">uniquement après que toutes les recherches citées ci-dessus aient été faites</b>, personne ne le réclame, nous verrons si nous pouvons le prendre en charge. 
			Sachant que, les demandes de prise en charge étant de plus en plus nombreuses, et nos places limitées, nous sommes en permanence complets, pour ne pas dire saturés. Donc le chat trouvé sera placé sur liste d'attente, le temps qu'une place se libère. L'attente peut être longue (plusieurs semaines, voire plusieurs mois...) donc il faudra que vous gardiez le chat chez vous en attendant. 
			Vous pouvez aussi, pour gagner du temps et pour une prise en charge plus rapide, vous proposer d'être sa famille d'accueil. Pour ce faire, il vous faudra remplir le formulaire de famille d'accueil sur notre site : <a href="http://www.felinpossible.fr/#/fa"><i class=" icon-file"></i> cliquez-ici</a>. L'un de nos chargés des familles d'accueil vous contactera alors pour vous expliquer les modalités et voir si votre environnement se prête à nos critères concernant les FA.
		</p>
		<p>
			<b><u>Si vous savez pertinemment que vous ne pourrez pas le garder chez vous, ne le recueillez pas !</u></b> 
			Beaucoup de gens nous appellent pour nous dire qu'ils ont recueilli un chat mais qu'ils ne peuvent (ou veulent...) pas le garder, même temporairement... et préfèrent nous harceler (le mot n'est pas trop fort malheureusement) pour que nous le prenions en charge rapidement. Ceci n'est pas acceptable. C'est <u><b>à chacun d'assumer ses sauvetages</b></u>, pas seulement à nous.
			Nous voulons bien aider, mais il faut que chacun y mette du sien, et n'attende pas tout de notre association, qui a ses limites, à commencer par des limites de place, mais aussi de temps libre (je rappelle que nous sommes tous bénévoles, avons pour la plupart des emplois ou des études à côté, et accessoirement une vie de famille également). <b>Nous attendons donc de la part de toute personne nous contactant, un engagement personnel et une implication forte.</b> 
		</p>
		<p>
			<u>Un petit mot pour le cas particulier des chats errants sauvages</u> : le but premier de l'association est l'adoption de chats. Les chats sauvages ne sont pas adoptables, par conséquent nous ne pouvons pas les accueillir. La solution dans ce cas, est de les faire stériliser et tatouer en tant que chats dits "libres" et de les relâcher sur place une fois cela fait. Pour cela, il existe des associations spécialisées dans les chats libres, dont nous pourrons vos donner les coordonnées.
		</p>
		<h3><a id="ancreParticulier"></a>Vous êtes un particulier et souhaitez abandonner votre chat</h3>
		<p>
			Nous avons souvent de la part de particuliers la réflexion suivante : 
			<blockquote><em>non non, je ne veux pas l'abandonner, juste vous le confier</em></blockquote>
			Nous confier votre chat, c'est l'abandonner. 
		</p>
		<p>
			<b>L'association n'a pas vocation à accueillir les chats de particuliers.</b> 
			Lorsque vous avez adopté ce chat, vous vous êtes <b><u>engagé</u></b> à vous en occuper tout au long de sa vie. Pour rappel, un chat vit en moyenne 15 ans, et les plus chanceux peuvent même dépasser les 20 ans. Il faut y penser AVANT de prendre un chat. 
			Certes on ne peut pas savoir ce que la vie nous réserve dans les 20 prochaines années. Mais un engagement est un engagement. Vous n'allez pas abandonner votre enfant au moindre souci, alors pourquoi serait-ce plus acceptable pour un chat ? Ca ne l'est pas. Le chat n'est pas non plus un objet de consommation, que l'on prend et que l'on jette lorsque bon nous semble. <b>C'est un être vivant et sensible, et un membre à part entière de la famille.</b> 
		</p>
		<p>
			Par contre, nous sommes toujours disponibles pour vous donner des <b>conseils</b> pour trouver des <b>solutions autres que l'abandon</b>, à condition que vous vouliez bien les entendre. 
			La plupart des personnes qui nous appellent arrivent résignées, décidées à se débarrasser de leur chat au plus vite, et n'écoutent absolument pas les solutions autres que nous proposons. 
			Et pourtant <b>bien des abandons pourraient être évités</b> si ces personnes étaient correctement informées, et surtout si elle voulaient bien faire un minimum d'efforts plutôt que de chercher toujours la facilité. Un chat, on le prend avec ses qualités et ses défauts, il faut le savoir. Le chat parfait n'existe pas, mais bien des problèmes de comportement chez le chat sont d'abord dû au comportement de leurs humains. Donc en modifiant nos comportements, cela suffit très souvent à résoudre le souci. 
		</p>
		<p>
			Nous acceptons de prendre en charge des chats de particuliers à certaines conditions :
			<ul>
				<li><i class="icon-ok"></i> que vous vous engagiez à garder votre chat chez vous jusqu'à son adoption (et ce quel que soit le temps que ça prend, les adoptions de chats adultes pouvant prendre plusieurs mois, voire plusieurs années).</li>
				<li><i class="icon-ok"></i> que vous mettiez votre chat "en règle", à vos frais : cela implique qu'il soit testé FIV/FELV, vacciné, identifié et stérilisé</li>
				<li><i class="icon-ok"></i> que vous ayiez TOUT tenté auparavant pour trouver des solutions autres (et par conséquent écouté nos conseils)</li>
			</ul>
		</p>
		<p>
			Pour le cas exceptionnel où un chat de particulier se retrouverait dans l'une de nos familles d'accueil, nous vous demanderons un <b>parrainage</b> (15 euros par mois) jusqu'à l'adoption du chat (quel que soit le délai que ça prendra), pour nous permettre de payer les frais d'entretien courant (croquettes, litière, anti-parasitaires etc). Mais ceci reste exceptionnel, nos places au sein de nos familles d'accueil sont réservés aux chats sans maître, n'ayant personne pour s'occuper d'eux.
		</p>
		<p>
			Pour résumer, qu'il s'agisse de chats trouvés errants, ou de votre propre chat, nous vous demanderons un <b>maximum d'implication et d'efforts.</b> 
			Si vous n'êtes pas prêts à faire ces efforts, il est inutile de nous contacter. 
		</p>
		<h3><a id="ancreQueFaire"></a>Que faire si je souhaite qu'un chat soit pris en charge par l'association ?</h3>
		<p>
			Dans un premier temps, nous contacter par email (<i class=" icon-envelope"></i> <?php echo $this->render('index/mailto.phtml'); ?>)
		</p>
		<p>
			Dans ce mail, il nous faudra le maximum d'informations, notamment :
			<h4>S'il s'agit d'un chat trouvé</h4>
			<ul>
				<li><i class="icon-hand-right"></i> où l'avez-vous trouvé ?</li>
				<li><i class="icon-hand-right"></i> à quelle date ?</li>
				<li><i class="icon-hand-right"></i> avez-vous vérifié s'il était porteur d'un tatouage ou d'une puce électronique ?</li>
				<li><i class="icon-hand-right"></i> quelles autres recherches avez-vous effectuées jusqu'à présent pour retrouver d'éventuels maîtres ?</li>
				<li><i class="icon-hand-right"></i> quel est son âge estimé (vous pouvez demander au vétérinaire lors de la vérification de la puce électronique) ?</li>
				<li><i class="icon-hand-right"></i> de quel sexe est-il ?</li>
				<li><i class="icon-hand-right"></i> quel est son état de santé apparent ?</li> 
				<li><i class="icon-hand-right"></i> quel est son caractère ?</li> 
				<li><i class="icon-hand-right"></i> est-il sociable ou sauvage/craintif ?</li>
				<li><i class="icon-hand-right"></i> quel est son comportement avec les chats, les chiens, et les enfants ? (si vous le connaissez)</li>
				<li><i class="icon-hand-right"></i> etc</li>
			</ul>
			<h4>S'il s'agit de votre chat</h4>
			<ul>
				<li><i class="icon-hand-right"></i> quel est son nom ?</li>
				<li><i class="icon-hand-right"></i> de quel sexe est-il ?</li>
				<li><i class="icon-hand-right"></i> quel âge a-t-il ? (date de naissance exacte si vous l'avez ou âge approximatif)</li>
				<li><i class="icon-hand-right"></i> quelle est son histoire ? (depuis combien de temps l'avez-vous ? a-t-il été adopté adulte ou chaton ? chez un particulier ? dans un élevage ? une animalerie ? un refuge ou une association ? etc)</li>
				<li><i class="icon-hand-right"></i> quelle est la raison de l'abandon (<u>soyez sincères</u> s'il vous plait : il ne sert à rien de nous mentir, on arrive toujours à le savoir)</li>
				<li><i class="icon-hand-right"></i> quelles sont les solutions autres que vous avez tentées ?</li>
				<li><i class="icon-hand-right"></i> est-il testé FIV/FELV ? (dépistage des maladies sida du chat et leucose) Si oui à quelle date ont été faits les tests et est-il sorti, ou a-t-il été en contact avec d'autres chats depuis ?</li>
				<li><i class="icon-hand-right"></i> est-il vacciné ? si oui pour quelles maladies (typhus, coryza, leucose, rage) et quelle est la date du dernier rappel de vaccins ?</li> 
				<li><i class="icon-hand-right"></i> est-il stérilisé ?</li>
				<li><i class="icon-hand-right"></i> est-il identifié ? Si oui, nous fournir le numéro de tatouage ou puce électronique. L'identification est obligatoire avant toute cession.</li>
				<li><i class="icon-hand-right"></i> si rien de tout ça (tests, vaccins, stérilisation, identification), êtes-vous prêt à le faire à vos frais pour lui donner le maximum de chances d'être adopté ?</li> 
				<li><i class="icon-hand-right"></i> êtes-vous prêt à vous <u>engager</u> à le garder chez vous jusqu'à ce qu'il trouve une famille adoptive ? (j'insiste sur la notion d'engagement encore une fois : il ne s'agit pas de nous dire "oui oui" et de changer d'avis 3 semaines plus tard)</li>
				<li><i class="icon-hand-right"></i> quel est son caractère ?</li> 
				<li><i class="icon-hand-right"></i> quel est son comportement avec les chats et les chiens (si vous le connaissez) ?</li>
				<li><i class="icon-hand-right"></i> peut-il vivre en appartement, ou a-t-il impérativement besoin de sortir ?</li>
				<li><i class="icon-hand-right"></i> est-il adapté dans une famille avec enfants ou pas ?</li> 
				<li><i class="icon-hand-right"></i> est-il propre ? a-t-il l'habitude d'utiliser un bac à litière ?</li>
				<li><i class="icon-hand-right"></i> a-t-il des besoins autres particuliers ?</li>
				<li><i class="icon-hand-right"></i> quel est son état de santé ? a-t-il eu des maladies ou des blessures dans le passé ? à quand remonte son dernier examen de routine chez le vétérinaire ?</li> 
				<li><i class="icon-hand-right"></i> le type de famille qui lui conviendrait le mieux</li>
				<li><i class="icon-hand-right"></i> etc</li>
			</ul>
		</p>
		<p>
			<b>Dans les deux cas</b>, il nous faudra :
			<ul>
				<li><i class="icon-hand-right"></i> des photos du chat, de bonne qualité si possible, et réduites à la taille 640x480 pour ne pas saturer notre messagerie</li>
				<li><i class="icon-hand-right"></i> et vos coordonnées complètes (nom prénom - adresse postale - téléphone fixe + portable - adresse mail</li>
			</ul>
		</p>
		<p>
			En cas de prise en charge par notre association, nous vous demanderons de remplir un document de <b>déclaration de cession</b> (pour la télécharger, <a href="http://www.felinpossible.fr/site/public/documents/FP_DECLARATION_CESSION_2019.pdf"><i class=" icon-file"></i> cliquez-ici</a>). 
			C'est un document qui indique que vous nous confiez le chat, dans le but de le faire adopter.
			Aucun chat ne sera accepté sans ce document, qu'il s'agisse de chat trouvé ou d'abandon de particulier. 
			Ce document nous permet de garder une trace de la provenance du chat, il est donc primordial. 
		</p>
		<p>
			Bien entendu, toute <b>aide financière</b> est la bienvenue pour toute prise en charge.
			Nous ne l'imposons pas pour le cas des chats trouvés, mais il faut savoir que les chats accueillis, qu'ils soient trouvés ou pas, nous coûtent très cher (alimentation, traitements anti-parasitaires, frais vétérinaires, etc).
		</p>
		<p>
			J'insiste également sur la notion de <b>courtoisie</b>, qui fait parfois défaut à certains. 
			Je rappelle que nous sommes bénévoles, que nous nous occupons de l'association uniquement sur notre temps libre, quand nos activités professionnelles et nos vies de famille nous le permettent. 
			Sachez que <b><u>nous n'avons aucune obligation de prise en charge.</u></b>
			Nous aidons volontiers et de bon coeur toute personne nous le demandant gentiment et respectueusement, dans la mesure de nos possibilités bien entendu. 
			Par contre, si vous arrivez en étant impoli, agressif, ou menaçant, vous serez immédiatement reconduit vers la sortie. Nous sommes bénévoles, mais pas esclaves. 
		</p>
		<p>
			Nous vous remercions pour votre compréhension et restons à votre disposition pour toute question supplémentaire, par email (<a href="mailto:asso@felinpossible.fr"><i class=" icon-envelope"></i> asso@felinpossible.fr</a>).
			<b>Nous préférons être contactés par email</b>, plutôt que par téléphone, dans la mesure du possible.
		</p>
		<p>
			<u>Pourquoi ?</u>
			<ul>
				<li><i class="icon-hand-right"></i> car nous sommes plusieurs à avoir accès à la boîte mail alors que je suis seule à gérer le standard téléphonique</li>
				<li><i class="icon-hand-right"></i> car nous ne nous occupons pas de l'association à tout moment de la journée, vous avez donc de grandes chances de tomber sur le répondeur si vous nous contactez par téléphone</li>
				<li><i class="icon-hand-right"></i> car les mails nous permettent de garder une trace écrite des échanges et d'oublier de noter certaines informations</li>
				<li>car nous n'avons pas toujours la possibilité de prendre des notes là où nous sommes lorsque nous recevons des appels</li>
				<li><i class="icon-hand-right"></i> car les mails nous permettent de vous répondre tardivement le soir (heures où nous nous occupons de l'association), alors que nous cessons les appels téléphoniques à 21h</li>
			</ul>
		</p>
		<p>
			<u>En conclusion</u> : la réponse n'en sera que plus rapide si vous nous contactez par mail et si vous nous mettez le maximum d'informations dès votre premier mail.
			Pour le cas où vous ne pourriez pas nous contacter par mail, et où vous le feriez malgré tout par téléphone, il vous suffit de laisser un message sur la boîte vocale et nous vous rappellerons dès que nos emplois du temps surchargés nous le permettront. Il est inutile d'appeler 15 fois toutes les 10 minutes (surtout sans laisser de message) : si nous ne répondons pas, c'est que nous sommes occupés.
		</p>
	</div>
