<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal">
  <div class="adresse">
  <b>Comment nous Contacter?</b><br><br>
  Association FELIN POSSIBLE<br>
  Chez Mlle Caroline CANTIN<br>
  La Ville es Ray<br>
  35190 QUEBRIAC<br>
  Tel: <b>06 28 19 73 84</b> <i>(boîte vocale: laissez un message précisant l'objet de votre appel et vos coordonnées, et nous vous recontacterons dès que possible)</i><br>
  Email: <a href="mailto:asso@felinpossible.fr">asso@felinpossible.fr</a><br>
  Site: <a href="http://www.felinpossible.fr">www.felinpossible.fr</a><br>
  Forum: <a href="http://www.felinpossible.fr/forum">www.felinpossible.fr/forum</a><br>
  </div>
</div>