<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal">
	<h2>Les dangers</h2>
	<p>
		Qu'ils soient chats des villes ou chats des prés, les dangers qui entourent nos boules de poils sont multiples et présents partout, aussi bien à l'extérieur qu'à l'intérieur. Il vous faudra donc être particulièrement vigilant, afin de limiter le plus possible de risques.
	</p>
	<h3>A l'intérieur</h3>
	<p>
		Les plantes toxiques (et produits de traitement, engrais etc), les produits ménagers, les aliments toxiques (notamment le chocolat), les fenêtres oscillo-battantes, les fenêtres et balcons non-sécurisés, les objets coupants ou pointus, les ficelles qui traînent, les poubelles et ce qu'elles peuvent contenir (os de poulet pointus), les WC aux couvercles non-baissés, etc.
	</p>
	<h3>A l'extérieur</h3>
	<p>
		Les voitures, les chasseurs, les prédateurs, les chiens, les voisins qui utilisent, volontairement ou non, des produits toxiques (mort aux rats, désherbant...), les voleurs de chats, les insectes (chenilles processionnaires, guêpes, frelons), etc.
	</p>
	<p>
		Cette liste est loin d'être exhaustive et nous vous encourageons fortement à vous renseigner au maximum, auprès de nous, de votre vétérinaire, ou sur internet, sur tous les dangers qui entourent votre chat. Mieux vaut prévenir que guérir.
	</p>
	<p>
		Retrouvez plus d'informations sur notre forum : <a href='http://felinpossible.fr/forum/viewforum.php?f=17'>cliquez-ici <i class="icon-comment"></i></a>.
	</p>
</div>