<div class="centre_principal">

	<div class="row-fluid">
		<p>Vos dons sont essentiels au bon fonctionnement de l'asso, sans eux nous ne pourrions venir en aide à tous ces chats : les soins, les opérations, la nourriture, l'entretien, même les plus petits dons nous sont d'une précieuse aide. 
		</p>
		<p>L'association Félin Possible étant reconnue d'intérêt général, 66% de votre don (hors adhésion) sera déduit de votre impôt.
			Pour bénéficier de la réduction de 66%, vous recevrez un reçu fiscal à domicile.
		</p>
		<p>
			Merci à vous ! 
		</p>
	</div>

  	<div class="row-fluid">
  		<div class="span2"/>
  		<div class="span7">
	  		<img src="http://img4.hostingpics.net/pics/206583visueldonrduction2.jpg"/>
	  	</div>
	</div>
	<?php echo $this->partial("index/reference.phtml"); ?>
  	
</div>