<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal well">
<br>
<p><b> Ami félinophile, soyez le bienvenu sur le site de l'association FELIN POSSIBLE ! </b>
</p>
<br>
<p>Ce site vous permettra de découvrir notre association à travers ses actions, et de voir les chats à adopter. Vous y trouverez également de nombreux conseils pour vous occuper au mieux de votre chat. Vous pourrez, si vous le souhaitez, nous aider en faisant un don en ligne directement sur le site, ou postuler pour devenir famille d'accueil pour l'association.
</p>
<br> 
<p> Nous vous invitons aussi à découvrir les différents objets à vendre au profit de l'association dans notre boutique.
</p>
<br>
<p> N'hésitez pas à vous inscrire sur notre forum de discussion pour poser vos questions, ou tout simplement participer à la vie de l'association.
</p>
<br>
  <ul>
    <li id="signature">L'équipe FELIN POSSIBLE</li>
  </ul>
</div> 