<?php include_once("../../spongestats/stats.php"); ?>

<div class="centre_principal">



    <ul class="thumbnails">
        <li><a href="http://chatslibreslorient.com"><img src="http://imageshack.us/a/img824/4792/nouveau20bandeau20site.jpg" title="Chats libres de lorient"/></a></li>
        <li><a href="http://www.ecole-du-chat-bordeaux.com/"><img src="http://img24.imageshack.us/img24/8300/logoecb.gif"/></a></li>
        <li><a href="http://nineland.free.fr/"><img src="http://img24.imageshack.us/img24/333/nineland.jpg" title="Design du site"/></a></li>
        <li><a href="http://www.chat-perdu.org/"><img src="http://img24.imageshack.us/img24/5702/logochatperduorg.gif"/></a></li>
        <li><a href="http://www.partez-tranquille.com/"/><img src="http://img845.imageshack.us/img845/3473/parteztranquillelogobov.jpg" title="Société de services animaliers. 10% de réduction avec la carte Félin Possible"/></a></li>
        <li><a href="http://www.chatman.fr/"/><img src="http://img412.imageshack.us/img412/2033/logochatman.jpg" title="Comportementaliste spécialisée dans les relations Chats-Hommes, qui officie en Ille-et-Vilaine (35) et dans les départements limitrophes"/></a></li>
        <li><a href="http://assistance-feline.bb-fr.com/"><img src="http://img13.imageshack.us/img13/9609/soleilpanorama13wu.jpg" title="Forum de discussion et d'adoption pour les chats positifs (FIV/FELV)"/></a></li>
        <li><a href="http://www.secondechance.org/"><img src="http://img24.imageshack.us/img24/182/secondechance.jpg"/></a></li>
        <li><a href="http://rescue-bretagne.xooit.fr/portal.php"><img src="http://img17.imageshack.us/img17/5250/rescuebretagne530d1c.jpg"/></a></li>
        <li><a href="http://www.rescue-forum.com"><img src="http://img26.imageshack.us/img26/2334/rescue11.gif"/></a></li>
        <li><a href="http://www.chatmania.fr/forum-chats/index.php"><img src="http://www.chatmania.fr/100x55bleu.gif"/></a></li>
        <li><a href="http://www.educationduchiendecompagnie.fr/welcome/index.php"><img src="http://www.educationduchiendecompagnie.fr/bannieres/banniere_edcdc_003.png"/></a></li>
        <li><a href="http://www.boulesdefourrure.fr/"><img src="http://img194.imageshack.us/img194/563/cello.jpg" title="Boules de Fourrure (blog vétérinaire)"/></a></li>
        <li><a href="http://maliki.com"/><img src="http://www.maliki.com/bonus/minibanniere_maliki_site.jpg" title="Maliki, webcomic"/></a></li>
        <li><a href="http://charlie-asv.over-blog.com/"/><img src="http://img29.imageshack.us/img29/9024/tccollage3.jpg" title="L'asv de Charlie"/></a></li>
        <li><a href="http://snow-veto.over-blog.com/"/><img src="http://img27.imageshack.us/img27/5512/headerarticletmpphpvlve.jpg" title="Blog : Snow veto"/></a></li>
        <li><a href="http://www.chezleveto.com/blog/"/><img src="http://img707.imageshack.us/img707/3386/top1bg.jpg" title="Blog : chez le véto"/></a></li>
        <li><a href="http://www.comportementalisteschienschats.fr/services/chat.htm"/><img src="http://img525.imageshack.us/img525/1518/cartecynthiagauthier.jpg" title="Cynthia GAUTHIER, comportementaliste CHATS"/></a></li>
        <li><a href="http://www.simplydigishop.com/zen-cart/"/><img src="http://img196.imageshack.us/img196/3032/simplydigishop.gif" title="SIMPLY DIGI SHOP, boutique de DIGISCRAP"/></a></li>
        <li><a href="http://www.veterinaire.fr/"/><img src="http://img33.imageshack.us/img33/9527/accueil200807151.jpg" title="Le Portail de l'Ordre des Vétérinaires"/></a></li>
        <li><a href="http://www.animaux-nature.info/"/><img src="http://www.animaux-nature.info/IMG/gif/idae.gif" title="IDAE: Information pour la Défense des Animaux et de l'Environnement"/></a></li>
        <li><a href="http://animalice.e-monsite.com/"/><img src="http://img23.imageshack.us/img23/9638/animalice.jpg" title="AniMalice, société de services animaliers (chiens, chats, furets, lapins, rongeurs, oiseaux...) sur le secteur de DOL DE BRETAGNE"/></a></li>
        <li><a href="http://www.catsweethome.fr/"/><img src="http://img3.imageshack.us/img3/1539/401439logocsh.jpg" title="Garde d'animaux sur la région rennaise"/></a></li>
        <li><a href="http://chatssanstoi22.blogspot.com/"/><img src="http://img228.imageshack.us/img228/733/466461chatssanstoi.jpg" title="Association pour les chats libres à Saint-Brieuc (22)"/></a></li>
        <li><a href="http://www.letardis.eu/"/><img src="http://img41.imageshack.us/img41/4872/16159010000185421029381.jpg" title="Letardis Webradio"/></a></li>
        <li><a href="http://www.catstore.fr"><img src="/site/public/css/image/catstore.jpg" alt="Catstore - La déco 100% chat"/></a></li>
    </ul>
    <p>
        Plus de détails sur notre forum, à cette adresse : <a href="http://felinpossible.fr/forum/viewforum.php?f=95">cliquez-ici <i class="icon-comment"></i></a>
    </p>
    <p>Ce site est listé dans la catégorie <a href="http://www.webrankinfo.com/annuaire/cat-310-animaux.htm">Animaux</a> : <a href="http://www.webrankinfo.com/annuaire/cat-5184-adoption-d-animaux.htm">Adoption d'animaux</a> de l'annuaire <a href="http://formation.webrankexpert.com/"><img src="http://www.webrankinfo.com/images/wri/webrankinfo-80-15.png" title="WebRankInfo" width="80" height="15" alt="Cours de referencement Olivier Duffez" /></a>
    </p>
</div>