<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal">

 <ul>
    <li><a href="http://pagesperso-orange.fr/chatslibres/cariboost1/crbst_0.html">Les Chats Libres de Lorient</a></li>
    <li><a href="http://www.ecole-du-chat-bordeaux.com/"><img src="http://img24.imageshack.us/img24/8300/logoecb.gif"/></a></li>
    <li><a href="http://nineland.free.fr/"><img src="http://img24.imageshack.us/img24/333/nineland.jpg" title="Design du site"/></a></li>
    <li><a href="http://www.chat-perdu.org/"><img src="http://img24.imageshack.us/img24/5702/logochatperduorg.gif"/></a></li>
    <li><a href="http://assistance-feline.bb-fr.com/"><img src="http://img13.imageshack.us/img13/9609/soleilpanorama13wu.jpg" title="Forum de discussion et d'adoption pour les chats positifs (FIV/FELV)"/></a></li>
    <li><a href="http://www.secondechance.org/"><img src="http://img24.imageshack.us/img24/182/secondechance.jpg"/></a></li>
    <li><a href="http://chatpapotebreizh.superforum.fr/index.htm"><img src="http://img17.imageshack.us/img17/1027/chatp12.jpg"/></a></li>
    <li><a href="http://rescue-bretagne.xooit.fr/portal.php"><img src="http://img17.imageshack.us/img17/5250/rescuebretagne530d1c.jpg"/></a></li>
    <li><a href="http://rescue.forumactif.com/"><img src="http://img26.imageshack.us/img26/2334/rescue11.gif"/></a></li>
    <li><a href="http://www.chatmania.fr/forum-chats/index.php"><img src="http://www.chatmania.fr/100x55bleu.gif"/></a></li>
    <li><a href="http://www.educationduchiendecompagnie.fr/welcome/index.php"><img src="http://www.educationduchiendecompagnie.fr/bannieres/banniere_edcdc_003.png"/></a></li>
    <li><a href="http://www.boulesdefourrure.fr/"><img src="http://img194.imageshack.us/img194/563/cello.jpg" title="Boules de Fourrure (blog vétérinaire)"/></a></li>
    <li><a href="http://maliki.com"/><img src="http://www.maliki.com/bonus/minibanniere_maliki_site.jpg" title="Maliki, webcomic"/></a></li>
    <li><a href="http://charlie-asv.over-blog.com/"/><img src="http://img29.imageshack.us/img29/9024/tccollage3.jpg" title="L'asv de Charlie"/></a></li>
    <li><a href="http://snow-veto.over-blog.com/"/><img src="http://img27.imageshack.us/img27/5512/headerarticletmpphpvlve.jpg" title="Blog : Snow veto"/></a></li>
    <li><a href="http://www.chezleveto.com/blog/"/>Blog : chez le véto</a></li>
    <li><a href="http://www.comportementalisteschienschats.fr/services/chat.htm"/><img src="http://img525.imageshack.us/img525/1518/cartecynthiagauthier.jpg" title="Cynthia GAUTHIER, comportementaliste CHATS"/></a></li>
    <li><a href="http://www.simplydigishop.com/zen-cart/"/><img src="http://img196.imageshack.us/img196/3032/simplydigishop.gif" title="SIMPLY DIGI SHOP, boutique de DIGISCRAP"/></a></li>
    <li><a href="http://www.veterinaire.fr/"/><img src="http://img33.imageshack.us/img33/9527/accueil200807151.jpg" title="Le Portail de l'Ordre des Vétérinaires"/></a></li>
  </ul>
  Plus de détails sur notre forum, à cette adresse : <a href="http://felinpossible.fr/forum/viewforum.php?f=95">cliquez-ici</a>
</div>