<div class="centre_principal">
	<ul class="thumbnails"">	
	
		<li><a href="https://fr-fr.facebook.com/kikazhrennes"><img width="300px" src="/forum/images/kikaz.jpg" title="Kikazh, le chat, le chien... et vous !"/></a></li>
		<li><a href="http://www.crad-rennes.com/"><img width="300px" src="/forum/images/CRAD.jpg" title="Comité Rennais pour l'Animal en Danger"/></a></li>
		<br>
		<li><a href="http://lesvacancesdepandore.com/"><img width="300px" src="/forum/images/vacpand.png" title="Les vacances de Pandore"/></a></li>
		<li><a href="http://www.secondechance.org/"><img width="300px" src="http://www.secondechance.org/images/secondechance.jpg"/></a></li>
		<br>
		<li><a href="http://www.rescue-forum.com"><img width="300px" src="/forum/images/rescue.png"/></a></li>
		<li><a href="http://www.chat-perdu.org/"><img width="300px" src="http://www.chat-perdu.org/images/logo-chat-perdu-org.gif"/></a></li>
		<br>
		<li><a href="http://chatslibreslorient.com"><img width="630px" src="http://u.jimdo.com/www400/o/se8eb61c7ad35f3c0/emotion/crop/header.jpg" title="Chats libres de lorient"/></a></li>
		<br>
		<!--<li><a href="http://www.chatman.fr/"><img width="600px" src="http://www.chatman.fr/images/design/ban_chaTman.png" title="Comportementaliste spécialisée dans les relations Chats-Hommes, qui officie en Ille-et-Vilaine (35) et dans les départements limitrophes"/></a></li>-->
		<li><a href="http://assistance-feline.bb-fr.com/"><img width="630px" src="http://img15.hostingpics.net/pics/506423logo11.jpg" title="Forum de discussion et d'adoption pour les chats positifs (FIV/FELV)"/></a></li>
		<br>
		<li><a href="http://www.boulesdefourrure.fr/"><img width="300px" src="http://www.anthedesign.fr/w2015/wp-content/uploads/2012/07/blog.jpg" title="Boules de Fourrure (blog vétérinaire)"/></a></li>
		<li><a href="http://www.haikuprod.fr"><img width="300px" src="http://img15.hostingpics.net/pics/555817unnamed.jpg" alt="Haikuprod"/></a></li>
		<!--<li><a href="http://www.veterinaire.fr/"><img width="200px" src="http://www.veterinaire.fr/cru-1445617089/typo3conf/ext/site/Resources/Public/Frontend/vendor/html/assets/images/logo.png" title="Le Portail de l'Ordre des Vétérinaires"/></a></li>-->
		<li><a href="http://www.catsweethome.fr/"><img width="300px" src="http://www.catsweethome.fr/images/logo.gif" title="Garde d'animaux sur la région rennaise"/></a></li>
		<br>
		<li><a href="http://www.catstore.fr"><img width="300px" src="http://www.catstore.fr/images/catstore_10.png" alt="Catstore - La déco 100% chat"/></a></li>
		<li><a href="http://maliki.com"><img width="300px" src="http://maliki.com/wp-content/themes/maliki/img/logo_maliki_rollover.gif" title="Maliki, webcomic"/></a></li>
		<br>
		<li><a href="http://ellllsa.com/"><img width="200px" src="http://img15.hostingpics.net/pics/876788logoj.png" alt="ellllsa"/></a></li>
		<li><a href="http://www.catpatetcie.fr/"><img width="200px" src="/forum/images/catpatetcie.png" alt="catpatetcie.fr"/></a></li>
		<li><a href="http://www.educationduchiendecompagnie.fr/welcome/index.php"><img width="150px" src="http://www.educationduchiendecompagnie.fr/bannieres/banniere_edcdc_003.png"/></a></li>
		
	</ul>	
	<p>Plus de détails sur le forum, à cette adresse : 	<a href="http://felinpossible.fr/forum/viewforum.php?f=95">cliquez-ici <i class="icon-comment"></i></a>
	</p>	<p>Ce site est référencé dans la catégorie <a href="http://www.webrankinfo.com/annuaire/cat-310-animaux.htm">Animaux</a> : <a href="http://www.webrankinfo.com/annuaire/cat-5184-adoption-d-animaux.htm">Adoption d'animaux</a> de l'annuaire <a href="http://formation.webrankexpert.com/"><img src="http://www.webrankinfo.com/images/wri/webrankinfo-80-15.png" title="WebRankInfo" width="80" height="15" alt="Cours de referencement Olivier Duffez" /></a>   </p>		</div>