<div class="centre_principal">
		
	<p>
		Le parrainage d'un ou plusieurs chats consiste à faire un don mensuel à l'association pour l'aider dans la prise en charge du chat.
		Pour les non-adhérents, les 25 premiers euros, sont considérés comme une adhésion, les dons suivants vous offrent le droit à une réduction d'impôt de 66% du don.
	</p>
	
	<p>
		Si vous décidez de <b>parrainer un chat</b>, vous mettrez en place un virement automatique mensuel, d'une valeur de 5 euros minimum. Le montant de parrainage que nous conseillons est de 15 euros : c'est le coût estimé pour l'entretien d'un chat pour les dépenses habituelles (croquettes, litière, anti-puces, vermifuge...). Vous devez transmettre à votre banque une demande de virement mensuel de la somme de votre choix.
	</p>
	<p>
		En contrepartie de votre parrainage, vous aurez la satisfaction de voir concrètement le résultat de votre don, car vous recevrez régulièrement des nouvelles et des photos de votre filleul. En accord avec la Famille d'accueil, vous pouvez rendre visite au chat.
	</p>
	<p>
		Si le chat que vous parrainez est adopté, vous pouvez choisir d'en parrainer un autre ou d'arrêter votre virement automatique.
	</p>
	<p>
		Vous pouvez à tout moment choisir d'interrompre le parrainage.
	</p>

	<p>
		<b>Veuillez télécharger le rib ci-joint : <a href="http://felinpossible.fr/forum/download/file.php?id=6246"><i class=" icon-file"></i> rib de l'association</a></b>
	</p>
</div>
<div class="centre_principal">
	<br>
	<?php
	echo $this->form 
	?>
	<br>
</div>
