<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal">
	<p>
		Si vous décidez de <b>parrainer un chat</b>, vous mettrez en place un virement automatique mensuel, d'une valeur de 15 euros (minimum), 15 euros étant le coût estimé pour l'entretien d'un chat pour les dépenses habituelles (croquettes, litière, anti-puces, vermifuge...).
	</p>
	<p>
		En contrepartie de votre parrainage, vous aurez la satisfaction de voir concrètement le résultat de votre don, car vous recevrez régulièrement des nouvelles et des photos de votre filleul.
	</p>
	<p>
		Si le chat que vous parrainez est adopté, vous pouvez choisir d'en parrainer un autre ou d'annuler votre virement<br> automatique.
	</p>
	<p>
		Vous pouvez à tout moment choisir d'interrompre le parrainage.
	</p>

	<p>
		<b>Veuillez télécharger le rib ci-joint : <a href="http://img6.imageshack.us/img6/2696/rice1200909.jpg"><i class=" icon-file"></i> rib de l'association</a></b>
	</p>
</div>
<div class="centre_principal">
	<br>
	<?php
	echo $this->form 
	?>
	<br>
</div>
