<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal">
<iframe id="framePerdusTrouves" src="http://www.chat-perdu.org/iframe/ille-et-vilaine" width="100%" frameborder="0" marginheight="0" marginwidth="0">
  Votre navigateur ne supporte pas les "iframe". Pour consulter les annonces, veuillez vous rendre sur 
  <a href="http://www.chat-perdu.org/iframe/ille-et-vilaine">http://www.chat-perdu.org/iframe/ille-et-vilaine</a>
</iframe>
</div>