<div class="centre_principal">
	<h2>Présentation</h2>
	<h3>Création</h3>
	<p>
		FELIN POSSIBLE est une association loi 1901 créée en janvier 2008 par une poignée de passionnés de chats, particulièrement soucieux du bien-être et de la protection de ceux-ci.
	</p>

	<h3>Notre rayon d'action</h3>
	<p>
		Nous sommes présents sur toute l'Ille-et-Vilaine (35), principalement sur la région rennaise.
	</p>

	<h3>Nos objectifs</h3>
	<p>
		Ils sont doubles : 
	</p>
	<dl>
		<dt>Les adoptions</dt>
		<dd>Nous prenons en charge les chats abandonnés <b>(dans la limite de nos places disponibles en famille d'accueil)</b>, en vue de les faire adopter par des maîtres aimants et attentionnés, après les avoir testés, soignés, déparasités, vaccinés, identifiés et stérilisés.</dd>
		<dt>L'information</dt>
		<dd>Nous informons le grand public et nous le sensibilisons à la protection féline, notamment au problème de la surpopulation féline et à l'importance de la stérilisation.</dd>
	</dl>

	<h3>Les moyens mis en oeuvre</h3>
	<dl>
		<dt>Famille d'accueil</dt>
		<dd>Un réseau de familles d'accueil pour accueillir nos petits protégés, le temps de les soigner et de leur trouver une famille d'adoption.</dd>
		<dt>Communication</dt>
		<dd>La communication sur différents types de supports, comme internet, la diffusion d'affiches et de tracts, les articles dans la presse locale, ou la participation à des manifestations diverses sur le terrain, pour faire passer le message de sensibilisation à la protection féline auprès du plus grand nombre.</dd>
	</dl>
</div>
