<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal">
<br>
<h2>Création</h2>
<p>
FELIN POSSIBLE est une association loi 1901 créée en janvier 2008 par une poignée de passionnés de chats, particulièrement soucieux du bien-être et de la protection de ceux-ci.
</p>
<br>
<h2>Notre rayon d'action</h2>
<p>
Nous sommes présents sur toute l'Ille-et-Vilaine (35), principalement sur la région rennaise.
</p>
<br>
<h2>Nos objectifs</h2>
<p>
Ils sont doubles : 
</p>
<ul>
  <li>Les adoptions : nous prenons en charge les chats abandonnés <b>(dans la limite de nos places disponibles en famille d'accueil)</b>, en vue de les faire adopter par des maîtres aimants et attentionnés, après les avoir testés, soignés, déparasités, vaccinés, identifiés et stérilisés.</li>
  <li>L'information : nous informons le grand public et nous le sensibilisons à la protection féline, notamment au problème de la surpopulation féline et à l'importance de la stérilisation.</li>
</ul>

<br>
<h2>Les moyens mis en oeuvre</h2>
<ul>
  <li>Un réseau de familles d'accueil pour accueillir nos petits protégés, le temps de les soigner et de leur trouver une famille d'adoption.</li>
  <li>La communication sur différents types de supports, comme internet, la diffusion d'affiches et de tracts, les articles dans la presse locale, ou la participation à des manifestations diverses sur le terrain, pour faire passer le message de sensibilisation à la protection féline auprès du plus grand nombre.</li>
</ul>
</div>
