<ul id="menu" class="nav nav-list well">
        <li>
          <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script>
          <fb:like-box href="http://www.facebook.com/profile.php?id=100000118602118#!/pages/F%C3%A9lin-Possible/44926746491" width="200" show_faces="false" stream="false" header="false"></fb:like-box>
        </li>
        <li>  
          <br/>
          <div id="paypal">
            <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="1658266">
            <input type="image" src="https://www.paypal.com/fr_FR/FR/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="">
            <img alt="" border="0" src="https://www.paypal.com/fr_FR/i/scr/pixel.gif" width="1" height="1">
            </form>
          </div>
        </li>
</ul>