<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal">
<h2>Santé et Alimentation</h2>
<br/>
<ul>
  <li><a href="#ancreDangerPilule">Dangers de la pilule et importance de la stérilisation</a></li>
  <li><a href="#ancreImportanceVaccins">Importance de la vaccination</a></li>
  <li><a href="#ancreParasites">Parasites et maladies</a></li>
  <li><a href="#ancreNourriture">La nourriture et la boisson</a></li>
</ul>
<br><br>
<!-- Dangers pilule -->
<h3><a name="ancreDangerPilule">Dangers de la pilule et importance de la stérilisation</a></h3>
<p>
La pilule est <b>cancérigène</b> pour les chattes, et ce, potentiellement dès la première prise, même si les effets n'apparaissent pas tout de suite. Les pilules pour empêcher les chaleurs sont également très mauvaises pour les chattes.
</p>
<p>
Les chaleurs et les grossesses à répétition mènent les chattes à l'épuisement.
</p>
<p>
<b>C'est pourquoi il est indispensable de <u>stériliser</u> votre chat.</b>
</p>
<p>
Qu'il soit mâle ou femelle, ce n'est pas seulement pour votre confort personnel (fini le marquage, fini les miaulements des chaleurs), mais avant tout pour la santé de vos chats qu'il faut les stériliser. La stérilisation évitera les fugues, parfois de plusieurs jours, de vos mâles. Elle évitera aussi les bagarres entre mâles non-castrés (avec tous les risques de maladies qui en découlent). Elle évitera aussi aux femelles ces risques, ainsi que ceux liés aux grossesses multiples.
</p>
<p>
Enfin la stérilisation permettra de réduire la <b>surpopulation féline</b> qui est belle et bien présente, et qui représente actuellement un problème pour notre société.
</p>
<p>
Voici un lien vers le site de One Voice, qui explique très bien pourquoi il FAUT stériliser vos chats, les avantages de la stérilisation et les idées reçues sur celle-ci :
<a href="http://www.animaux-familiers.org/version_imprimable/animal_en_famille/sterilisation_print.html">cliquez-ici</a>.
</p>
<br>

<!-- Vaccins -->
<h3><a name="ancreImportanceVaccins">Importance de la vaccination</a></h3>
<p>
Faire vacciner votre chat, c'est un acte d'amour: c'est le protéger contre des maladies contagieuses et bien souvent mortelles.
</p>
<h4>A quel âge faut-il faire vacciner son chat ?</h4>
<p>
La vaccination du chat intervient lorsqu'il n'est plus protégé par les anticorps de sa mère, c'est-à-dire vers deux mois.
Le chat doit recevoir sa première injection à cet âge, et la seconde un mois plus tard. Ensuite, un rappel annuel est indispensable pour le protéger efficacement de nombreuses maladies, et ce, jusqu'à la fin de sa vie (les défenses immunitaires baissant avec l'âge).
</p>

<h4>Les maladies contre lesquelles il faut faire vacciner votre chat</h4>
<ul>
<li><b>La leucose (ou FELV)</b>
<br><u>Mode de transmission:</u> sang, voie sexuelle, salive, urines, liquide lacrymal…
La leucose est très contagieuse chez les chats, mais n'est pas transmissible à l'être humain.
<br><u>Symptômes:</u> perte de poids, anémie, apparition de ganglions, tumeurs aux reins, baisse générale des défenses immunitaires.
Il existe des tests de dépistage, à faire chez le vétérinaire, pour détecter la maladie.
Il est indispensable de vacciner votre chat contre la leucose si celui-ci a accès à l'extérieur ou est en contact avec des chats non-testés.
</li>
<li><b>Le typhus</b>
<br><u>Mode de transmission:</u> salive, selles... la contamination peut être indirecte (vêtements, chaussures etc...)
Le typhus n'est pas transmissible à l'homme, ni aux autres animaux.
<br><u>Symptômes:</u> forte fièvre parfois suivie d'une hypothermie, diarrhée, vomissements jaunes et odorants, forte déshydratation...
Le typhus est très contagieux et entraîne très souvent la mort, surtout chez les chatons.
Le virus est très résistant à l'air libre et peut subsister plusieurs mois dans l'environnement.
Le vaccin contre le typhus est très efficace, il est donc primordial de vacciner votre chat contre le typhus, même si celui-ci ne sort pas.
</li>
<li><b>Le coryza</b>
<br><u>Mode de transmission:</u> par contact ou même sans contact (maladie présente dans l'air)
Le coryza n'est pas transmissible à l'homme.
<br><u>Symptômes:</u> fièvre, écoulements nasaux, ulcères dans la bouche, conjonctivites infectieuses, manque d'appétit...
La maladie peut être mortelle dans les cas les plus grave, mais elle se soigne bien si elle est prise à temps.
Le vaccin n'empêche pas l'apparition de la maladie, mais il réduit fortement les risques de l'attraper, et empêche l'aggravation de la maladie. C'est pourquoi il est indispensable de vacciner votre chat contre le coryza, qu'il ait accès à l'extérieur ou non.
</li>
</ul>

<h4>Vaccination optionnelle </h4>
<ul>
<li><b>La rage</b>
<br><u>Mode de transmission:</u> par morsure
La rage est transmissible à l'homme.
La vaccination contre la rage n'implique qu'une seule injection lorsque le chaton a 3 mois, contrairement aux autres maladies qui en nécessitent 2.
Elle est obligatoire pour voyager à l'étranger avec votre chat ou pour le faire garder dans une pension.
</li>
</ul>
<br>
<p>
Nous avons la chance de disposer de vaccins contre certaines des maladies qui touchent nos chats, avouez que ce serait dommage de s'en passer. Vacciner votre chat, c'est non seulement lui éviter d'attraper des maladies, mais c'est aussi contribuer à éradiquer ces mêmes maladies, en les empêchant de proliférer. Plus il y a de chats vaccinés, et plus les maladies régressent.
</p>
<p>
<b>Pensez-y et n'oubliez pas les rappels !</b>
</p>
<br/>
<br/>

<!-- Parasites -->
<h3><a name="ancreParasites">Parasites et maladies</a></h3>
<p>
Votre chat peut être atteint par diverses maladies ou parasites.
</p>
<h4>Les parasites</h4>
<p>
Les plus courants sont les puces, les vers, les tiques, la gale des oreilles, la teigne….
</p>
<p>
Puce et vers vont ensemble. Il faut traiter les deux préventivement. Le produit anti-puces se met chaque mois, et se présente sous forme de pipettes à mettre entre les omoplates du chat.
</p>
<p>
Le vermifuge se présente sous forme de cachet ou de pipette. Il faut le donner chaque mois jusqu'aux 6 mois du chat, puis 2 fois par an pour un chat d'appartement, et tous les 3 / 4 mois pour un chat d'extérieur.
</p>
<p>
Les tiques se retrouvent généralement sur les chats d'extérieur au printemps. Elles s'accrochent à la peau du chat et lui sucent le sang. Pour les enlever, la meilleure solution reste la pince à tique, que l'on tourne jusqu'à ce que la tique se détache. Il faut éviter d'endormir la tique à l'éther.
</p>
<p>
La gale des oreilles se traduit par un dépôt brun au fond des oreilles, le chat se gratte bien souvent. Elle se traite à l'aide de pipettes à mettre entre les omoplates du chat.
</p>
<p>
Quant à la teigne, c'est un champignon qui se dépose sur la peau du chat et qui se traduit par des zones circulaires sans poils. La teigne n'est pas grave, mais elle est contagieuse pour les chats, les autres animaux, et les humains également. Son traitement est long et relativement coûteux.
</p>
<h4>Les maladies</h4>
<p>
Exemples : coryza, gastro-entérite, typhus, leucose, PIF, FIV…
</p>
<p>
Les maladies qui peuvent toucher nos chats sont multiples et sont plus ou moins graves. Heureusement nos chats bénéficient de vaccins qui réduisent grandement le risque de maladie.
</p>
<p>
Les vaccins qui sont faits couramment aujourd'hui sont ceux contre le coryza, le typhus, la leucose (FELV) et la rage. Le vaccin contre le coryza n'est pas efficace contre toutes les souches de la maladie, mais il réduit tout de même énormément le risque d'attraper la maladie et surtout celui de développer une forme grave de la maladie. Les vaccins contre le typhus et la leucose sont très efficaces. Ces 3 vaccins sont indispensables pour tout chat qui a accès à l'extérieur ou est en contact avec un autre chat.
</p>
<p>
Si votre chat vit en appartement et n'a aucun contact avec ses congénères, vous pouvez vous passer de le vacciner contre la leucose.
</p>
<p>
Afin de protéger efficacement votre chat contre ces maladies, n'oubliez pas de faire le rappel de vaccin chaque année !
</p>
<p>
Certaines maladies mortelles n'ont malheureusement pas encore de vaccins : c'est le cas de la PIF (Péritonite Infectieuse Féline) ou du FIV (Syndrôme d'Immuno-Déficience Acquise).
</p>
<p>
Au moindre doute concernant la santé de votre chat, n'hésitez pas à consulter votre vétérinaire. Mieux vaut s'inquiéter pour rien que de s'inquiéter trop tard…
</p>
<br>
<br>

<!-- Nourriture -->
<h3><a name="ancreNourriture">La nourriture et la boisson</a></h3>
<h4>La nourriture</h4>
<p>
Les vétérinaires conseillent généralement une alimentation à base de croquettes.
Il est essentiel de donner des croquettes de bonne qualité à votre chat.
Les marques distribuées chez votre vétérinaire ou en animalerie vous garantissent des aliments de bonne qualité.
A l'inverse, les marques distribuées par les supermarchés sont bien souvent de qualité médiocre et ont tendance à provoquer des problèmes rénaux (calculs, cystites, etc.).
</p>
<p>
Les croquettes que vous trouverez en animalerie ou chez le vétérinaire sont à première vue plus chères, mais à première vue seulement. Car ces croquettes sont plus nourrissantes que celles de supermarché, donc votre chat en mange moins. Et d'autre part, ces croquettes se trouvent en gros conditionnements (paquets de 10, voire 15 kilos), donc plus vous achetez un gros paquet, plus le prix au kilo baisse.
</p>
<h4>La boisson</h4>
<p>
De l'eau et uniquement de l'eau ! Un chat sevré n'a plus besoin de lait. Au contraire, celui-ci est mauvais pour lui, car il peut lui provoquer des troubles digestifs (diarrhées). Le lait pour chat que vous trouvez au supermarché est à considérer comme une friandise uniquement, il n'est en aucun cas à donner en guise de boisson principale.
</p>
<br><br>
<p>
Retrouvez plus d'informations sur notre forum : <a href='http://felinpossible.fr/forum/viewforum.php?f=15'>cliquez-ici</a>.
</p>
</div>