<div class="centre_principal">
	<h2>Santé et Alimentation</h2>
	<ul>
		<li><i class="icon-hand-right"></i> <a href="#ancreDangerPilule">Dangers de la pilule et importance de la stérilisation</a></li>
		<li><i class="icon-hand-right"></i> <a href="#ancreImportanceVaccins">Importance de la vaccination</a></li>
		<li><i class="icon-hand-right"></i> <a href="#ancreParasites">Parasites et maladies</a></li>
		<li><i class="icon-hand-right"></i> <a href="#ancreToxo">La toxoplasmose</a></li>
		<li><i class="icon-hand-right"></i> <a href="#ancreNourriture">La nourriture et la boisson</a></li>
	</ul>
	<!-- Dangers pilule -->
	<h3><a name="ancreDangerPilule">Dangers de la pilule et importance de la stérilisation</a></h3>
	<p>
		La pilule est <b>cancérigène</b> pour les chattes, et ce, potentiellement dès la première prise, même si les effets n'apparaissent pas tout de suite. Les pilules pour empêcher les chaleurs sont également très mauvaises pour les chattes.
	</p>
	<p>
		Les chaleurs et les grossesses à répétition mènent les chattes à l'épuisement.
	</p>
	<p>
		<b>C'est pourquoi il est indispensable de <u>stériliser</u> votre chat.</b>
	</p>
	<p>
		Qu'il soit mâle ou femelle, ce n'est pas seulement pour votre confort personnel (fini le marquage, fini les miaulements des chaleurs), mais avant tout pour la santé de vos chats qu'il faut les stériliser. La stérilisation évitera les fugues, parfois de plusieurs jours, de vos mâles. Elle évitera aussi les bagarres entre mâles non-castrés (avec tous les risques de maladies qui en découlent). Elle évitera aussi aux femelles ces risques, ainsi que ceux liés aux grossesses multiples.
	</p>
	<p>
		Enfin la stérilisation permettra de réduire la <b>surpopulation féline</b> qui est belle et bien présente, et qui représente actuellement un problème pour notre société.
	</p>
	<p>
		Voici un lien vers le site de One Voice, qui explique très bien pourquoi il FAUT stériliser vos chats, les avantages de la stérilisation et les idées reçues sur celle-ci :
		<a href="http://www.animaux-familiers.org/version_imprimable/animal_en_famille/sterilisation_print.html"><i class="icon-globe"></i> cliquez-ici</a>.
	</p>

	<!-- Vaccins -->
	<h3><a name="ancreImportanceVaccins">Importance de la vaccination</a></h3>
	<p>
		Faire vacciner votre chat, c'est un acte d'amour: c'est le protéger contre des maladies contagieuses et bien souvent mortelles.
	</p>
	<h4>A quel âge faut-il faire vacciner son chat ?</h4>
	<p>
		La vaccination du chat intervient lorsqu'il n'est plus protégé par les anticorps de sa mère, c'est-à-dire vers deux mois.
		Le chat doit recevoir sa première injection à cet âge, et la seconde un mois plus tard. Ensuite, un rappel annuel est indispensable pour le protéger efficacement de nombreuses maladies, et ce, jusqu'à la fin de sa vie (les défenses immunitaires baissant avec l'âge).
	</p>

	<h4>Les maladies contre lesquelles il faut faire vacciner votre chat</h4>
	<ul>
		<li><i class="icon-hand-right"></i> <b>La leucose (ou FELV)</b>
			<br><u>Mode de transmission:</u> sang, voie sexuelle, salive, urines, liquide lacrymal…
			La leucose est très contagieuse chez les chats, mais n'est pas transmissible à l'être humain.
			<br><u>Symptômes:</u> perte de poids, anémie, apparition de ganglions, tumeurs aux reins, baisse générale des défenses immunitaires.
			Il existe des tests de dépistage, à faire chez le vétérinaire, pour détecter la maladie.
			Il est indispensable de vacciner votre chat contre la leucose si celui-ci a accès à l'extérieur ou est en contact avec des chats non-testés.
		</li>
		<li><i class="icon-hand-right"></i> <b>Le typhus</b>
			<br><u>Mode de transmission:</u> salive, selles... la contamination peut être indirecte (vêtements, chaussures etc...)
			Le typhus n'est pas transmissible à l'homme, ni aux autres animaux.
			<br><u>Symptômes:</u> forte fièvre parfois suivie d'une hypothermie, diarrhée, vomissements jaunes et odorants, forte déshydratation...
			Le typhus est très contagieux et entraîne très souvent la mort, surtout chez les chatons.
			Le virus est très résistant à l'air libre et peut subsister plusieurs mois dans l'environnement.
			Le vaccin contre le typhus est très efficace, il est donc primordial de vacciner votre chat contre le typhus, même si celui-ci ne sort pas.
		</li>
		<li><i class="icon-hand-right"></i> <b>Le coryza</b>
			<br><u>Mode de transmission:</u> par contact ou même sans contact (maladie présente dans l'air)
			Le coryza n'est pas transmissible à l'homme.
			<br><u>Symptômes:</u> fièvre, écoulements nasaux, ulcères dans la bouche, conjonctivites infectieuses, manque d'appétit...
			La maladie peut être mortelle dans les cas les plus grave, mais elle se soigne bien si elle est prise à temps.
			Le vaccin n'empêche pas l'apparition de la maladie, mais il réduit fortement les risques de l'attraper, et empêche l'aggravation de la maladie. C'est pourquoi il est indispensable de vacciner votre chat contre le coryza, qu'il ait accès à l'extérieur ou non.
		</li>
	</ul>

	<h4>Vaccination optionnelle </h4>
	<ul>
		<li><i class="icon-hand-right"></i> <b>La rage</b>
			<br><u>Mode de transmission:</u> par morsure
			La rage est transmissible à l'homme.
			La vaccination contre la rage n'implique qu'une seule injection lorsque le chaton a 3 mois, contrairement aux autres maladies qui en nécessitent 2.
			Elle est obligatoire pour voyager à l'étranger avec votre chat ou pour le faire garder dans une pension.
		</li>
	</ul>
	<p>
		Nous avons la chance de disposer de vaccins contre certaines des maladies qui touchent nos chats, avouez que ce serait dommage de s'en passer. Vacciner votre chat, c'est non seulement lui éviter d'attraper des maladies, mais c'est aussi contribuer à éradiquer ces mêmes maladies, en les empêchant de proliférer. Plus il y a de chats vaccinés, et plus les maladies régressent.
	</p>
	<p>
		<b>Pensez-y et n'oubliez pas les rappels !</b>
	</p>

	<!-- Parasites -->
	<h3><a name="ancreParasites">Parasites et maladies</a></h3>
	<p>
		Votre chat peut être atteint par diverses maladies ou parasites.
	</p>
	<h4>Les parasites</h4>
	<p>
		Les plus courants sont les puces, les vers, les tiques, la gale des oreilles, la teigne….
	</p>
	<p>
		Puce et vers vont ensemble. Il faut traiter les deux préventivement. Le produit anti-puces se met chaque mois, et se présente sous forme de pipettes à mettre entre les omoplates du chat.
	</p>
	<p>
		Le vermifuge se présente sous forme de cachet ou de pipette. Il faut le donner chaque mois jusqu'aux 6 mois du chat, puis 2 fois par an pour un chat d'appartement, et tous les 3 / 4 mois pour un chat d'extérieur.
	</p>
	<p>
		Les tiques se retrouvent généralement sur les chats d'extérieur au printemps. Elles s'accrochent à la peau du chat et lui sucent le sang. Pour les enlever, la meilleure solution reste la pince à tique, que l'on tourne jusqu'à ce que la tique se détache. Il faut éviter d'endormir la tique à l'éther.
	</p>
	<p>
		La gale des oreilles se traduit par un dépôt brun au fond des oreilles, le chat se gratte bien souvent. Elle se traite à l'aide de pipettes à mettre entre les omoplates du chat.
	</p>
	<p>
		Quant à la teigne, c'est un champignon qui se dépose sur la peau du chat et qui se traduit par des zones circulaires sans poils. La teigne n'est pas grave, mais elle est contagieuse pour les chats, les autres animaux, et les humains également. Son traitement est long et relativement coûteux.
	</p>
	<h4>Les maladies</h4>
	<p>
		Exemples : coryza, gastro-entérite, typhus, leucose, PIF, FIV…
	</p>
	<p>
		Les maladies qui peuvent toucher nos chats sont multiples et sont plus ou moins graves. Heureusement nos chats bénéficient de vaccins qui réduisent grandement le risque de maladie.
	</p>
	<p>
		Les vaccins qui sont faits couramment aujourd'hui sont ceux contre le coryza, le typhus, la leucose (FELV) et la rage. Le vaccin contre le coryza n'est pas efficace contre toutes les souches de la maladie, mais il réduit tout de même énormément le risque d'attraper la maladie et surtout celui de développer une forme grave de la maladie. Les vaccins contre le typhus et la leucose sont très efficaces. Ces 3 vaccins sont indispensables pour tout chat qui a accès à l'extérieur ou est en contact avec un autre chat.
	</p>
	<p>
		Si votre chat vit en appartement et n'a aucun contact avec ses congénères, vous pouvez vous passer de le vacciner contre la leucose.
	</p>
	<p>
		Afin de protéger efficacement votre chat contre ces maladies, n'oubliez pas de faire le rappel de vaccin chaque année !
	</p>
	<p>
		Certaines maladies mortelles n'ont malheureusement pas encore de vaccins : c'est le cas de la PIF (Péritonite Infectieuse Féline) ou du FIV (Syndrôme d'Immuno-Déficience Acquise).
	</p>
	<p>
		Au moindre doute concernant la santé de votre chat, n'hésitez pas à consulter votre vétérinaire. Mieux vaut s'inquiéter pour rien que de s'inquiéter trop tard…
	</p>

	<!-- Toxoplasmose -->
	<h4><a name="ancreToxo">La toxoplasmose</a></h4>
	<i>(source : article de vétérinaire, ci-dessous un extrait, l'article complet est consultable ici : <a href="http://www.boulesdefourrure.fr/index.php?post/2011/05/15/Toxoplasmose-:-Foutez-la-paix-aux-chats-%21"><i class="icon-globe"></i> http://www.boulesdefourrure.fr</a>)</i>
	<p>
		<b>Quelles sont mes chances d'être contaminée par un toxoplasme ?</b>
	</p>
	<p>
		La toxoplasmose est généralement dépistée par des analyses sérologiques : on fait une prise de sang, et on regarde si le corps a des défenses contre les toxoplasmes, ce qui prouve qu'il a été en contact avec le parasite. On ne cherche pas le parasite, puisqu'il est en général enkysté dans les tissus, endormi et silencieux. Une séro positive ne permet pas de dire quand on a été en contact avec le parasite (même s'il y a des méthodes pour savoir si c'est ancien ou récent).
	</p>
	<p>
		Selon les études, 25 à 45% des chats domestiques sont séro positifs.
		On estime que 1% des chats sont excréteurs à un moment donné.
		Et seules les selles qui ont eu le temps de traîner dehors sont potentiellement infectieuses.
		Les chats ne sont excréteurs que pendant quelques jours à quelques semaines de leur vie, le temps pour eux d'obtenir les défenses adaptées suite à une primo-contamination. Des chats atteints de maladies immunodépressives (SIDA du chat, leucose féline) peuvent être excréteurs plus longtemps. On peut leur faire des sérologies : si la sérologie du chat est positive, il a de bonnes défenses, il n'est pas excréteur. Si elle est négative, il pourrait l'être ou le devenir s'il rencontre des toxoplasmes. D'ailleurs, il y a tellement de nuances que faire ces sérologies n'a aucun sens : mieux vaut avoir de bonnes pratiques d'hygiène, sur lesquelles je reviendrai plus loin.
	</p>
	<p>
		<b>La toxoplasmose, ça fait quoi ?</b>
	</p>
	<p>
		A un adulte en bonne santé, rien dans 80% des cas. Un bon syndrome fébrile avec pas mal de fatigue pour les 20% qui restent.
		A un chat, pas grand chose non plus : au pire, une gastro-entérite fébrile, j'en diagnostique de temps en temps. Les ovins avortent bien, par contre.
		Et c'est ce genre de risque qui intéresse la femme enceinte et qui fait la triste célébrité de la toxoplasmose : une infection pendant la grossesse peut avoir de graves répercussions sur la gestation, allant de l'avortement à la naissance d'un enfant atteint de troubles congénitaux. Les risques et les conséquences varient selon le stade de gestation, je n'y reviens pas, c'est assez bien expliqué ici et en de nombreux autres endroits.
	</p>
	<p>
		<b>Mais c'est horrible, il faut que je me débarrasse de mon chat !</b>
	</p>
	<p>
		<b>Non !</b>
	</p>
	<p>
		Au début de votre grossesse, on vous fera une sérologie pour vérifier si vous avez déjà été en contact avec le toxoplasme. Il ne faut vous inquiéter de ça que si vous êtes séronégative.
	</p>
	<p>
		J'ai eu un jour une discussion complexe avec une jeune femme enceinte à qui on avait très mal expliqué certains termes médicaux. Son chat était mort du FIV, le SIDA du chat. Son gynéco lui avait dit qu'elle était séropositive. Pour elle, séropositive, ça voulait dire "atteinte par le SIDA". Elle avait demandé si c'était son chat qui avait pu lui donner ça, le gynéco avait répondu oui, en pensant, évidemment, à sa séro toxo. Elle ne m'avait pas cru lorsque j'avais compris, et lui avais expliqué, la confusion. Donc hop, j'en profite pour le redire ici : le SIDA du chat et le SIDA de l'homme sont deux maladies différentes, la contagion est impossible.
	</p>
	<p>
		Vous êtes séronégative pour la toxoplasmose ?
	</p>
	<p>
		Je cite le rapport de l'AFSSA :
		<i>
			Malgré les résultats hétérogènes des études portant sur le risque d’acquisition de la toxoplasmose on peut identifier les facteurs de contamination les plus importants :
			<ul>
				<li><i class="icon-hand-right"></i> Le risque lié à la consommation de viande mal cuite ressort nettement de toutes les études. Il est essentiel qu’il soit clairement mis en avant dans toute information destinée à des femmes à risque.</li>
				<li><i class="icon-hand-right"></i> La consommation de crudités (légumes et fruits) insuffisamment nettoyées et la mauvaise hygiène des mains sont également des modes de contamination à intégrer dans un programme de prévention en insistant en particulier sur le risque des repas pris en dehors du domicile qui expose à la consommation de crudités insuffisamment lavées.</li>
				<li><i class="icon-hand-right"></i> La possession d’un chat ainsi que le nettoyage de sa litière : même si théoriquement sur le plan parasitologique le risque est faible (cf. section E), ces modes de contamination sont à prendre en compte dans un programme de prévention.</li>
			</ul>
		</i>
		<p>
			Cuisez bien votre viande, à cœur. Vous aurez des petits guides partout pour vous l'expliquer. La viande ovine est la plus à risque, mais tous les animaux à sang chaud peuvent être contaminés (surtout en milieu fermier). Congelez votre viande, mais à -20°C, pas dans le petit freezer de votre réfrigérateur.
			Lavez-vous les mains.
			Lavez les légumes, soigneusement.
			Nettoyez la litière du chat tous les jours, ou mieux faites nettoyer la litière tous les jours, et lavez-vous les mains.
		</p>
		<p>
			J'ai plusieurs consœurs vétérinaires, exerçant depuis plus d'une dizaine d'années, qui manipulent des chats malades tous les jours, des chatons, des chats immunodéprimés, qui se font mordre, griffer, qui font des coproscopies et manipulent dont des selles, et qui sont toujours séronégatives pour la toxoplasmose.
		</p>
		<p>
			Donc, je le dis, je le répète : on ne se débarrasse pas du chat .
		</p>

		<!-- Nourriture -->
		<h3><a name="ancreNourriture">La nourriture et la boisson</a></h3>
		<h4>La nourriture</h4>
		<p>
			Les vétérinaires conseillent généralement une alimentation à base de croquettes.
			Il est essentiel de donner des croquettes de bonne qualité à votre chat.
			Les marques distribuées chez votre vétérinaire ou en animalerie vous garantissent des aliments de bonne qualité.
			A l'inverse, les marques distribuées par les supermarchés sont bien souvent de qualité médiocre et ont tendance à provoquer des problèmes rénaux (calculs, cystites, etc.).
		</p>
		<p>
			Les croquettes que vous trouverez en animalerie ou chez le vétérinaire sont à première vue plus chères, mais à première vue seulement. Car ces croquettes sont plus nourrissantes que celles de supermarché, donc votre chat en mange moins. Et d'autre part, ces croquettes se trouvent en gros conditionnements (paquets de 10, voire 15 kilos), donc plus vous achetez un gros paquet, plus le prix au kilo baisse.
		</p>
		<h4>La boisson</h4>
		<p>
			De l'eau et uniquement de l'eau ! Un chat sevré n'a plus besoin de lait. Au contraire, celui-ci est mauvais pour lui, car il peut lui provoquer des troubles digestifs (diarrhées). Le lait pour chat que vous trouvez au supermarché est à considérer comme une friandise uniquement, il n'est en aucun cas à donner en guise de boisson principale.
		</p>
		<p>
			Retrouvez plus d'informations sur notre forum : <a href='http://felinpossible.fr/forum/viewforum.php?f=15'>cliquez-ici <i class="icon-comment"></i></a>.
		</p>
	</div>