<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal well">
<br>
<h2>Statuts</h2>

<h3>Article 1 : Constitution et Dénomination</h3>
<p>
Il est fondé entre les adhérents aux présents statuts une association régie par la loi du 1er juillet 1901 et le décret du 16 août 1901, ayant pour titre : Félin Possible.
</p>

<h3>Article 2 : Buts</h3>
<p>
Cette association a pour but de recueillir, soigner, et faire adopter les chats abandonnés, d'informer le public au sujet du problème de la surpopulation féline et de le sensibiliser à la protection féline.
</p>

<h3>Article 3 : Siège Social</h3>
<p>
Le siège social est fixé à cette adresse :<br>
<br>
</p>
<div class="align-center"><adress>
<strong>Association FELIN POSSIBLE</strong><br>
Chez Mademoiselle Caroline CANTIN<br>
La Ville es Ray<br>
35190 QUEBRIAC <br>
</adress>
</div>
<br>

<p>
Il pourra être transféré par simple décision du conseil d'administration.
</p>

<h3>Article 4 : Durée de l'Association</h3>
<p>
La durée de l'association est illimitée.
</p>

<h3>Article 5 : Moyens d'Action</h3>
<p>
Les moyens d'action de l'association sont notamment :
</p>
<ul>
  <li>Les publications sur internet, affiches et divers supports de communication</li>
  <li>les réunions de travail</li>
  <li>la vente permanente ou occasionnelle de tous produits ou services entrant dans le cadre de son objet ou susceptible de contribuer à sa réalisation</li>
  <li>l'organisation de manifestations et toute initiative pouvant aider à la réalisation de l'objet de l'association</li>
</ul>

<h3>Article 6 : Ressources de l'Association</h3>
<p>
Les ressources de l'association se composent :
</p>
<ul>
  <li>des cotisations</li>
  <li>de subventions éventuelles</li>
  <li>de recettes provenant de la vente de produits</li>
  <li>de services ou de prestations fournies par l'association</li>
  <li>de dons manuels</li>
  <li>et de toute autre ressource qui ne soit pas contraire aux règles en vigueur</li>
</ul>
<p>
Le Trésorier a pour mission de tenir la comptabilité de l'association et il doit en rendre compte auprès de l'ensemble des adhérents lors de l'assemblée générale, ainsi que chaque fois que le conseil d'administration en fait la demande.
</p>


<h3>Article 7 : Composition de l'Association</h3>
<p>
L'association se compose de :
</p>
<ul>
  <li>membres actifs, ou adhérents : sont membres actifs ceux qui sont à jour de leur cotisation annuelle. Ils ont le droit de vote à l'Assemblée Générale.</li>
  <li>membres d'honneur : sont membres d'honneur ceux qui ont rendu des services signalés à l'association. Ils sont dispensés de cotisations mais n'ont pas le droit de vote à l'assemblée générale.</li>
</ul>

<h3>Article 8 : Admission et Adhésion</h3>
<p>
Pour faire partie de l'association, il faut adhérer aux présents statuts, être agréé par le conseil d'administration et s'acquitter de la cotisation dont le montant est fixé par l'Assemblée Générale.
</p>
<p>
Les mineurs peuvent adhérer à l'association sous réserve d'un accord tacite ou d'une autorisation écrite de leurs parents ou tuteurs légaux. Ils sont membres à part entière de l'association.
</p>
<p>
Le Conseil d'Administration pourra refuser des adhésions. L'association s'interdit toute discrimination, veille au respect de ce principe et garantit la liberté de conscience pour chacun de ses membres.
</p>

<h3>Article 9 : Perte de la qualité de Membre</h3>
<p>
La qualité de membre se perd par :
</p>
<ul>
  <li>la démission</li>
  <li>le décès</li>
  <li>la radiation prononcée par le Conseil d'Administration pour non paiement de la cotisation ou pour motif grave</li>
</ul>

<h3>Article 10 : Assemblée Générale Ordinaire</h3>
<p>
L'Assemblée Générale ordinaire se réunit au moins une fois par an.
</p>
<p>
Elle comprend tous les membres de l'association, y compris les membres mineurs. Seuls les membres âgés de 18 au moins au jour de l'élection sont autorisés à voter. Pour les autres, leur droit de vote est transmis à leur parent ou représentant légal.
</p>
<p>
L'assemblée générale est convoquée par le Président, à la demande du Conseil d'Administration ou à la demande du tiers au moins des adhérents.
</p>
<p>
Quinze jours au moins avant la date fixée, les membres de l'association sont convoqués et l'ordre du jour est inscrit sur les convocations.
</p>
<p>
Le Président, assisté du conseil d'administration, préside l'assemblée générale.</p>
<p>
L'assemblée, après avoir délibéré, se prononce sur les rapports moral ou d'activité.</p>
<p>
Le Trésorier rend compte de l'exercice financier.</p>
<p>
Elle délibère sur les orientations à venir, et se prononce sur le budget correspondant.</p>
<p>Elle pourvoit à la nomination ou au renouvellement des membres du conseil d'administration.</p>
<p>Elle se prononce sur le montant de la cotisation annuelle et les divers tarifs d'activité.</p>
<p>Les décisions de l'assemblée sont prises à la majorité des membres présents ou représentés.</p>
<p>Les décisions prises obligent tous les adhérents, même les absents.
</p>

<h3>Article 11 : Conseil d'Administration</h3> 
<p>
L'association est dirigée par un Conseil d'Administration composé de 6 membres au maximum, élus pour une année par l'Assemblée Générale.</p>
<p>
Le Conseil d'Administration se réunit une fois au mois chaque année, ou sur la demande du quart de ses membres.</p>
<p>
Les membres du Conseil d'Administration sont rééligibles. Les décisions sont prises à la majorité des voix. En cas de partage, la voix du Président est prépondérante. Le vote par procuration est autorisé.</p>
<p>
En cas de vacance de poste, le Conseil d'Administration pourvoit provisoirement au remplacement de ses membres. Il est procédé à leur remplacement définitif à la prochaine Assemblée Générale. Les pouvoirs des membres ainsi élus prennent fin à l'époque où devrait normalement expirer le mandat des membres remplacés.</p>
<p>
Nul ne peut faire partie du Conseil s'il n'est pas majeur.</p>
<p>
Le Conseil d'Administration choisit parmi ses membres, un bureau composé de :
</p>
<ul>
  <li>un Président, et si besoin, un ou plusieurs Vice-Présidents</li>
  <li>un Secrétaire et si besoin, un Secrétaire Adjoint</li>
  <li>un Trésorier et si besoin, un Trésorier Adjoint</li>
</ul>

<h3>Article 12 : Rémunération</h3> 
<p>
Les fonctions de membres du conseil d'administration sont bénévoles.
</p>

<h3>Article 13 : Assemblée Générale Extraordinaire</h3>
<p>
Si besoin est, ou sur la demande de la moitié plus un des membres inscrits, le Président peut convoquer une assemblée générale extraordinaire. Les conditions de convocation sont identiques à celles de l'Assemblée Générale Ordinaire.
</p>

<h3>Article 14 : Règlement Intérieur</h3>
<p>
Un règlement intérieur peut être établi par le Conseil d'Administration.
</p> 
<p>
Ce règlement éventuel est destiné à fixer les divers points non prévus par les statuts, notamment ceux qui ont trait à l'administration interne de l'association.
</p>

<h3>Article 15 : Dissolution</h3>
<p>
En cas de dissolution prononcée par l'Assemblée Générale Extraordinaire, convoquée selon les modalités prévues à l'article 12, un ou plusieurs liquidateurs sont nommés par celle-ci et l'actif, s'il y a lieu, est dévolu à une association ayant des buts similaires, conformément à l'article 9 de la loi du 1er juillet 1901 et au décret du 16 août 1901.
</p>
<p> 
Les présents statuts sont approuvés par l'Assemblée Constitutive du 22/12/2007.
</p>
</div>