<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal well">
<br/><h2>Pourquoi st&eacute;riliser son chat</h2><br/>
<p>La <b>stérilisation</b> est nécessaire car elle lutte contre la <b>prolifération</b> des chats. Chaque année, il naît beaucoup plus de chatons qu'il y a de maîtres potentiels. Résultat : des chatons sont tués à la naissance, parfois par des méthodes barbares indignes d'un peuple dit « civilisé » au 21ème siècle, certains se verront abandonnés dans la nature, d'autres encore seront jetés négligemment (et courageusement…) dans un carton à la porte d'un refuge.Refuge dans lequel certains passeront toute leur vie car trop craintifs, trop « classiques », pas assez « à la mode » aux yeux des adoptants.</p>

<p>Certaines personnes considèrent que <b>stériliser</b> les chats, c'est aller contre la nature. </p>

<p>Et pourtant, il n'y a <b>QUE</b> des avantages à la stérilisation, pour les maîtres, mais surtout <u>pour les chats</u> : 
</p>
<ul>
  <li>elle lutte contre la <b>surpopulation féline</b> en réduisant la prolifération des chats</li>
  <li>elle réduit grandement le <b>risque de cancer</b> des mamelles ou de l'utérus chez la chatte, d'autant plus quand elle est pratiquée avant les premières chaleurs</li>
  <li>elle réduit, chez les mâles comme chez les femelles, le <b>risque de fugues et de bagarres</b>, et par conséquent tous les risques qui y sont liés (risque de se faire écraser, d'attraper des <b>maladies</b> sexuellement transmissibles comme la leucose ou le sida du chat…)</li>
  <li>elle limite le risque de <b>marquage urinaire</b>, très fréquent chez les chats non-stérilisés</li>
  <li>elle est <b>avantageuse financièrement</b>. Certes elle représente un certain coût (110 euros pour une femelle, 60 euros pour un mâle), mais donner la pilule pendant des années revient au final plus cher, sans compter les frais vétérinaires qui en découleront, car la pilule est hautement cancérigène et ce, dès la première prise</li>
</ul>

<h2>Alors n'h&eacute;sitez plus st&eacute;rilisez-les</h2>
</div>