<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal">
  <h2>Tarifs</h2>
  <p>
    Les tarifs vétérinaires ayant augmenté depuis le premier janvier dernier, nous sommes obligés de répercuter (en partie) cette hausse dans nos forfaits d'adoption. 
  </p>
  <p>
    Voici donc <b>les tarifs en vigueur</b> :
  </p>
  <p>
    <strong>155 €</strong> pour un chat :
    <ul>
      <li><i class="icon-hand-right"></i> <b>testé</b> FIV/FELV,</li>
      <li><i class="icon-hand-right"></i> <b>stérilisé</b>,</li>
      <li><i class="icon-hand-right"></i> <b>identifié</b> (par puce électronique ou tatouage),</li>
      <li><i class="icon-hand-right"></i> et <b>ayant eu sa première injection de vaccins</b> (le rappel dans ce cas est à la charge des adoptants, et à faire dans le mois qui suit l'adoption)</li>
    </ul>
  </p>
  <p>
    <strong>185 €</strong> pour un chat :
    <ul>
      <li><i class="icon-hand-right"></i> <b>testé</b> FIV/FELV,</li>
      <li><i class="icon-hand-right"></i> <b>stérilisé</b>,</li>
      <li><i class="icon-hand-right"></i> <b>identifié</b> (par puce électronique ou tatouage),</li>
      <li><i class="icon-hand-right"></i> et <b>ayant eu sa primo-vaccination complète (2 injections)</b></li>
    </ul>
  </p>
  <p>
    Ce tarif est valable uniquement pour les chats pris en charge à partir du 1er janvier 2012. 
  </p>
  <p>
    Pour les chats pris en charge avant cette date, l'<b>ancien tarif (180 €)</b> reste valable.
  </p>
  <p>
    Si la stérilisation n'est pas faite au moment de l'adoption (car le chat est trop jeune), nous vous donnerons un bon de stérilisation à donner au vétérinaire le jour de l'opération.
  </p>
  <p> 
    La facture sera ainsi envoyée directement à l'association et vous n'aurez rien à débourser le moment venu. La <b><u>stérilisation est obligatoire</u></b> pour tous nos chats, mâles comme femelles. 
  </p>
  <p>
    Règlement par <u>chèque libellé au nom de FELIN POSSIBLE</u>.
  </p>
</div>
