<div class="centre_principal">
  <h2>Tarifs</h2>
  <p>
    Les situations des chats sont très diverses, l'association adapte donc le tarif d'adoption en fonction des soins obligatoires déjà reçus au moment de l'adoption.
  </p>
  <p>
    Voici donc <b>les tarifs en vigueur</b> :
  </p>
  <p>
		<div class="align-center">
			<img src="/site/public/img/prix2.png"/>
		</div>
  </p>
  </br>
  <p>
    La <u><strong>stérilisation est obligatoire</strong></u> pour tous nos chats, mâles comme femelles. Si la stérilisation n'est pas faite au moment de l'adoption (car le chat est trop jeune), nous vous demanderons un chèque de caution (non-encaissé), que nous détruirons sur présentation d'un justificatif de stérilisation.
  </p>

  <p>
    Règlement par <u>chèque libellé au nom de FELIN POSSIBLE</u> (merci de bien vouloir vérifier la solvabilité de votre compte auparavant).
  </p>


    <h3>Réservation d'un chat</h3>
  <p>
    Vous êtes nombreux à vouloir réserver un chat mais ne l'adopter qu'après vos vacances, ce que nous comprenons très bien. 
  </p>
  <p>
    Malheureusement cela ne nous arrange pas, d'une part car cela nous oblige à bloquer une place en famille d'accueil pendant ces quelques semaines, alors que nous en manquons cruellement, nos familles d'accueil étant pour beaucoup elles aussi en vacances, et la période étant propice à une forte augmentation des abandons. 
  </p>
  <p>
    C'est pourquoi, en cas de <strong>garde</strong> pour vous arranger (pour le cas où le chat est adoptable immédiatement), l'association vous demandera une <u>participation aux frais d'entretien</u> du chat (croquettes etc) de <strong>15€</strong> pour ce <u>service</u>, qui ne pourra excéder 4 semaines (à noter qu'une garde dans une pension ou une société de garde d'animaux coûte environ 10-12 euros <u>par jour</u>).
  </p>
  <p>
    <em>Précision: l'association ne fait pas de gardes par ailleurs, ceci est valable uniquement pour les chats à l'adoption.</em>
  </p>
  <p>
    Par ailleurs pour toute <strong>réservation</strong>, si l'adoption ne se fait pas dans la foulée (notamment pour les chatons qui ne sont pas encore en âge d'être adoptés), nous demandons un <strong>chèque de caution de 80 euros</strong>, qui ne sera encaissé qu'après l'adoption, et déduit du montant global de l'adoption. Ceci pour éviter les désistements de dernière minute, qui enlèveraient des chances d'adoption au chat réservé en le bloquant pendant x semaines. 
  </p>
  <p>
    Merci de votre compréhension. 
  </p>
</div>
