<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal">
<h2>Tarifs</h2>
<p>Afin de ne pas favoriser l'adoption des mâles par rapport aux femelles, nous avons fait le choix de vous proposer un tarif unique de :
<span class="prixAdoption">140 euros*</span>.
</p>
<p>
Ce tarif comprend :
</p>
<ul>
  <li>les tests FIV / FELV</li>
  <li>les 3 premiers vaccins Typhus / Coryza / Leucose</li>
  <li>le Tatouage</li>
  <li>la Stérilisation</li>
</ul>

<p>
Si le <u>rappel de vaccins</u> est fait, nous vous demanderons un complément de <u>30 euros</u> pour celui-ci.
</p>
<p>
Si le chat porte une <u>puce électronique</u> à la place du tatouage (comme c'est souvent le cas pour les chatons), nous demandons <u>10 euros</u> supplémentaires pour celle-ci.
</p>
<p>
Si la stérilisation n'est pas faite (car le chat est trop jeune), nous vous donnerons un bon de stérilisation à donner au vétérinaire le jour de l'opération. La facture sera ainsi envoyée directement à l'association et vous n'aurez rien à débourser le moment venu.
</p>
<p>
Règlement par chèque libellé au nom de FELIN POSSIBLE.
</p>
<p>
Possibilité de tarif spécial pour les chats âgés ou positifs au FIV/FELV.
</p>
<p>
(*) Possibilité de régler en plusieurs fois.
</p>

</div>