<?php if ($this->pageCount): ?>
<div id="paginationControl" class="pagination pagination-centered">
<ul>

<!-- First page link --> 
<?php if (isset($this->previous)): ?> 
  <li><a href="#<?php echo $this->url(array('page' => $this->first)); ?>" rel="ajax">«</a></li> 
<?php endif; ?> 

<!-- Previous page link --> 
<?php if (isset($this->previous)): ?> 
  <li><a href="#<?php echo $this->url(array('page' => $this->previous)); ?>" rel="ajax">Préc.</a></li> 
<?php endif; ?> 

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?> 
  <?php if ($page != $this->current): ?>
    <li><a href="#<?php echo $this->url(array('page' => $page)); ?>" rel="ajax">
     <?php echo $page; ?>
    </a></li>
  <?php else: ?>
    <li class="active"><span><?php echo $page; ?></span></li>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link --> 
<?php if (isset($this->next)): ?> 
  <li><a href="#<?php echo $this->url(array('page' => $this->next)); ?>" rel="ajax">Suiv.</a></li>
<?php endif; ?> 

<!-- Last page link --> 
<?php if (isset($this->next)): ?> 
  <li><a href="#<?php echo $this->url(array('page' => $this->last)); ?>" rel="ajax">»</a></li>
<?php endif; ?> 
</ul>
</div> 
<?php endif; ?>
