<?php if ($this->pageCount): ?>
<div id="paginationControl" class="pagination pagination-centered">
<ul>

<!-- First page link --> 
<?php if (isset($this->previous)): ?> 
  <li><a href="<?php echo $this->url(array('page' => $this->first)); ?>" 
     onclick="showPage('<?php echo $this->url(array('page' => $this->first)); ?>'); return false;">«</a></li> 
<?php endif; ?> 

<!-- Previous page link --> 
<?php if (isset($this->previous)): ?> 
  <li><a href="<?php echo $this->url(array('page' => $this->previous)); ?>" 
     onclick="showPage('<?php echo $this->url(array('page' => $this->previous)); ?>'); return false;">Préc.</a></li> 
<?php endif; ?> 

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?> 
  <?php if ($page != $this->current): ?>
    <li><a href="<?php echo $this->url(array('page' => $page)); ?>"
       onclick="showPage('<?php echo $this->url(array('page' => $page)); ?>'); return false;">
     <?php echo $page; ?>
    </a></li>
  <?php else: ?>
    <li class="active"><span><?php echo $page; ?></span></li>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link --> 
<?php if (isset($this->next)): ?> 
  <li><a href="<?php echo $this->url(array('page' => $this->next)); ?>"
     onclick="showPage('<?php echo $this->url(array('page' => $this->next)); ?>'); return false;">Suiv.</a></li>
<?php endif; ?> 

<!-- Last page link --> 
<?php if (isset($this->next)): ?> 
  <li><a href="<?php echo $this->url(array('page' => $this->last)); ?>"
     onclick="showPage('<?php echo $this->url(array('page' => $this->last)); ?>'); return false;">»</a></li>
<?php endif; ?> 
</ul>
</div> 
<?php endif; ?>
