<?php echo $this->doctype() ?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/> 
  <?php echo $this->headTitle() ?>
  <?php echo $this->headLink() ?>
  <?php echo $this->headStyle() ?>
</head>
<body onload="init()" class="tundra">
  <!-- Header -->
  <div class="row-fluid">
    <div class="span12"><?php echo $this->render('menuHaut.phtml') ?></div>
  </div>

  <header class="header hidden-phone"><?php echo $this->partial('header.phtml'); ?></header>

  <div class="container-fluid">
    <!-- Content -->
    <div class="row-fluid">
      <div id="main-menu" class="span3">
        <?php if ($this->login) {
          echo $this->partial('menuAdmin.phtml'); 
        } else {
         echo $this->partial('menu.phtml');
       }
       ?>
     </div>
     <div id="main-content" class="span9">
      <div id="corps">
        <?php echo $this->layout()->content ?>
      </div>
      <div id="chargementCorps" class="ajax" style="display:none"></div>
    </div>
  </div>
</div>

<!-- Footer -->
<div class="row-fluid">
  <div class="span12"><?php echo $this->partial('footer.phtml') ?></div>
</div>

<?php echo $this->dojo() ?>
<?php echo $this->headScript() ?>
</body>
</html>