<?php echo $this->doctype() ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->dojo() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
</head>
<body onload="init()" class="tundra">

  <div id="all">
    <?php echo $this->partial('header.phtml'); ?>
    
    <div id="global">
      <?php echo $this->render('logout.phtml') ?>
      <?php 
        if ($this->login) {
          echo $this->partial('menuGaucheAdmin.phtml'); 
        } else {
          echo $this->partial('menuGauche.phtml');
        }
      ?>

      <div id="chargementCorps" class="ajax" style="display:block"></div>
      
      <div id="corps" class="png" style="display:none">
        <?php echo $this->layout()->content ?>
      </div>
      
      <div class="astuce"></div>
    </div>
    <?php echo $this->partial('footer.phtml') ?>
  </div>
</body>
</html>