<?php echo $this->doctype() ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
</head>
<body onload="init()" class="tundra">
  <!-- Header -->
  <div class="row-fluid">
    <div class="span12"><?php echo $this->partial('menuHaut.phtml') ?></div>

  </div>

  <header class="header"><?php echo $this->partial('header.phtml') ?></header>

  <div class="container-fluid">
  
  <!-- Content -->
  <div class="row-fluid">
    <div id="main-menu" class="span2">
      <?php 
        if ($this->login) {
          echo $this->partial('menuGaucheAdmin.phtml'); 
        } else {
          echo $this->partial('menu.phtml');
        }
      ?>
      <?php echo $this->render('logout.phtml') ?>
    </div>
    <div id="main-content" class="span10">
      <div id="corps">
        <?php echo $this->layout()->content ?>
      </div>
      <div id="chargementCorps" class="ajax" style="display:block"></div>
    </div>
  </div>

  <!-- Footer -->
  <div class="row-fluid">
    <div class="span12"><?php echo $this->partial('footer.phtml') ?></div>
  </div>

  <?php echo $this->dojo() ?>
  <?php echo $this->headScript() ?>
</body>
</html>