<div class="hidden-desktop">
  <?php echo $this->partial("index/reference.phtml"); ?>
</div>

<div class="row-fluid footer">
  <div class="span12">
    <p><em>© 2012 felinpossible.fr, Association FelinPossible</em></p>
    <div class="navbar pull-right">
      <div class="navbar-inner">
        <ul class="nav">
          <li><a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'index')) ?>">Administration</a></li>
          <li><a href="/spongestats/index.php" class="lien-adm">SpongeStats</a></li>
        </ul>
      </div>
    </div>
    <br>
    <p>

      <!-- Begin zooplus Partner Program Code -->

      <a href="http://www.zooplus.fr/shop/chats/partner/zap62839">

        <img src="http://www.zooplus.fr/affiliate/material/zap62839" alt="Chat" border="0"/>

      </a>

      <!-- End zooplus Partner Program Code -->



      <!-- Begin wanimo Partner Program Code -->

      <a href="http://action.metaffiliation.com/suivi.php?mclic=S3CFA529D33145" >

        <img src="http://action.metaffiliation.com/suivi.php?maff=S3CFA529D33145" border="0">

      </a>

      <!-- End wanimo Partner Program Code -->



      <!-- BEGIN CODE NetAffiliation : http://www.netaffiliation.com/ - Groupon -->

      <a href="http://action.metaffiliation.com/suivi.php?mclic=S43B15529D33167" target="_blank">

        <img src="http://action.metaffiliation.com/suivi.php?maff=S43B15529D33167" border="0">

      </a>

      <!-- END CODE NetAffiliation -->



      <!-- BEGIN CODE NetAffiliation : http://www.netaffiliation.com/ - Vivastreet -->

      <a href="http://action.metaffiliation.com/suivi.php?mclic=S45D53529D331112" target="_blank"><img src="http://action.metaffiliation.com/suivi.php?maff=S45D53529D331112" height="100" width="100" border="0"></a>

      <!-- END CODE NetAffiliation -->

      <!--  polytrans -->

      <a href="http://www.polytrans.fr"> <img width="120" height="40" alt="Polytrans : animalerie en ligne chiens et chats" src="http://www.polytrans.fr/images/polytrans1.jpg" /> </a>

    </p>
    <p>Icônes fournies par <a href="http://www.iconbeast.com/free/">Iconbeast</a>.</p>
  </div>
</div>