<div id="footer" class="png">
<p class=padding2>
  <FONT size=1pt> © 2008 felinpossible.com, Association FelinPossible - Une réalisation de Boost35, Lutine & Nineland. | 
     <a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'index')) ?>"
        class="lien-adm">Administration</a> | 
     <a href="/spongestats/index.php" class="lien-adm">SpongeStats</a> | 
     <a class="lien-adm" href="<?php echo $this->url(array('controller' => 'news', 'action' => 'flux')) ?>">Flux RSS<span class="rss"></span></a> 
  </FONT>
</p>
<p align="center">
  <!-- Begin zooplus Partner Program Code -->
  <a href="http://www.zooplus.fr/shop/chats/partner/zap62839">
    <img src="http://www.zooplus.fr/affiliate/material/zap62839" alt="Chat" border="0"/>
  </a>
  <!-- End zooplus Partner Program Code -->
  
  <!-- Begin wanimo Partner Program Code -->
  <a href="http://action.metaffiliation.com/suivi.php?mclic=S3CFA529D33145" >
    <img src="http://action.metaffiliation.com/suivi.php?maff=S3CFA529D33145" border="0">
  </a>
  <!-- End wanimo Partner Program Code -->
  
  <!-- BEGIN CODE NetAffiliation : http://www.netaffiliation.com/ - Groupon -->
  <a href="http://action.metaffiliation.com/suivi.php?mclic=S43B15529D33167" target="_blank">
    <img src="http://action.metaffiliation.com/suivi.php?maff=S43B15529D33167" border="0">
  </a>
  <!-- END CODE NetAffiliation -->
  
  <!-- BEGIN CODE NetAffiliation : http://www.netaffiliation.com/ - Vivastreet -->
  <a href="http://action.metaffiliation.com/suivi.php?mclic=S45D53529D331112" target="_blank"><img src="http://action.metaffiliation.com/suivi.php?maff=S45D53529D331112" height="100" width="100" border="0"></a>
  <!-- END CODE NetAffiliation -->
  <!--  polytrans -->
  <a href="http://www.polytrans.fr"> <img width="120" height="40" alt="Polytrans : animalerie en ligne chiens et chats" src="http://www.polytrans.fr/images/polytrans1.jpg" /> </a>
</p>
</div>
