<div id="footer" class="png">
<p class=padding2>
  <FONT size=1pt> © 2008 felinpossible.com, Association FelinPossible - Une réalisation de Boost35, Lutine & Nineland. | 
     <a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'index')) ?>"
        class="lien-adm">Administration</a> | 
     <a href="/spongestats/index.php" class="lien-adm">SpongeStats</a> | 
     <a class="lien-adm" href="<?php echo $this->url(array('controller' => 'news', 'action' => 'flux')) ?>">Flux RSS<span class="rss"></span></a> 
  </FONT>
</p>
<p align="center">
  <!-- Begin zooplus Partner Program Code -->
  <a href="http://www.zooplus.fr/shop/chats/partner/zap62839">
    <img src="http://www.zooplus.fr/affiliate/material/zap62839" alt="Chat" border="0"/>
  </a>
  <!-- End zooplus Partner Program Code -->
</p>
</div>
