<?php echo $this->doctype() ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->dojo(); ?>
    <?php echo $this->headScript() ?>

</head>
<body onload="init()" >
  <div id="all">
    <?php echo $this->partial('header.phtml') ?>
    <div id="global">
      <?php echo $this->partial('menuGauche.phtml') ?>
      
      <div id="chargementCorps" class="ajax" style="display:block"></div>
      
      <div id="corps" class="png" style="display:none">
        <?php echo $this->layout()->content ?>
      </div>
      
      <div class="astuce"></div>
    </div>
    <?php echo $this->partial('footer.phtml') ?>
  </div>
  <!-- Google analytics -->
  <script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-12513665-1");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>
</html>