<div class="accordion well" id="accordionMenu">
  <!-- Association -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" data-toggle="collapse" data-parent="#accordionMenu" href="#collapseAsso">
        <i class="icone-home pull-left"></i>L'association
      </a>
    </div>
    <div id="collapseAsso" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul class="nav nav-pills nav-stacked">
            <li class="active"><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'home')) ?>" title="Accueil" onclick="showPage('<?php echo $url ?>'); return false;">Accueil</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'presentation')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Pr&eacute;sentation">Présentation</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'statuts')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Statuts">Statuts</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'news', 'action' => 'index')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="News">News</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'charge')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Prise en charge">Prise en charge</a></li>
          </ul>
      </div>
    </div>
  </div>

  <!-- Nous aider -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" data-toggle="collapse" data-parent="#accordionMenu" href="#collapseAider">
        <i class="icone-aider pull-left"></i>Nous aider
      </a>
    </div>
    <div id="collapseAider" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul class="nav nav-pills nav-stacked">
            <li><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'adherent')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Adh&eacute;rer">Adh&eacute;rer</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'parrainer')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Parrainer un chat">Parrainer un chat</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'benevole')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Devenir b&eacute;n&eacute;vole">Devenir b&eacute;n&eacute;vole</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'fa', 'action' => 'index')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Etre Famille d&rsquo;Accueil">Etre Famille d&rsquo;Accueil</a></li>
          </ul>
      </div>
    </div>
  </div>

  <!-- Les chats -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" data-toggle="collapse" data-parent="#accordionMenu" href="#collapseChats">
        <i class="icone-empreinte pull-left"></i>Les chats
      </a>
    </div>
    <div id="collapseChats" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul class="nav nav-pills nav-stacked">
            <li><a href="<?php echo $url = $this->url(array('controller' => 'chat', 'action' => 'adoption')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Chats &agrave; l&rsquo;adoption">Chats &agrave; l&rsquo;adoption</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'chat', 'action' => 'adoptes')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Chats adopt&eacute;s">Chats adopt&eacute;s</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'chat', 'action' => 'parrainer')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Chats &agrave; parrainer">Chats &agrave; parrainer</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'chat', 'action' => 'disparus')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Les disparus">Les disparus</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'perdus')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Perdus/Trouv&eacute;">Perdus/Trouv&eacute;s</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'charge')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Prise en charge">Prise en charge</a></li>
          </ul>
      </div>
    </div>
  </div>

  <!-- Adopter -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" data-toggle="collapse" data-parent="#accordionMenu" href="#collapseAdopter">
        <i class="icone-poussette pull-left"></i>Adopter
      </a>
    </div>
    <div id="collapseAdopter" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul class="nav nav-pills nav-stacked"> 
            <li><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'adoption')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="A lire avant toute adoption">A lire avant d'adopter</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'tarifs')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Tarifs">Tarifs</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'adoptant', 'action' => 'process')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Poster sa candidature">Poster sa candidature</a></li>
          </ul>
      </div>
    </div>
  </div>

  <!-- Conseils -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" data-toggle="collapse" data-parent="#accordionMenu" href="#collapseConseils">
        <i class="icone-info pull-left"></i>Conseils
      </a>
    </div>
    <div id="collapseConseils" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul class="nav nav-pills nav-stacked">
            <li><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'arrivee')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="L&rsquo;arriv&eacute;e de votre chat">L&rsquo;arriv&eacute;e de votre chat</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'sante')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Sant&eacute; &amp; Alimentation">Sant&eacute; &amp; Alimentation</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'sterilisation')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="La st&eacute;rilisation">La st&eacute;rilisation</a></li>
            <li><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'dangers')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Les Dangers">Les dangers</a></li>
          </ul>
      </div>
    </div>
  </div>

  <!-- Liens -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'liens')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" title="Liens">
        <i class="icone-lien pull-left"></i>Liens
      </a>

    </div>
  </div>

  <!-- Forum -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" href="/forum/index.php" title="Forum">
        <i class="icone-message pull-left"></i>Forum
      </a>
    </div>
  </div>        
</div>

<div class="visible-desktop">
  <?php echo $this->partial("index/reference.phtml"); ?>
</div>