<div class="visible-desktop">
  <?php echo $this->partial("index/reference.phtml"); ?>
</div>
<div class="accordion well" id="accordionMenu">
  <!-- Association -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" data-toggle="collapse" data-parent="#accordionMenu" href="#collapseAsso">
        <i class="icone-home pull-left"></i>L'association
      </a>
    </div>
    <div id="collapseAsso" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul class="nav nav-pills nav-stacked">
          <li class="active"><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'home')) ?>" rel="ajax">Accueil</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'presentation')) ?>" rel="ajax">Présentation</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'statuts')) ?>" rel="ajax">Statuts</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'news', 'action' => 'index')) ?>" rel="ajax">News</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'charge')) ?>" rel="ajax">Prise en charge</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Nous aider -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" data-toggle="collapse" data-parent="#accordionMenu" href="#collapseAider">
        <i class="icone-aider pull-left"></i>Nous aider
      </a>
    </div>
    <div id="collapseAider" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'adherent')) ?>" rel="ajax" >Adhérer</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'parrainer')) ?>" rel="ajax" >Parrainer un chat</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'benevole')) ?>" rel="ajax">Devenir bénévole</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'fa', 'action' => 'index')) ?>" rel="ajax">Etre Famille d'Accueil</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'don')) ?>" rel="ajax">Faire un don</a></li>

        </ul>
      </div>
    </div>
  </div>

      <!-- FA -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-custom btn-large btn-primary" data-toggle="collapse" data-parent="#accordionMenu" href="#collapseFA">
        <i class="icone-home pull-left"></i>Familles d'accueil
      </a>
    </div>
    <div id="collapseFA" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul class="nav nav-pills nav-stacked">
		  <li><a href="#<?php echo $this->url(array('controller' => 'fa', 'action' => 'index')) ?>" rel="ajax">Etre Famille d'Accueil</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'demandesFA')) ?>" rel="ajax">Demande matériel/soins</a></li>
        </ul>
      </div>
    </div>
  </div>
  
  <!-- Les chats -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" data-toggle="collapse" data-parent="#accordionMenu" href="#collapseChats">
        <i class="icone-empreinte pull-left"></i>Les chats
      </a>
    </div>
    <div id="collapseChats" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="#<?php echo $this->url(array('controller' => 'chat', 'action' => 'adoption')) ?>" rel="ajax">Chats à l'adoption</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'chat', 'action' => 'chercher')) ?>" rel="ajax">Trouvez votre chat</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'chat', 'action' => 'parrainer')) ?>" rel="ajax">Chats à parrainer</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'chat', 'action' => 'adoptes')) ?>" rel="ajax">Chats adoptés</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'chat', 'action' => 'disparus')) ?>" rel="ajax">Les disparus</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'perdus')) ?>" rel="ajax">Perdus/Trouvés</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'charge')) ?>" rel="ajax">Prise en charge</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Adopter -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" data-toggle="collapse" data-parent="#accordionMenu" href="#collapseAdopter">
        <i class="icone-pen pull-left"></i>Adopter
      </a>
    </div>
    <div id="collapseAdopter" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul class="nav nav-pills nav-stacked"> 
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'adoption')) ?>" rel="ajax">A lire avant d'adopter</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'tarifs')) ?>" rel="ajax">Tarifs</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'adoptant', 'action' => 'process')) ?>" rel="ajax">Poster sa candidature</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Conseils -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" data-toggle="collapse" data-parent="#accordionMenu" href="#collapseConseils">
        <i class="icone-info pull-left"></i>Conseils
      </a>
    </div>
    <div id="collapseConseils" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'arrivee')) ?>" rel="ajax">L'arrivée de votre chat</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'sante')) ?>" rel="ajax">Santé &amp; Alimentation</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'sterilisation')) ?>" rel="ajax">La stérilisation</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'dangers')) ?>" rel="ajax">Les dangers</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Liens -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'liens')) ?>" rel="ajax">
        <i class="icone-lien pull-left"></i>Liens
      </a>

    </div>
  </div>

  <!-- Forum -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" href="/forum/index.php">
        <i class="icone-message pull-left"></i>Forum
      </a>
    </div>
  </div>        
</div>
