<div class="accordion well" id="accordionMenu">
  <!-- Association -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" data-toggle="collapse" data-parent="#accordionMenu" href="#collapseAsso">
        <i class="icone-home pull-left"></i>L'association
      </a>
    </div>
    <div id="collapseAsso" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul class="nav nav-pills nav-stacked">
          <li class="active"><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'home')) ?>" rel="ajax" title="Accueil">Accueil</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'presentation')) ?>" rel="ajax" title="Présentation">Présentation</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'statuts')) ?>" rel="ajax" title="Statuts">Statuts</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'news', 'action' => 'index')) ?>" rel="ajax" title="News">News</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'charge')) ?>" rel="ajax" title="Prise en charge">Prise en charge</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Nous aider -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" data-toggle="collapse" data-parent="#accordionMenu" href="#collapseAider">
        <i class="icone-aider pull-left"></i>Nous aider
      </a>
    </div>
    <div id="collapseAider" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'adherent')) ?>" rel="ajax" title="Adhérer">Adhérer</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'parrainer')) ?>" rel="ajax" title="Parrainer un chat">Parrainer un chat</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'benevole')) ?>" rel="ajax" title="Devenir bénévole">Devenir bénévole</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'fa', 'action' => 'index')) ?>" rel="ajax" title="Etre Famille d'Accueil">Etre Famille d'Accueil</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Les chats -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" data-toggle="collapse" data-parent="#accordionMenu" href="#collapseChats">
        <i class="icone-empreinte pull-left"></i>Les chats
      </a>
    </div>
    <div id="collapseChats" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="#<?php echo $this->url(array('controller' => 'chat', 'action' => 'adoption')) ?>" rel="ajax" title="Chats à l'adoption">Chats à l'adoption</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'chat', 'action' => 'adoptes')) ?>" rel="ajax" title="Chats adoptés">Chats adoptés</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'chat', 'action' => 'parrainer')) ?>" rel="ajax" title="Chats à parrainer">Chats à parrainer</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'chat', 'action' => 'disparus')) ?>" rel="ajax" title="Les disparus">Les disparus</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'perdus')) ?>" rel="ajax" title="Perdus/Trouvé">Perdus/Trouvés</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'charge')) ?>" rel="ajax" title="Prise en charge">Prise en charge</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Adopter -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" data-toggle="collapse" data-parent="#accordionMenu" href="#collapseAdopter">
        <i class="icone-poussette pull-left"></i>Adopter
      </a>
    </div>
    <div id="collapseAdopter" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul class="nav nav-pills nav-stacked"> 
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'adoption')) ?>" rel="ajax" title="A lire avant toute adoption">A lire avant d'adopter</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'tarifs')) ?>" rel="ajax" title="Tarifs">Tarifs</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'adoptant', 'action' => 'process')) ?>" rel="ajax" title="Poster sa candidature">Poster sa candidature</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Conseils -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" data-toggle="collapse" data-parent="#accordionMenu" href="#collapseConseils">
        <i class="icone-info pull-left"></i>Conseils
      </a>
    </div>
    <div id="collapseConseils" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'arrivee')) ?>" rel="ajax" title="L'arrivée de votre chat">L'arrivée de votre chat</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'sante')) ?>" rel="ajax" title="Santé &amp; Alimentation">Santé &amp; Alimentation</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'sterilisation')) ?>" rel="ajax" title="La stérilisation">La stérilisation</a></li>
          <li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'dangers')) ?>" rel="ajax" title="Les Dangers">Les dangers</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Liens -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'liens')) ?>" rel="ajax" title="Liens">
        <i class="icone-lien pull-left"></i>Liens
      </a>

    </div>
  </div>

  <!-- Forum -->
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn btn-large btn-primary" href="/forum/index.php" title="Forum">
        <i class="icone-message pull-left"></i>Forum
      </a>
    </div>
  </div>        
</div>

<div class="visible-desktop">
  <?php echo $this->partial("index/reference.phtml"); ?>
</div>