<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<a class="brand" href="<?php echo $this->url(array('controller' => null, 'action' => null)) ?>"> <i class="icone-fp-medium"></i> Association Félin Possible</a>
		<?php if ($this->login) { ?>
		<a class="icone-power icone-nav" href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'logout')) ?>" title="Deconnexion [<?php echo $this->login ?>]"></a>
		<?php } ?>
		<!-- menu haut -->
		<ul class="nav pull-right">
			<li><a class="icone-twitter icone-nav" href="https://twitter.com/FelinPossible"></a></li>
			<li><a class="icone-facebook icone-nav" href="https://fr-fr.facebook.com/felinpossible"></a></li>
			<li><a class="icone-rss icone-nav" href="<?php echo $this->url(array('controller' => 'news', 'action' => 'flux')) ?>"></a></li>
		</ul>
		<ul class="nav pull-right">
			<li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'boutique')) ?>" rel="ajax">Boutique</a></li>
			<li><a href="/forum/index.php">Forum</a></li>
			<li><a href="#<?php echo $this->url(array('controller' => 'index', 'action' => 'contact')) ?>" rel="ajax">Nous contacter</a></li>
		</ul>
	</div>
</div>
