<ul>
  <li><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'boutique')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" style="width: 65px;">&nbsp;</a></li>
  <li><a href="/forum/index.php" style="width: 40px;">&nbsp;</a></li>
  <li><a href="<?php echo $url = $this->url(array('controller' => 'index', 'action' => 'contact')) ?>" onclick="showPage('<?php echo $url ?>'); return false;" style="width: 100px;">&nbsp;</a></li>
</ul>