<thead>
  <tr>
    <th field="#" width="18px" get="formatRowNum">#</th>
    <th field="id" hidden="true" width="24px">Id</th>
    <th field="token" hidden="true" width="25px">Token</th>
    <th field="dateDemande" width="90px" formatter="formatDate">Date Demande</th>
    <th field="nom" width="140px">Demandeur</th>
    <th field="login" width="90px">Login</th>
    <th field="nomChat" width="100px">Chat</th>
    <th field="dateVisite" width="90px" formatter="formatDate">Date Visite</th> 
    <th field="ficheGeneree" width="60px">Traitée</th>  
    <th field="soinIdent" width="35px">Ident</th>
    <th field="soinTests" width="35px">Tests</th>
    <th field="soinVaccins" width="35px">Vacc.</th>
    <th field="soinSterilisation" width="35px">Stéri.</th>
    <th field="soinVermifuge" width="35px">Vermi</th>
    <th field="soinAntiParasites" width="38px">Puces</th>
  </tr>
</thead>