<thead>
  <tr>
    <th field="#" width="18px" get="formatRowNum">#</th>
    <th field="id" hidden="true" width="24px">Id</th>
    <th field="token" hidden="true" width="25px">Token</th>
    <th field="dateDemande" width="100px" formatter="formatDate">Date Demande</th>
    <th field="nom" width="180px">Demandeur</th>
    <th field="login" width="100px">Login</th>
    <th field="nomChat" width="100px">Chat</th>
    <th field="dateVisite" width="100px" formatter="formatDate">Date Visite</th> 
    <th field="ficheGeneree" width="80px">Traitée</th>  
    <!--<th field="soinIdent" width="38px">Ident</th>
    <th field="soinTests" width="38px">Tests</th>
    <th field="soinVaccins" width="38px">Vacc.</th>
    <th field="soinSterilisation" width="35px">Stéri.</th>
    <th field="soinVermifuge" width="40px">Vermi</th>
    <th field="soinAntiParasites" width="40px">Puces</th>-->
    <th field="envoiVeto" width="150px">Envoi direct au véto</th>
  </tr>
</thead>