<div class="centre_principal">
	<p> <h3>Traitement de la fiche de soins </h5>
            
            <?php          
             if ($this->demandeTraitee == 1)
             {
                 echo '</br></br><b><font color="red" size="4">ATTENTION : Cette demande semble avoir déjà été traitée !</font></b>';
             }
            ?>
            
            <b><?php echo $this->form;?></b>
            
            <?php          
             if ($this->envoiVeto == 1)
             {
                 echo '<div align="center"><b><font color="red" size="4">A envoyer directement au vétérinaire</font></b></div>';
             }
             else
             {
                 echo '<div align="center"><font color="green" size="3">A envoyer à la famille d\'accueil</font></div>';
             }
            ?>
        </p>
</br> 
</br>
</div>

<div class="centre_principal">
	<em><a href="../index">Retour à l'accueil</a>
	</em>
</div>