<div class="centre_principal">
	<p> <h3>Traitement de la fiche de soins </h5>
            
            <?php          
             if ($this->demandeTraitee == 1)
             {
                 echo '</br></br><b><font color="red" size="4">ATTENTION : Cette demande semble avoir déjà été traitée !</font></b>';
             }
            ?>
            
            <b><?php echo $this->form;?></b>
        </p>
</br> 
</br>
</div>

<div class="centre_principal">
	<em><a href="../index">Retour à l'accueil</a>
	</em>
</div>