<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.2.0.1 setup script by Piotr Przybylski <piotrprz@gmail.com>
 * Date: Sat, 05 Sep 2009 11:41:05 +0200
 */

/* Servers configuration */
$i = 0;

/* Server: felinpossible [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'felinpossible';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['ForceSSL'] = false;
$cfg['DefaultLang'] = 'fr-utf-8';
$cfg['ServerDefault'] = 1;
$cfg['blowfish_secret'] = '4aa231e7cebb73.75492474';
?>