
<div class="centre_principal">
    <p>
        Ajoutez dans le tableau ci-dessous tous les matériels dont vous avez besoin (en cliquant sur 'ajouter') puis cliquez sur "envoyer" en bas de la page pour soumettre votre demande :</br></br>
   </p>

  <div id="chargementMateriels" class="ajax" style="display:none"></div>
<div class="centre_principal">
	<?php echo $this->render("stock/indexgridmat.phtml"); ?>
     
<div>
<form class="formOrange" id="DemandeMateriel" action="/stock/storedem/" enctype="application/x-www-form-urlencoded" method="post">
    <input type="hidden" name="idd" value="<?php echo $this->idd;?>">
    <br/>
    <hr><hr>
    <br/>  
    
    Commentaires : <i><span style="color: OrangeRed;font-size:80%">Ajouter tous vos articles AVANT de saisir un commentaire</span></i>
    <textarea name="commentaire" rows="3"></textarea>
    <dt id="submit-label">&nbsp;</dt><dd id="submit-element">
    <input name="submit" class="btn btn-primary" id="submit" type="submit" value="Envoyer"></dd></dl>
</form>
</div> 
</div>
</div>