
<div class="centre_principal">
    <p>
        Ajoutez ci-dessous tous les matériels dont vous avez besoin (en cliquant sur 'ajouter') puis cliquez sur "envoyer" :</br></br>
   </p>

  <div id="chargementMateriels" class="ajax" style="display:none"></div>
<div class="centre_principal">
	<?php echo $this->render("stock/indexgridmat.phtml"); ?>
     
<div>
<form class="formOrange" id="DemandeMateriel" action="/stock/storedem/" enctype="application/x-www-form-urlencoded" method="post">
   <!-- <dl class="zend_form">Commentaire : 
        <textarea name="commentaires" rows="4" cols="50" ></textarea>-->
    <input type="hidden" name="idd" value="<?php echo $this->idd;?>">
    <dt id="submit-label">&nbsp;</dt><dd id="submit-element">
    <input name="submit" class="btn btn-primary" id="submit" type="submit" value="Envoyer"></dd></dl>
</form>
</div> 
</div>
</div>