<br/>
<form class="form-horizontal">
	<div class="control-group">
		<label class="control-label" for="filterLogin">Login</label>
		<div class="controls">
			<input class="search-query" data-dojo-type="dijit/form/TextBox" id="filterLogin" type="text" onkeyup="filterDemande('<?php echo $this->gridName ?>')" />
		</div>
	</div>
        <div class="control-group">
		<label class="control-label" for="filterNom">Nom</label>
		<div class="controls">
			<input class="search-query" data-dojo-type="dijit/form/TextBox" id="filterNom" type="text" onkeyup="filterDemande('<?php echo $this->gridName ?>')" />
		</div>
	</div>
</form>
