<br/>
<form class="form-horizontal" action="">
	<div class="control-group">
		<label class="control-label" for="filterDescriptionMateriel">DescriptionMateriel</label>
		<div class="controls">
			<input class="search-query" data-dojo-type="dijit/form/TextBox" id="filterDescriptionMateriel" type="text" onkeyup="filterMateriel('<?php echo $this->gridName ?>')" />
                </div>
	</div>

</form>
