<thead>
  <tr>
    <th field="id" width="20px" get="formatRowNum">#</th>
    <th field="DescriptionMateriel"  width="450px">Materiel</th>
    <th field="StockEnPret" width="80px" >Stock Prêté</th>
    <th field="StockRestant" width="82px" >Stock Restant</th>
    <th field="Unite" width="100px">Unite</th>
    <th field="libelle" width="100px">Categorie</th>
    <th field="SuiviPrets" width="35px">Suivi</th>
  </tr>
</thead>