<b>Votre demande a bien été prise en compte. 
    </br>Notre responsable du matériel vous contactera prochainement pour fixer un rendez-vous.</b>
    </br>
    </br><p>La majorité du matériel, des médicaments, et des croquettes est stockée à l'adresse suivante:
</br></br>
<b>KI-KAZH</b></br>
    9 rue Victor Hugo</br>
    35000 RENNES</br>
    02 99 51 96 67</br>
    contact@ki-kazh.com
</br></br>
<i>Horaires d'ouverture:</i></br>
    du mardi au samedi:</br>
    10h30 - 13h / 14h- 19h
</br></br>
Pour les croquettes, merci de venir <b>munis d'un contenant</b> pour les transporter, les croquettes de l'association étant en vrac.
    </p>