<?php if ($this->urlMaj) {?>
<div class="centre_principal">
	<?php if ($this->form->miniature->getValue() != "") {
		echo "<img class='img-rounded' src='".$this->form->miniature->getValue()."'/><br>";
	}?>
	<button class="btn" id="majButton" dojoType="dijit.form.Button" onclick="callAjax('<?php echo $this->urlMaj ?>'); return false;">Mettre à jour à partir des données du forum</button>
</div>
<?php }?>

<div class="centre_principal">
	<?php
	echo $this->form;
	?>
</div>