<div class="centre_principal">
	<em>Retrouvez plus d'infos et de photos de nos chats à adopter sur notre forum : <a href="http://felinpossible.fr/forum/index.php">cliquez ici <i class=" icon-comment"></i></a>
	</em>
</div>

<?php echo $this->render('chat/vignettesChats.phtml') ?>

<div class="centre_principal">
	<em>Retrouvez plus d'infos et de photos de nos chats à adopter sur notre forum : <a href="http://felinpossible.fr/forum/index.php">cliquez ici <i class=" icon-comment"></i></a>
	</em>
</div>