<div class="ligneText">
  <br>
  <b>Retrouvez plus d'infos et de photos de nos chats &agrave; adopter sur notre forum : <a href="http://felinpossible.fr/forum/index.php">cliquez ici</a></b>
</div>
<br>
<div class="spacer"></div>

<?php echo $this->render('chat/vignettesChats.phtml') ?>


<div class="ligneText">
  <br>
  <b>Retrouvez plus d'infos et de photos de nos chats &agrave; adopter sur notre forum : <a href="http://felinpossible.fr/forum/index.php">cliquez ici</a></b>
</div>