<div class="well">Retrouvez plus d'infos et de photos de nos chats &agrave; adopter sur notre forum : <a href="http://felinpossible.fr/forum/index.php">cliquez ici</a>
</div>

<div class="well">
	<?php echo $this->render('chat/vignettesChats.phtml') ?>
</div>

<div class="well">Retrouvez plus d'infos et de photos de nos chats &agrave; adopter sur notre forum : <a href="http://felinpossible.fr/forum/index.php">cliquez ici</a>
</div>