<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal">
<br>
<div class="formOrange">
	<?php if ($this->chat->nom) { ?>
	<p>
		<label class="colorFiche">Nom : </label>
		<label class="colorLabel"><?php echo $this->chat->nom ?></label>
	</p>
	<?php }?>
	
    <?php if ($this->chat->idSexe) { ?>
	<p>
		<label class="colorFiche">Sexe : </label>
		<label class="colorLabel"><?php echo $this->chat->libelleSexe ?></label>		
	</p>
	<?php }?>
	
	<?php if ($this->chat->dateNaissance) { ?>	
	<p>
		<label class="colorFiche">Date de naissance : </label>
		<label class="colorLabel"><?php echo FP_Util_DateUtil::getDateFormatted($this->chat->dateNaissance)?></label>
	</p>
	<?php }?>
	
	<?php if ($this->chat->dateAdoption) { ?>
	<p>
		<label class="colorFiche">Date d'adoption : </label>
		<label class="colorLabel"><?php echo FP_Util_DateUtil::getDateFormatted($this->chat->dateAdoption) ?></label>
	</p>
	<?php }?>
	
    <?php if ($this->chat->race) { ?>
	<p>
		<label class="colorFiche">Race : </label>
		<label class="colorLabel"><?php echo $this->chat->race ?></label>
	</p>
	<?php }?>
	
    <?php if ($this->chat->idCouleur) { ?>
	<p>
		<label class="colorFiche">Couleur : </label>
		<label class="colorLabel"><?php echo $this->chat->libelleCouleur ?></label>
	</p>
	<?php }?>
	
    <?php if ($this->chat->yeux) { ?>
	<p>
		<label class="colorFiche">Yeux : </label>
		<label class="colorLabel"><?php echo $this->chat->yeux ?></label>
	</p>
	<?php }?>
	
    <?php if ($this->chat->tests) { ?>
	<p>
		<label class="colorFiche">Tests : </label>
		<label class="colorLabel"><?php echo $this->chat->tests ?></label>
	</p>
	<?php }?>
	
    <?php if ($this->chat->vaccins) { ?>
	<p>
		<label class="colorFiche">Vaccins : </label>
		<label class="colorLabel"><?php echo $this->chat->vaccins ?></label>
	</p>
	<?php }?>
	
    <?php if ($this->chat->tatouage) { ?>
	<p>
		<label class="colorFiche">Tatouage : </label>
		<label class="colorLabel"><?php echo $this->chat->tatouage ?></label>
	</p>
	<?php }?>
	
    <?php if ($this->chat->caractere) { ?>	
	<p>
		<label class="colorFiche">Caract&egrave;re : </label>
		<label class="colorLabel"><?php echo $this->chat->caractere ?></label>
	</p>
	<?php }?>
	
    <?php if ($this->chat->commentaires) { ?>
	<p>
		<label class="colorFiche">Commentaires : </label>
		<label class="colorLabel"><?php echo $this->chat->commentaires ?></label>
	</p>
	<?php }?>
</div>
<br>
<div class="spacer"><br></div>
</div>
