<div class="centre_principal">
	<p> Parce que nous luttons au quotidien contre les abandons de chats, nous voulons être certains que vous pourrez trouver le chat qui vous conviendra parfaitement.
	</p>
	<p>
		<ul>
			<li><i class="icon-hand-right"></i> Vous avez déjà un chien et avez peur qu'ils ne s'entendent pas ?</li>
			<li><i class="icon-hand-right"></i> Vous cherchez un chat placide qui puisse supporter la présence de jeunes enfants ?</li>
			<li><i class="icon-hand-right"></i> Vous vivez en appartement et avez peur qu'il le supporte mal ?</li>
		</ul>
		<b>Nous sommes là pour vous aider</b> : parce que nos chats à l'adoption vivent en famille d'accueil, nous les connaissons bien.
	</p>
	<p>
		Ce formulaire vous permettra d'opérer un premier parcours des chats dont nous nous occupons actuellement. Vous pourrez ainsi vous assurer que la boule de poils qui vous fera chavirer sera parfaitement adaptée à vos conditions de vie.
	</p>
	<p>
		Quoi qu'il en soit, n'hésitez pas à remplir le <a href='http://felinpossible.fr/#/adoptant/process'>formulaire d'adoption</a> (sans engagement). Nos chargés d'adoptions vous recontacteront pour vous conseiller dans votre recherche.
	</p>
</div>
<div class="centre_principal">
	<h5>Je recherche un chat : </h5></br>
	<?php
	echo $this->form;
	?>
</div>
