<form class="form-horizontal" action="">
	<div class="control-group">
		<label class="control-label" for="filterChatNom">Nom</label>
		<div class="controls">
			<input class="search-query" data-dojo-type="dijit/form/TextBox" id="filterChatNom" type="text" onkeyup="filterChat('<?php echo $this->gridName ?>')" />
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="filterChatValider">A valider</label>
		<div class="controls">
			<input class="search-query" data-dojo-type="dijit/form/CheckBox" id="filterChatValider" onchange="filterChat('<?php echo $this->gridName ?>')" />
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="filterChatAdoption">A l'adoption</label>
		<div class="controls">
			<input class="search-query" data-dojo-type="dijit/form/CheckBox" id="filterChatAdoption" onchange="filterChat('<?php echo $this->gridName ?>')" checked="true"/>

		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="filterChatReserve">Réservé</label>
		<div class="controls">
			<input class="search-query" data-dojo-type="dijit/form/CheckBox" id="filterChatReserve" onchange="filterChat('<?php echo $this->gridName ?>')" />
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="filterChatParrainer">A parrainer</label>
		<div class="controls">
			<input class="search-query" data-dojo-type="dijit/form/CheckBox" id="filterChatParrainer" onchange="filterChat('<?php echo $this->gridName ?>')" />
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="filterChatDisparu">Disparu</label>
		<div class="controls">
			<input class="search-query" data-dojo-type="dijit/form/CheckBox" id="filterChatDisparu" onchange="filterChat('<?php echo $this->gridName ?>')" />
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="">Sans contrat</label>
		<div class="controls">
			<input class="search-query" data-dojo-type="dijit/form/CheckBox" id="filterChatSansContrat" onchange="filterChat('<?php echo $this->gridName ?>')" />
		</div>
	</div>
</form>
