<thead>
  <tr>
    <th field="Nom" width="18px" get="formatRowNum">#</th>
    <th field="statutVisite" width="30px" formatter="formatStatutVPA">Vpa</th>
    <th field="nom" width="130px" formatter="formatUpperCaseBold">Nom chat</th>
    <th field="renomme" width="130px" formatter="formatUpperCaseBold">Renommé</th>
    <th field="adoptant" width="300px">Adoptant</th>
    <th field="date_adoption" width="100px" formatter="formatDate">Date adoption</th>
    <th field="visitePostPar" width="150px">Chargé VPA ?</th>
  </tr>
</thead>