<thead>
  <tr>
    <th field="Nom" width="18px" get="formatRowNum">#</th>
    <th field="id" hidden="true" width="25px">Id</th>
    <th field="nom" width="80px" formatter="formatUpperCaseBold">Nom</th>
    <th field="libSexe" width="30px" formatter="formatSexe">Sexe</th>
    <th field="date" width="90px" formatter="formatDate">Date de naissance</th>
    <th field="datePriseEnCharge" width="70px" hidden="true" formatter="formatDate">Date prise en charge</th>
    <th field="date_adoption" width="85px" formatter="formatDate">Date d'adoption</th>
    <th field="fa" width="110px">FA</th>
    <th field="adoptant" width="110px">Adoptant</th>
    <th field="dateRappelVaccins" width="70px" formatter="formatDateFutur">Date vaccins</th>
    <th field="dateSterilisation" width="70px" formatter="formatDateFuturSterilisation">Date stérilisation</th>
    <th field="sterilise" sortDesc="true" width="80px" formatter="formatBoolean">Stérilisé(e) ?</th>
    <th field="notesPrivees" width="110px">Notes</th>
    <th field="tests" hidden="true" width="70px">Tests</th>
    <th field="declCession" sortDesc="true" width="80px" formatter="formatBoolean">Déclaration de cession</th>
    <th field="statutVisite" sortDesc="true" width="80px" formatter="formatBoolean">Visite post-adoption</th>
    <th field="papierIdRecu" sortDesc="true" width="80px" formatter="formatBoolean">Papier id. reçu</th>
    <th field="chgtProprio" width="50px" formatter="formatBoolean">Chg Proprio</th>
  </tr>
</thead>