<thead>
  <tr>
    <th field="Nom" width="18px" get="formatRowNum">#</th>
    <th field="nom" width="80px" formatter="formatUpperCaseBold">Nom</th>
    <th field="renomme" width="80px" formatter="formatUpperCaseBold">Renommé</th>
    <th field="libSexe" width="25px" formatter="formatSexe">Sexe</th>
    <th field="date" width="60px" formatter="formatDate">Date de naissance</th>
    <th field="fa" width="80px">FA</th>
    <th field="adoptant" width="80px">Adoptant</th>
    <th field="date_adoption" hidden="true" width="60px" formatter="formatDate">Date d'adoption</th>
    <th field="dateEnvoiRappelSte" width="60px" formatter="formatDate">Date mail rappel</th>
    <th field="dateSterilisation" width="60px" formatter="formatDateFuturSterilisation">Date stérilisation</th>
    <th field="sterilise" sortDesc="true" width="30px" formatter="formatBoolean">Stérilisé(e) ?</th>
    <th field="notesPrivees" width="110px">Notes</th>
  </tr>
</thead>