<thead>
  <tr>
    <th field="Nom" width="18px" get="formatRowNum">#</th>
    <th field="nom" width="80px" formatter="formatUpperCaseBold">Nom</th>
    <th field="libSexe" width="30px" formatter="formatSexe">Sexe</th>
    <th field="date" width="80px" formatter="formatDate">Date de naissance</th>
    <th field="fa" width="150px">FA</th>
    <th field="adoptant" width="110px">Adoptant</th>
    <th field="dateEnvoiRappelVac" width="100px" formatter="formatDate">Date mail rappel</th>
    <th field="dateRappelVaccins" width="100px" formatter="formatDateFutur">Date vaccins</th>
    <th field="notesPrivees" width="400px">Notes</th>
  </tr>
</thead>