<thead>
  <tr>
    <th field="Nom" width="18px" get="formatRowNum">#</th>
    <th field="statutVisite" width="30px" formatter="formatBoolean">Vpa</th>
    <th field="nom" width="150px" formatter="formatUpperCaseBold">Nom chat</th>
    <th field="renomme" width="150px" formatter="formatUpperCaseBold">Renommé</th>
    <th field="adoptant" width="300px">Adoptant</th>
    <th field="date_adoption" width="120px" formatter="formatDate">Date d'adoption</th>
  </tr>
</thead>