<thead>
  <tr>
    <th field="Nom" width="18px" get="formatRowNum">#</th>
    <th field="nom" width="80px" formatter="formatUpperCaseBold">Nom</th>
    <th field="renomme" width="80px" formatter="formatUpperCaseBold">Renommé</th>
    <th field="libSexe" width="25px" formatter="formatSexe">Sx</th>
    <th field="date" width="80px" formatter="formatDate">Date de naissance</th>
    <th field="fa" width="120px">FA</th>
    <th field="adoptant" width="150px">Adoptant</th>
    <th field="date_adoption" width="80px" formatter="formatDate">Date d'adoption</th>
    <th field="chgtProprio" width="50px" formatter="formatBoolean">Chg Proprio</th>
    <th field="notesPrivees" width="500px">Notes</th>
  </tr>
</thead>