<div class="centre_principal">
  <div id="chargementChats" class="ajax" style="display:none"></div>
    <div id="chats">
      <?php echo $this->render("admin/indexgrid.phtml"); ?>
      <button class="btn btn-action" onclick="addItem('<?php echo $this->urlAddItem ?>')"><i class="icon-plus"></i> Ajouter</button>
      <button class="btn btn-action" onclick="editItem('<?php echo $this->urlEditItem ?>', 'commonGrid')"><i class="icon-pencil"></i> Editer</button>
      <button class="btn btn-action" onclick="editItem('<?php echo $this->urlGenererFicheSoins ?>', 'commonGrid')"><i class="icon-file"></i> Fiche soins</button>
      <button class="btn btn-action" onclick="deleteItem('<?php echo $this->urlDeleteItem ?>', 'commonGrid')"><i class="icon-trash"></i> Supprimer</button>
      <button class="btn btn-action" onclick="editItem('<?php echo $this->urlSelectFaItem ?>', 'commonGrid', 'corps', 'chargementCorps', false, 'idChat')"><i class="icon-home"></i> Choisir FA</button>
      <button class="btn btn-action" onclick="deleteItem('<?php echo $this->urlDeleteFa ?>', 'commonGrid', 'idChat')"><i class="icon-remove"></i> Aucune FA</button>
      <button class="btn btn-action" onclick="editItem('<?php echo $this->urlSelectAdItem ?>', 'commonGrid', 'corps', 'chargementCorps', false, 'idChat')"><i class="icon-user"></i> Choisir Adoptant</button>
      <button class="btn btn-action" onclick="deleteItem('<?php echo $this->urlDeleteAd ?>', 'commonGrid', 'idChat')"><i class="icon-remove"></i> Aucun adoptant</button>
  </div>
</div>