<div class="centre_principal">
  <?php echo $this->render("admin/indexgrid.phtml"); ?>
  <button class="btn btn-action" onclick="editItem('<?php echo $this->urlEnvoiMailItem ?>', 'commonGrid')"><i class="icon-envelope"></i> Envoyer un mail</button>
  <button class="btn btn-action" onclick="editItem('<?php echo $this->urlEditItem ?>', 'commonGrid')"><i class="icon-pencil"></i> Editer</button>
  <br>
</div>