<div class="centre_principal">
  <?php echo $this->render("admin/indexgrid.phtml"); ?>
  <button class="btn btn-action" onclick="editItem('<?php echo $this->urlEnvoiMailItem ?>', 'commonGrid')"><i class="icon-envelope"></i> Envoyer un mail à la FA</button>
  <button class="btn btn-action" onclick="editItem('<?php echo $this->urlEditItem ?>', 'commonGrid')"><i class="icon-pencil"></i> Editer</button>
  <button class="btn btn-action" onclick="updateItem('<?php echo $this->urlIncrDateItem ?>', 'commonGrid')"><i class="icon-plus"></i> 1 an sur la date de vaccins</button>
  <br>
</div>