<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal">
  <br>
  <div id="lignesCat">
    <?php 
    $currentLigne = 0;
    $nbChatParLigne = $this->nbChatsParLigne;
    
    foreach ($this->entries as $entry): 
      if ($currentLigne%$nbChatParLigne == 0 ) {?>
        <!-- Nouvelle ligne -->
        <div class="ligne">
      <?php }?>
      <!-- Affichage vignette -->
        
      <span class="chatGauche">
        <a class="info_bulle" 
           href="<?php echo $entry->lienTopic ?>" 
           onMouseOver="showInfoBulleContent('<?php echo $this->url(array('action' => 'bulle', 'id' => $entry->id)) ?>', 'bulle<?php echo $entry->id ?>', 'chargementFicheChat<?php echo $entry->id ?>');" 
           onClick="hideElement('bulle<?php echo $entry->id ?>');">
             <img src="<?php echo $entry->miniature ?>" title="Cliquez ici pour plus d'infos sur <?php echo $entry->nom ?>" border="1"/>
             <br>
             <?php 
             echo $entry->nom; 
             if ($entry->getReserve()) {
             	if ($entry->getIdSexe() == FP_Util_Constantes::ID_SEXE_MALE){
             		echo " [RESERVE]";
             	} else {
             		echo " [RESERVEE]";
             	}
             }
             ?>
             
             <span id="bulle<?php echo $entry->id ?>" onClick="hideElement('bulle<?php echo $entry->id ?>');"></span>
        </a>
        <span id="chargementFicheChat<?php echo $entry->id ?>" class="ajax"></span>
      </span>
            
      <?php 
      $currentLigne++;
      if ($currentLigne%$nbChatParLigne == 0 ) {?>
        <!-- Fin nouvelle ligne -->
        </div>
      <?php }
    endforeach;
    if ($currentLigne%$nbChatParLigne != 0 ) {
       echo "</div>";
     }?>
  </div>
  <br>
  <div class="spacer"></div>
</div>