<?php if ($this->displayDiv) {?>
<div class="centre_principal">
<?php }?>

  <h3><?php echo $this->titre ?></h3>
  <br>
  <div data-dojo-type="dojox/data/QueryReadStore" clientSort="true" jsId="gridFaStore" url="<?php echo $this->urlFaListeJson ?>"></div>
  <?php echo $this->render('admin/filter.phtml'); ?>
  
  <div style="text-align:left">
    <?php if ($this->displayDiv) {?>
    <div class="grid">
    <?php } else { ?>
    <div class="chatFaAjoutGrid">
    <?php }?>
    
    <div data-dojo-type="dijit/Menu" jsid="gridMenuFa" style="display: none;">
        <div data-dojo-type="dojox/widget/PlaceholderMenuItem" label="GridColumns"></div>
    </div>
    
    <table id='gridFaSelection' 
           headerMenu="gridMenuFa"
           rowsPerPage="15" 
           columnReordering="true" 
           sortInfo="3" 
           jsId="gridChatSelection" 
           data-dojo-type="dojox/grid/DataGrid" 
           store="gridFaStore" 
           selectable="true" 
           selectionMode="single" 
           noDataMessage="Pas de FA">
      <?php echo $this->partial($this->headerFaPath) ?>
      <script type="dojo/connect" event="_onFetchBegin" args="event">initGrid(this.id);</script>
      <script type="dojo/connect" event="_onFetchComplete" args="event">endGrid(this.id);</script>
      <?php if ($this->displayDiv) {?>
        <script type="dojo/method" event="onDblClick" args="event">hideTooltip(event);editItem('<?php echo $this->urlSelectFa ?>', 'gridFaSelection',  'corps', 'chargementCorps', false, 'idNewFa')</script>
      <?php } else {?>  
        <script type="dojo/method" event="onDblClick" args="event">hideTooltip(event);editItem('<?php echo $this->urlSelectFa ?>', 'gridFaSelection',  'chats', 'chargementChats', false, 'idNewFa')</script>
      <?php }?>
        <script type="dojo/method" event="onCellMouseOver" args="event">showTooltipAjout(event)</script>
        <script type="dojo/method" event="onCellMouseOut" args="event">hideTooltip(event)</script>
    </table>
  </div>
</div>
<?php if ($this->displayDiv) {?>
  <button class="btn btn-action" onclick="editItem('<?php echo $this->urlSelectFa ?>', 'gridFaSelection',  'corps', 'chargementCorps', false, 'idNewFa')"><i class="icon-hand-up"></i> Sélectionner</button>
  <button class="btn btn-action" onclick="addItem('<?php echo $this->urlRetourListeChat ?>', 'corps', 'chargementCorps', false)"><i class="icon-arrow-left"></i> Retour</button>
</div>
<?php } else {?>  
  <button class="btn btn-action" onclick="editItem('<?php echo $this->urlSelectFa ?>', 'gridFaSelection',  'chats', 'chargementChats', false, 'idNewFa')"><i class="icon-hand-up"></i> Sélectionner</button>
  <button class="btn btn-action" onclick="addItem('<?php echo $this->urlRetourListeChat ?>', 'chats', 'chargementChats', false)"><i class="icon-arrow-left"></i> Retour</button>
<?php }?>