<div id="indispoStatutStore" style="display:none" data-dojo-type="dojo/data/ItemFileReadStore" jsId="indispoStatutStore" url="<?php echo $this->url(array('action' => 'listestatutsindispo')) ?>"></div>
Statut : 
<span>
  <input id="filterIndispoStatut" 
               data-dojo-type="dijit/form/FilteringSelect"
               store="indispoStatutStore"
               searchAttr="nom"
               autocomplete="true"
               ignoreCase="true"
               required="false"
               onchange="filterIndispo"/>
</span>