<div class="centre_principal">
  <?php echo $this->render('fa/infosfa.phtml')?>

    <table>
        <tr>
            <td width="250px"></td>
            <td width="200px">
                <button style="min-width:150px;padding:4px 12px;" 
                        class="btn-primary" onclick="window.open('#/stock/editemprunt/id/<?php echo $this->fiche->getId();?>')">
                        <i class="icon-search"></i> Matériels prêtés
                </button>
            </td>
        </tr>
    </table>
<br>
<div class="centre_principal">
  <div id="chargementChats" class="ajax" style="display:none"></div>
  <div id="chats">
    <?php echo $this->render('fa/gridchats.phtml')?>
  </div>
</div>
<br>
<div class="centre_principal">
  <div id="chargementIndispo" class="ajax" style="display:none"></div>
  <div id="indispo">
    <?php echo $this->render('fa/gridindispo.phtml')?>
  </div>
</div>