<div class="centre_principal">
  <?php echo $this->render('fa/infosfa.phtml')?>
</div>
<br>
<div class="centre_principal">
  <div id="chargementChats" class="ajax" style="display:none"></div>
  <div id="chats">
    <?php echo $this->render('fa/gridchats.phtml')?>
  </div>
</div>
<br>
<div class="centre_principal">
  <div id="chargementIndispo" class="ajax" style="display:none"></div>
  <div id="indispo">
    <?php echo $this->render('fa/gridindispo.phtml')?>
  </div>
</div>