  <h3><?php echo $this->titreChat ?></h3>
  <h4><span id="nbElements"><?php echo $this->nbChats?></span> chat(s)</h4>
  <br>
  <div data-dojo-type="dojox/data/QueryReadStore" sortInfo="3" clientSort="true" jsId="gridChatStore" url="<?php echo $this->urlChatListeJson ?>"></div>
  
  <div data-dojo-type="dijit/Menu" jsid="gridMenuFaChat" style="display: none;">
        <div data-dojo-type="dojox/widget/PlaceholderMenuItem" label="GridColumns"></div>
  </div>
  <div style="text-align:left">  
  <div class="chatFaGrid">
    <table id="gridChat" 
           rowsPerPage="15"
           headerMenu="gridMenuFaChat"
           columnReordering="true"
           sortInfo="3" 
           jsId="gridChat" 
           data-dojo-type="dojox/grid/DataGrid" 
           store="gridChatStore" 
           selectable="true" 
           selectionMode="single" 
           noDataMessage="Pas de chat dans cette famille d'accueil.">
      <script type="dojo/connect" event="_onFetchBegin" args="event">initGrid(this.id);</script>
      <script type="dojo/connect" event="_onFetchComplete" args="event">endGrid(this.id);</script>
      <?php echo $this->partial($this->headerChatPath) ?>
    </table>
  </div>
  </div>
  <button class="btn btn-action" onclick="addItem('<?php echo $this->urlChatAddItem ?>', 'chats', 'chargementChats', false)"><i class="icon-plus"></i> Ajouter</button>
  <button class="btn btn-action" onclick="editItem('<?php echo $this->urlChangerFa ?>', 'gridChat', 'chats', 'chargementChats', false, 'idChat')"><i class="icon-home"></i> Changer de FA</button>
  <button class="btn btn-action" onclick="deleteItem('<?php echo $this->urlChatDeleteItem ?>', 'gridChat', 'idChat')"><i class="icon-remove"></i> Supprimer de la FA</button>