  <h3><?php echo $this->titreIndispo ?></h3>
  <br>
  <div dojoType="dojox.data.QueryReadStore" sortInfo="-3" clientSort="true" jsId="gridIndispoStore" url="<?php echo $this->urlIndispoListeJson ?>"></div>

  <div dojoType="dijit.Menu" jsid="gridMenuIndisp" style="display: none;">
      <div dojoType="dojox.widget.PlaceholderMenuItem" label="GridColumns"></div>
  </div>
  <div style="text-align:left">
  <div class="indispoFaGrid">
<table id="gridIndispo" 
       headerMenu="gridMenuIndisp" 
       rowsPerPage="15" 
       columnReordering="true"
       sortInfo="-3" 
       jsId="gridIndispo" 
       dojoType="dojox.grid.DataGrid" 
       store="gridIndispoStore" 
       selectable="true" 
       noDataMessage="Aucune indisponibilité.">
	<?php echo $this->partial($this->headerIndispoPath) ?>
	<script type="dojo/connect" event="_onFetchBegin" args="event">initGrid(this.id);</script>
	<script type="dojo/connect" event="_onFetchComplete" args="event">endGrid(this.id);</script>
	<script type="dojo/method" event="onDblClick" args="event">hideTooltip(event);editItem('<?php echo $this->urlIndispoEdit ?>', 'gridIndispo', 'indispo', 'chargementIndispo', false, 'idIndispo')</script>
	<script type="dojo/method" event="onCellMouseOver" args="event">showTooltip(event)</script>
    <script type="dojo/method" event="onCellMouseOut" args="event">hideTooltip(event)</script>
</table>
</div>
</div>
  
  <button class="btn btn-action" onclick="addItem('<?php echo $this->urlIndispoAdd ?>', 'indispo', 'chargementIndispo', false)"><i class="icon-plus"></i> Ajouter</button>
  <button class="btn btn-action" onclick="editItem('<?php echo $this->urlIndispoEdit ?>', 'gridIndispo', 'indispo', 'chargementIndispo', false, 'idIndispo')"><i class="icon-pencil"></i> Editer</button>
  <button class="btn btn-action" onclick="deleteItem('<?php echo $this->urlIndispoDelete ?>', 'gridIndispo', 'idIndispo')"><i class="icon-trash"></i> Supprimer</button>