<thead>
  <tr>
    <th field="nom" width="18px" get="formatRowNum">#</th>
    <th field="id" hidden="true" width="18px">Id</th>
    <th field="dateSubmit" formatter="formatDate" width="90px">Date</th>
    <th field="nom" width="80px" formatter="formatUpperCaseBold">Nom</th>
    <th field="prenom" width="80px" formatter="formatUcfirst">Prénom</th>
    <th field="login" width="70px">Login</th>
    <th field="idStatut" width="22px" formatter="formatStatutFa">-</th>
    <th field="statutLib" width="65px" type="dojox/grid/cells/Select">Statut</th>
    <th field="chatsAccueil" width="90px">Chats en accueil</th>
    <th field="fiv" sortDesc="true" width="50px" formatter="formatBoolean">FIV</th>
    <th field="felv" sortDesc="true" width="50px" formatter="formatBoolean">FELV</th>
    <th field="quarantaine" sortDesc="true" width="50px" formatter="formatBoolean">Quarantaine</th>
    <th field="notes" width="150px">Notes</th>
    <th field="chats" width="150px">Chats</th>
    <th field="animaux" width="150px">Animaux</th>
    <th field="cp" hidden="true" width="40px">Code postal</th>
    <th field="ville" width="100px" formatter="formatUpperCase">Ville</th>
    <th field="email" width="80px">Email</th>
    <th field="portable" width="80px">Portable</th>
    <th field="fixe" width="80px">Fixe</th>
  </tr>
</thead>