<thead>
  <tr>
    <th field="id" width="18px" get="formatRowNum">#</th>
    <th field="id" hidden="true" width="18px">Id</th>
    <th field="dateDeb" width="80px" formatter="formatDate">Date de début</th>
    <th field="dateFin" width="80px" formatter="formatDate">Date de fin</th>
    <th field="idStatut" width="20px" formatter="formatStatutIndispo">-</th>
    <th field="libStatut" width="50px" >Statut</th>
    <th field="faLib" width="150px">FA</th>
    <th field="comment" width="400px">Commentaires</th>
  </tr>
</thead>