<?php include_once("../../spongestats/stats.php"); ?>
<div class="centre_principal">
<h2>Etre Famille d'Accueil</h2>
<br>
<ul>
  <li><a href="#ancreInfo">Qu'est-ce qu'une Famille d'Accueil ?</a></li>
  <li><a href="#ancrePostuler">Postuler</a></li>
</ul>
<br>
<p>
Notre association n'a pas de local, nous fonctionnons uniquement grâce au système des <b>Familles d'Accueil</b>,
souvent appelées <b>FA</b>. Les Familles d'Accueil sont <u>primordiales</u> pour notre association: sans elles, nous ne pouvons pas fonctionner,
car sans elles, nous ne pouvons pas accueillir de nouveaux petits pensionnaires.
</p>
<p>
Nous n'aurons jamais assez de Familles d'Accueil, c'est pourquoi nous faisons appel à toutes les bonnes volontés disposées à nous aider !
</p>

<h3><a name="ancreInfo">Qu'est-ce qu'une Famille d'Accueil ?</a></h3>

<p>
Etre Famille d'Accueil, c'est accepter d'ouvrir <u>temporairement</u> la porte de son foyer et celle de son coeur,
à une petite boule de poils, le temps de le soigner si besoin est, et de lui trouver une famille d'adoption définitive.
</p>

<p>
La <b>durée d'accueil</b> peut varier de quelques jours, à quelques semaines, voire quelques mois, selon le chat, son âge,
son état de santé, sa sociabilité etc... Néanmoins notre but est que les chats en accueil n'y restent pas trop longtemps,
d'une part pour qu'ils ne s'habituent pas trop à leur maison et leur famille d'accueil, et d'autre part, pour que la famille
d'accueil ne s'y attache pas trop non plus (car les chats sont tels que l'on s'y attache très vite !). Si la famille d'accueil a des impératifs (vacances ou autres), nous faisons en sorte de trouver auprès de notre réseau de Familles d'Accueil une autre
solution pour accueillir le chat pendant son absence.
</p>
<p>
Les Familles d'Accueil sont <b>responsables</b> du chat en accueil comme si c'était le leur. 
Elles sont chargées de lui prodiguer attention, amour et soins.
Il peut être demandé aux FA de conduire le chat chez le vétérinaire en cas d'urgence (dans le cas, la facture est envoyée directement à l'association, la FA n'a rien à débourser).
</p>
<p>
L'association prend en charge tous les <b>frais vétérinaires</b> concernant le chat en accueil, que ce soit les tests, les vaccins,
la stérilisation, l'identification, l'anti-puces, le vermifuge ou les soins divers. Elle peut également fournir des croquettes de qualité (Royal Canin) aux Familles d'Accueil, si celles-ci en font la demande.
Pour des raisons pratiques, il peut être demandé aux Familles d'Accueil de prendre en charge les frais de litière.
Si la famille d'accueil manque d'équipements (bac à litière, caisse de transport), l'association s'engage à lui en prêter sur simple demande.
</p>
<p>
La Famille d'Accueil peut bien sûr participer activement à la <b>recherche d'éventuels adoptants</b> si elle le souhaite..
Elle est d'ailleurs en charge de les recevoir, et de leur parler du chat, de son caractère, de ses habitudes.
Les visites se font, sauf exception, en présence d'un responsable de l'association, qui en profitera pour faire signer le contrat d'adoption si nécessaire.
Les familles d'accueil ont leur mot à dire sur le choix des adoptants, mais le choix définitif revient aux responsables de l'association.
</p>
<p>
Notre association travaille avec un <b>réseau de familles d'accueil</b> bénévoles.
En cas d'imprévu, nous nous engageons à reprendre le chat pour le placer dans une autre famille (à condition de nous laisser un peu de temps quand même ;) ).
</p>
<p>
Tous les chats placés en FA sont testés FIV/FELV, vaccinés, traités contre les parasites (puces, vers etc…), identifiés et stérilisés.
Selon les cas, nous pouvons cependant demander à la famille d'accueil, si celle-ci possède d'autres chats ou animaux,
de mettre le chat en <b>quarantaine</b> dans une pièce séparée pendant un certain temps, ceci aussi bien pour protéger les chats déjà en place que le chat en accueil.
</p>
<p>
Nous pouvons demander aux Familles d'Accueil d'effectuer un travail de <b>sociabilisation</b> pour des chats un peu craintifs.
Cependant, notre association ne s'occupant pas (pour le moment) des chats libres, nous ne prenons pas en charge les chats complètement sauvages.
Les Familles d'Accueil restent de toutes façons <b>libres</b> de refuser de prendre un chat en accueil et de définir leurs propres <b>critères d'accueil</b>.
</p>
<p>
Accueillir un chat chez vous en accueil vous apportera énormément au quotidien: des câlins, beaucoup d'amour et de tendresse, une oreille attentive toujours là pour vous écouter, une présence tout simplement, qui égayera votre maison et y apportera <br> vie et bonne humeur.
Avoir un chat en accueil vous procurera aussi le plaisir de vous sentir <b>utile</b> en sauvant un petit être, et celui d'agir en faveur de la cause animale. Le voir grandir, évoluer, s'ouvrir a vous petit à petit, vous procurera une immense satisfaction et un réel bonheur.
</p>
<p>
Désormais vous pouvez <b>postuler</b> pour être famille d'accueil pour notre association directement sur notre site en remplissant le formulaire de candidature ci-dessous.
</p>
<p>
Vous pouvez aussi nous contacter au <b>06 28 19 73 84</b>, par email à l'adresse <b>asso@felinpossible.fr</b> ou encore postuler sur notre <a href=http://felinpossible.fr/forum/viewtopic.php?f=13&t=29>forum de discussion</a>,
sur lequel vous trouverez le formulaire de candidature sur format Word.
</p>
<p>
Nous vous remercions, au nom de tous les chats, pour l’'intérêt que vous manifesterez à notre association, et l'aide que vous voudrez bien nous apporter.
</p>
<h3><a name="ancrePostuler">Postuler</a></h3>
<p>
Pour postuler maintenant comme Famille d'Accueil, veuillez cliquer sur ce lien: 
  <a href="<?php echo $this->url(array('controller' => 'fa', 'action' => 'process')) ?>"  
     onclick="showPage('<?php echo $this->url(array('controller' => 'fa', 'action' => 'process')) ?>'); return false;">
    Devenir Famille d'Accueil
  </a>.
</p>
</div>