<div class="centre_principal">
  <?php echo $this->render("admin/indexgrid.phtml"); ?>
  <button class="btn btn-action" onclick="editItem('<?php echo $this->urlEditItem ?>', 'commonGrid',  'corps', 'chargementCorps', false, 'idIndispo')"><i class="icon-pencil"></i> Editer</button>
  <button class="btn btn-action" onclick="deleteItem('<?php echo $this->urlDeleteItem ?>', 'commonGrid', 'idIndispo')"><i class="icon-trash"></i> Supprimer</button>
  <br>
</div>