<?php include_once("../../spongestats/stats.php"); ?>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
<?php foreach ($this->entries as $entry): ?>
      <div class='centre_principal'>
        <h4><?php echo $entry->titre ?>&nbsp;
          <em>rédigée le <?php echo date('d/m/Y à H\hi', $entry->timestampCreation) ?>
          </em>
        </h4>
        <p>
          <?php echo $entry->contenu ?>
        </p>
      </div>
<?php endforeach ?>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>