<?php include_once("../../spongestats/stats.php"); ?>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
<?php date_default_timezone_set('Europe/Paris'); 
foreach ($this->entries as $entry): ?>
<div class='centre_principal'>
	<h3><i class="icone-fp-medium"></i> <?php echo $entry->titre ?></h3>
	<p class="muted">
		<em>rédigée le <?php echo date('d/m/Y à H\hi', $entry->timestampCreation) ?>
		</em>
	</p>
	<p>
		<?php echo $entry->contenu ?>
	</p>
</div>
<?php endforeach ?>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>